### ISSUE TITLE
App crash at /extension/nevalla--kube-resource-map

### ISSUE THREAD

**Issue by floverdevel** [kontena/lens#3830]
**Describe the bug**
The kube-resource-map extension do not work since Lens 5.2.2-latest.20210917.1

**To Reproduce**
1. Install the kube-resource-map extension (@nevalla/kube-resource-map)
3. Open the Workload tab of a cluster (Or the Ressource Map tab of a cluster)
 
Component stack:
```
    at r (/Users/eantaya/.k8slens/extensions/nevalla--kube-resource-map/dist/renderer.js:7:595820)
    at ErrorBoundary (http://11a569ab806052b5067f12872917d387.localhost:55754/build/Lens.js:572185:47)
    at ErrorBoundary (http://11a569ab806052b5067f12872917d387.localhost:55754/build/Lens.js:572294:36)
    at main
    at div
    at http://11a569ab806052b5067f12872917d387.localhost:55754/build/Lens.js:9707:16
    at l (/Users/eantaya/.k8slens/extensions/nevalla--kube-resource-map/dist/renderer.js:226:13342)
    at Route (http://11a569ab806052b5067f12872917d387.localhost:55754/build/Lens.js:32471:29)
    at Switch (http://11a569ab806052b5067f12872917d387.localhost:55754/build/Lens.js:32641:29)
    at ErrorBoundary (http://11a569ab806052b5067f12872917d387.localhost:55754/build/Lens.js:572185:47)
    at ErrorBoundary (http://11a569ab806052b5067f12872917d387.localhost:55754/build/Lens.js:572294:36)
    at div
    at div
    at MainLayout (http://11a569ab806052b5067f12872917d387.localhost:55754/build/Lens.js:572724:9)
    at ErrorBoundary (http://11a569ab806052b5067f12872917d387.localhost:55754/build/Lens.js:572185:47)
    at ErrorBoundary (http://11a569ab806052b5067f12872917d387.localhost:55754/build/Lens.js:572294:36)
    at Router (http://11a569ab806052b5067f12872917d387.localhost:55754/build/Lens.js:32134:30)
    at App (http://11a569ab806052b5067f12872917d387.localhost:55754/build/Lens.js:666464:9)
    at ThemeProvider (http://11a569ab806052b5067f12872917d387.localhost:55754/build/Lens.js:700146:24)
```

Error stack:
```
TypeError: Cannot read property 'clientWidth' of undefined
    at render (/Users/eantaya/.k8slens/extensions/nevalla--kube-resource-map/dist/renderer.js:7:608021)
    at allowStateChanges (http://11a569ab806052b5067f12872917d387.localhost:55754/build/Lens.js:1472:12)
    at http://11a569ab806052b5067f12872917d387.localhost:55754/build/Lens.js:10151:59
    at trackDerivedFunction (http://11a569ab806052b5067f12872917d387.localhost:55754/build/Lens.js:2024:18)
    at Reaction.track (http://11a569ab806052b5067f12872917d387.localhost:55754/build/Lens.js:2552:18)
    at reactiveRender [as render] (http://11a569ab806052b5067f12872917d387.localhost:55754/build/Lens.js:10149:14)
    at r.makeComponentReactive (http://11a569ab806052b5067f12872917d387.localhost:55754/build/Lens.js:10164:25)
    at r.target.render (http://11a569ab806052b5067f12872917d387.localhost:55754/build/Lens.js:10077:34)
    at qi (http://11a569ab806052b5067f12872917d387.localhost:55754/build/Lens.js:535664:188)
    at pi (http://11a569ab806052b5067f12872917d387.localhost:55754/build/Lens.js:535663:173)
    at ck (http://11a569ab806052b5067f12872917d387.localhost:55754/build/Lens.js:535746:427)
    at bk (http://11a569ab806052b5067f12872917d387.localhost:55754/build/Lens.js:535727:347)
    at ak (http://11a569ab806052b5067f12872917d387.localhost:55754/build/Lens.js:535727:278)
    at Tj (http://11a569ab806052b5067f12872917d387.localhost:55754/build/Lens.js:535727:138)
    at Lj (http://11a569ab806052b5067f12872917d387.localhost:55754/build/Lens.js:535720:163)
    at http://11a569ab806052b5067f12872917d387.localhost:55754/build/Lens.js:535600:115
    at exports.unstable_runWithPriority (http://11a569ab806052b5067f12872917d387.localhost:55754/build/Lens.js:535811:343)
    at gg (http://11a569ab806052b5067f12872917d387.localhost:55754/build/Lens.js:535599:325)
    at jg (http://11a569ab806052b5067f12872917d387.localhost:55754/build/Lens.js:535600:61)
    at ig (http://11a569ab806052b5067f12872917d387.localhost:55754/build/Lens.js:535599:428)
    at Jg (http://11a569ab806052b5067f12872917d387.localhost:55754/build/Lens.js:535714:203)
    at Object.enqueueSetState (http://11a569ab806052b5067f12872917d387.localhost:55754/build/Lens.js:535610:211)
    at Router.C.setState (http://11a569ab806052b5067f12872917d387.localhost:55754/build/Lens.js:459195:369)
    at http://11a569ab806052b5067f12872917d387.localhost:55754/build/Lens.js:32149:17
    at listener (http://11a569ab806052b5067f12872917d387.localhost:55754/build/Lens.js:103910:24)
    at http://11a569ab806052b5067f12872917d387.localhost:55754/build/Lens.js:103928:23
    at Array.forEach (<anonymous>)
    at Object.notifyListeners (http://11a569ab806052b5067f12872917d387.localhost:55754/build/Lens.js:103927:15)
    at setState (http://11a569ab806052b5067f12872917d387.localhost:55754/build/Lens.js:104043:23)
    at http://11a569ab806052b5067f12872917d387.localhost:55754/build/Lens.js:104066:11
    at Object.confirmTransitionTo (http://11a569ab806052b5067f12872917d387.localhost:55754/build/Lens.js:103900:7)
    at handlePop (http://11a569ab806052b5067f12872917d387.localhost:55754/build/Lens.js:104064:25)
    at handlePopState (http://11a569ab806052b5067f12872917d387.localhost:55754/build/Lens.js:104049:5)
```

**Expected behavior**
No error.

**Screenshots**
![Capture d’écran, le 2021-09-17 à 11 11 43](https://user-images.githubusercontent.com/1007857/133806678-bace9b16-8cdb-43f5-8bf7-00ed2a48773d.png)

**Environment (please complete the following information):**
- Lens Version:
  - Lens: 5.2.2-latest.20210917.1
  - Electron: 12.0.17
  - Chrome: 89.0.4389.128
  - Node: 14.16.0
  - © 2021 Mirantis, Inc.
- OS: OSX 10.14.6 (18G103)
- Installation method : with the dmg provided from https://k8slens.dev/

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
I used `open /Applications/Lens.app` but it just returns to the prompt and it opens the Lens application.  No logs there.
```
No log from terminal in MacOS ¯\_(ツ)_/¯
```

**Additional context**
The extension was working just fine this morning before i updated Lens to the latest version.
So i don't know if it's Lens's fault or the extension's fault.

**Comment by nevalla** [comment]
Fixed in extension. Please upgrade to version `v.1.0.1` (uninstall the extension and re-install by typing `@nevalla/kube-resource-map` into extension name field and click "Install" button)

**Comment by floverdevel** [comment]
I confirm that the 1.0.1 version of the extension fixes the problem.
Thank you very much 👍🏻
