### ISSUE TITLE
New LENS updated App crash at /workloads

### ISSUE THREAD

**Issue by LarryBetson** [kontena/lens#3832]
**Describe the bug**
After running the new update when I go to observe my workload overview I am now getting 
App crash at /workloads
Error stack:

 
TypeError: Cannot read property 'clientWidth' of undefined
```
    at render (C:\Users\\.k8slens\extensions\nevalla--kube-resource-map\dist\renderer.js:7:608021)
    at allowStateChanges (http://62ead164b3e03297f8182cd5e586e1c1.localhost:1535/build/Lens.js:1472:12)
    at http://62ead164b3e03297f8182cd5e586e1c1.localhost:1535/build/Lens.js:10151:59
    at trackDerivedFunction (http://62ead164b3e03297f8182cd5e586e1c1.localhost:1535/build/Lens.js:2024:18)
    at Reaction.track (http://62ead164b3e03297f8182cd5e586e1c1.localhost:1535/build/Lens.js:2552:18)
    at reactiveRender [as render] (http://62ead164b3e03297f8182cd5e586e1c1.localhost:1535/build/Lens.js:10149:14)
    at qi (http://62ead164b3e03297f8182cd5e586e1c1.localhost:1535/build/Lens.js:535664:188)
    at pi (http://62ead164b3e03297f8182cd5e586e1c1.localhost:1535/build/Lens.js:535663:173)
    at ck (http://62ead164b3e03297f8182cd5e586e1c1.localhost:1535/build/Lens.js:535746:427)
    at bk (http://62ead164b3e03297f8182cd5e586e1c1.localhost:1535/build/Lens.js:535727:347)
    at ak (http://62ead164b3e03297f8182cd5e586e1c1.localhost:1535/build/Lens.js:535727:278)
    at Tj (http://62ead164b3e03297f8182cd5e586e1c1.localhost:1535/build/Lens.js:535727:138)
    at Lj (http://62ead164b3e03297f8182cd5e586e1c1.localhost:1535/build/Lens.js:535720:163)
    at http://62ead164b3e03297f8182cd5e586e1c1.localhost:1535/build/Lens.js:535600:115
    at exports.unstable_runWithPriority (http://62ead164b3e03297f8182cd5e586e1c1.localhost:1535/build/Lens.js:535811:343)
    at gg (http://62ead164b3e03297f8182cd5e586e1c1.localhost:1535/build/Lens.js:535599:325)
    at jg (http://62ead164b3e03297f8182cd5e586e1c1.localhost:1535/build/Lens.js:535600:61)
    at ig (http://62ead164b3e03297f8182cd5e586e1c1.localhost:1535/build/Lens.js:535599:428)
    at Jg (http://62ead164b3e03297f8182cd5e586e1c1.localhost:1535/build/Lens.js:535714:203)
    at Object.enqueueSetState (http://62ead164b3e03297f8182cd5e586e1c1.localhost:1535/build/Lens.js:535610:211)
    at r.C.setState (http://62ead164b3e03297f8182cd5e586e1c1.localhost:1535/build/Lens.js:459195:369)
    at r.generateChartDataSeries (C:\Users\\.k8slens\extensions\nevalla--kube-resource-map\dist\renderer.js:7:597517)
    at r.displayChart (C:\Users\\.k8slens\extensions\nevalla--kube-resource-map\dist\renderer.js:7:597140)
    at r.componentDidMount (C:\Users\\.k8slens\extensions\nevalla--kube-resource-map\dist\renderer.js:7:597935)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Screenshots**
![image](https://user-images.githubusercontent.com/31968725/133839203-827bb6f7-5fbb-4e86-99ec-08a3f064bd67.png)

**Environment (please complete the following information):**
- Lens Version: Lens latest 
- OS: Windows 10

**Comment by systemmonkey42** [comment]
This has started happening to me.  It worked fine for a few days since the initial upgrade, then after deploying a HELM chart today, all copies of LENS pointing to this cluster are crashing with this error.

```
Lens: 5.2.1-latest.20210916.2
Electron: 12.0.17
Chrome: 89.0.4389.128
Node: 14.16.0
© 2021 Mirantis, Inc.
```

**Comment by utk231** [comment]
Facing the same issue in Lens Latest Release for all the clusters "Workload" Tab after I deployed 100 pods at once using a loop to one of the clusters.

**Comment by systemmonkey42** [comment]
Same error after update;

```
Lens: 5.2.2-latest.20210918.1
Electron: 12.0.17
Chrome: 89.0.4389.128
Node: 14.16.0
© 2021 Mirantis, Inc.
```

```
TypeError: Cannot read property 'clientWidth' of undefined
```

It does take longer to crash though.

On my desktop is always crashes, on my laptop it only sometimes crashes (which is an improvement 👍 )

EDIT: Yes - pointing to same cluster, same kube config, same namespace.

**Comment by systemmonkey42** [comment]
Just a thought - I was taking a closer look at the original screenshot above, and it references "kube resource map", a plugin I know I installed on my desktop, but not on my laptop.

I disabled it, and can now view the `workload/overciew` without crashing.

**Comment by systemmonkey42** [comment]
Note the fault is also logged here:  https://github.com/nevalla/lens-resource-map-extension/issues/12

The owner of the extension is looking into it.

**Comment by nevalla** [comment]
Fixed in extension. Please upgrade to version `v1.0.1` (uninstall the extension and re-install by typing `@nevalla/kube-resource-map` into extension name field and click "Install" button)
