### ISSUE TITLE
TypeError: Cannot read property 'clientWidth' of undefined

### ISSUE THREAD

**Issue by a1exus** [kontena/lens#3835]
**Describe the bug**

> see screenshot

**To Reproduce**
1. Go to `Workflow`
2. Click on `Overview`
3. ~~Scroll down to 'n/a'~~

**Expected behavior**

> not an error ;-)

**Screenshots**

<img width="1335" alt="Screen Shot 2021-09-19 at 10 14 40 PM" src="https://user-images.githubusercontent.com/447497/133951453-658889d1-cd8c-4db2-bd2d-425ee5c68226.png">

**Environment (please complete the following information):**
- Lens: 5.2.2-latest.20210918.1
- OS: macOS Big Sur 11.6
- Installation method (e.g. snap or AppImage in Linux): drag & drop

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Component stack:


    at r (/Users/alexus/.k8slens/extensions/nevalla--kube-resource-map/dist/renderer.js:7:595820)
    at div
    at div
    at Details
    at div
    at WorkloadsOverview (http://0ad90d4d525fd96d9516146f318460c0.localhost:60906/build/Lens.js:607550:34)
    at Route (http://0ad90d4d525fd96d9516146f318460c0.localhost:60906/build/Lens.js:32471:29)
    at Switch (http://0ad90d4d525fd96d9516146f318460c0.localhost:60906/build/Lens.js:32641:29)
    at ErrorBoundary (http://0ad90d4d525fd96d9516146f318460c0.localhost:60906/build/Lens.js:572185:47)
    at ErrorBoundary (http://0ad90d4d525fd96d9516146f318460c0.localhost:60906/build/Lens.js:572294:36)
    at main
    at div
    at http://0ad90d4d525fd96d9516146f318460c0.localhost:60906/build/Lens.js:9707:16
    at Workloads (http://0ad90d4d525fd96d9516146f318460c0.localhost:60906/build/Lens.js:610791:41)
    at Route (http://0ad90d4d525fd96d9516146f318460c0.localhost:60906/build/Lens.js:32471:29)
    at Switch (http://0ad90d4d525fd96d9516146f318460c0.localhost:60906/build/Lens.js:32641:29)
    at ErrorBoundary (http://0ad90d4d525fd96d9516146f318460c0.localhost:60906/build/Lens.js:572185:47)
    at ErrorBoundary (http://0ad90d4d525fd96d9516146f318460c0.localhost:60906/build/Lens.js:572294:36)
    at div
    at div
    at MainLayout (http://0ad90d4d525fd96d9516146f318460c0.localhost:60906/build/Lens.js:572724:9)
    at ErrorBoundary (http://0ad90d4d525fd96d9516146f318460c0.localhost:60906/build/Lens.js:572185:47)
    at ErrorBoundary (http://0ad90d4d525fd96d9516146f318460c0.localhost:60906/build/Lens.js:572294:36)
    at Router (http://0ad90d4d525fd96d9516146f318460c0.localhost:60906/build/Lens.js:32134:30)
    at App (http://0ad90d4d525fd96d9516146f318460c0.localhost:60906/build/Lens.js:666464:9)
    at ThemeProvider (http://0ad90d4d525fd96d9516146f318460c0.localhost:60906/build/Lens.js:700146:24)
```
```
Error stack:

 
TypeError: Cannot read property 'clientWidth' of undefined
    at render (/Users/alexus/.k8slens/extensions/nevalla--kube-resource-map/dist/renderer.js:7:608021)
    at allowStateChanges (http://0ad90d4d525fd96d9516146f318460c0.localhost:60906/build/Lens.js:1472:12)
    at http://0ad90d4d525fd96d9516146f318460c0.localhost:60906/build/Lens.js:10151:59
    at trackDerivedFunction (http://0ad90d4d525fd96d9516146f318460c0.localhost:60906/build/Lens.js:2024:18)
    at Reaction.track (http://0ad90d4d525fd96d9516146f318460c0.localhost:60906/build/Lens.js:2552:18)
    at reactiveRender [as render] (http://0ad90d4d525fd96d9516146f318460c0.localhost:60906/build/Lens.js:10149:14)
    at qi (http://0ad90d4d525fd96d9516146f318460c0.localhost:60906/build/Lens.js:535664:188)
    at pi (http://0ad90d4d525fd96d9516146f318460c0.localhost:60906/build/Lens.js:535663:173)
    at ck (http://0ad90d4d525fd96d9516146f318460c0.localhost:60906/build/Lens.js:535746:427)
    at bk (http://0ad90d4d525fd96d9516146f318460c0.localhost:60906/build/Lens.js:535727:347)
    at ak (http://0ad90d4d525fd96d9516146f318460c0.localhost:60906/build/Lens.js:535727:278)
    at Tj (http://0ad90d4d525fd96d9516146f318460c0.localhost:60906/build/Lens.js:535727:138)
    at Lj (http://0ad90d4d525fd96d9516146f318460c0.localhost:60906/build/Lens.js:535720:163)
    at http://0ad90d4d525fd96d9516146f318460c0.localhost:60906/build/Lens.js:535600:115
    at exports.unstable_runWithPriority (http://0ad90d4d525fd96d9516146f318460c0.localhost:60906/build/Lens.js:535811:343)
    at gg (http://0ad90d4d525fd96d9516146f318460c0.localhost:60906/build/Lens.js:535599:325)
    at jg (http://0ad90d4d525fd96d9516146f318460c0.localhost:60906/build/Lens.js:535600:61)
    at ig (http://0ad90d4d525fd96d9516146f318460c0.localhost:60906/build/Lens.js:535599:428)
    at Jg (http://0ad90d4d525fd96d9516146f318460c0.localhost:60906/build/Lens.js:535714:203)
    at Object.enqueueSetState (http://0ad90d4d525fd96d9516146f318460c0.localhost:60906/build/Lens.js:535610:211)
    at r.C.setState (http://0ad90d4d525fd96d9516146f318460c0.localhost:60906/build/Lens.js:459195:369)
    at r.generateChartDataSeries (/Users/alexus/.k8slens/extensions/nevalla--kube-resource-map/dist/renderer.js:7:597517)
    at r.displayChart (/Users/alexus/.k8slens/extensions/nevalla--kube-resource-map/dist/renderer.js:7:597140)
    at r.componentDidMount (/Users/alexus/.k8slens/extensions/nevalla--kube-resource-map/dist/renderer.js:7:597935)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

> nothing special about my kueconfig, previous version of `Lens` worked without any issue and it stopped after latest update (I was already on Lens 5)

**Additional context**

**Comment by systemmonkey42** [comment]
Are you using the Resource Map extension (https://github.com/nevalla/lens-resource-map-extension)

The latest version crashes with this extension installed.    see #3832 and https://github.com/nevalla/lens-resource-map-extension/issues/12

**Comment by nevalla** [comment]
Fixed in extension. Please upgrade to version `v1.0.1` (uninstall the extension and re-install by typing `@nevalla/kube-resource-map` into extension name field and click "Install" button)

**Comment by a1exus** [comment]
- @systemmonkey42 - yes 
- @nevalla - thanks! updated and confirm everything works now) thank you!
