### ISSUE TITLE
K8s Lens crach

### ISSUE THREAD

**Issue by charanm1985** [kontena/lens#3861]
App crash at /workloads

This is when i navigate to workload tab, this happens often

TypeError: Cannot read property 'clientWidth' of undefined
    at render (C:\Users\Chandra.SekharMallu\.k8slens\extensions\nevalla--kube-resource-map\dist\renderer.js:7:608021)
    at allowStateChanges (http://ae685c606379441fafc233c3d5dd3057.localhost:50487/build/Lens.js:1472:12)
    at http://ae685c606379441fafc233c3d5dd3057.localhost:50487/build/Lens.js:10151:59
    at trackDerivedFunction (http://ae685c606379441fafc233c3d5dd3057.localhost:50487/build/Lens.js:2024:18)

**Comment by Nokel81** [comment]
please install the latest version of the `@nevalla/lube-resource-map` extension. It should be 1.0.1
