### ISSUE TITLE
Crash in Workloads Tabs

### ISSUE THREAD

**Issue by m00nyONE** [kontena/lens#3889]
**Describe the bug**
The bug occures when loading one of the workload subcategories (Overview, Pods, Deployments, DaemonSets ... )

i know this has to do with the ressource map extension

**To Reproduce**
1. Go to 'Overview'
2. See error

**Expected behavior**
Behave normally and see the informations

**Screenshots**
![Bug-Lens](https://user-images.githubusercontent.com/23294566/134651757-d7570f70-c671-4de5-94ba-828599e5733c.png)

**Environment (please complete the following information):**
- Lens Version:
- OS: Linux ( Manjaro 5.12 )
- Installation method (AUR bin-release directly from github):

**Logs:**
Component stack:

    at r (/home/sm/.k8slens/extensions/nevalla--kube-resource-map/dist/renderer.js:7:595820)
    at div
    at div
    at Details
    at div
    at WorkloadsOverview (http://30bbe6314d2de07136d5f4cef5436f4d.localhost:43493/build/Lens.js:607438:34)
    at Route (http://30bbe6314d2de07136d5f4cef5436f4d.localhost:43493/build/Lens.js:32471:29)
    at Switch (http://30bbe6314d2de07136d5f4cef5436f4d.localhost:43493/build/Lens.js:32641:29)
    at ErrorBoundary (http://30bbe6314d2de07136d5f4cef5436f4d.localhost:43493/build/Lens.js:572072:47)
    at ErrorBoundary (http://30bbe6314d2de07136d5f4cef5436f4d.localhost:43493/build/Lens.js:572181:36)
    at main
    at div
    at http://30bbe6314d2de07136d5f4cef5436f4d.localhost:43493/build/Lens.js:9707:16
    at Workloads (http://30bbe6314d2de07136d5f4cef5436f4d.localhost:43493/build/Lens.js:610679:41)
    at Route (http://30bbe6314d2de07136d5f4cef5436f4d.localhost:43493/build/Lens.js:32471:29)
    at Switch (http://30bbe6314d2de07136d5f4cef5436f4d.localhost:43493/build/Lens.js:32641:29)
    at ErrorBoundary (http://30bbe6314d2de07136d5f4cef5436f4d.localhost:43493/build/Lens.js:572072:47)
    at ErrorBoundary (http://30bbe6314d2de07136d5f4cef5436f4d.localhost:43493/build/Lens.js:572181:36)
    at div
    at div
    at MainLayout (http://30bbe6314d2de07136d5f4cef5436f4d.localhost:43493/build/Lens.js:572611:9)
    at ErrorBoundary (http://30bbe6314d2de07136d5f4cef5436f4d.localhost:43493/build/Lens.js:572072:47)
    at ErrorBoundary (http://30bbe6314d2de07136d5f4cef5436f4d.localhost:43493/build/Lens.js:572181:36)
    at Router (http://30bbe6314d2de07136d5f4cef5436f4d.localhost:43493/build/Lens.js:32134:30)
    at App (http://30bbe6314d2de07136d5f4cef5436f4d.localhost:43493/build/Lens.js:666352:9)
    at ThemeProvider (http://30bbe6314d2de07136d5f4cef5436f4d.localhost:43493/build/Lens.js:700028:24)

Error stack:
 
    TypeError: Cannot read property 'clientWidth' of undefined
    at render (/home/sm/.k8slens/extensions/nevalla--kube-resource-map/dist/renderer.js:7:608021)
    at allowStateChanges (http://30bbe6314d2de07136d5f4cef5436f4d.localhost:43493/build/Lens.js:1472:12)
    at http://30bbe6314d2de07136d5f4cef5436f4d.localhost:43493/build/Lens.js:10151:59
    at trackDerivedFunction (http://30bbe6314d2de07136d5f4cef5436f4d.localhost:43493/build/Lens.js:2024:18)
    at Reaction.track (http://30bbe6314d2de07136d5f4cef5436f4d.localhost:43493/build/Lens.js:2552:18)
    at reactiveRender [as render] (http://30bbe6314d2de07136d5f4cef5436f4d.localhost:43493/build/Lens.js:10149:14)
    at qi (http://30bbe6314d2de07136d5f4cef5436f4d.localhost:43493/build/Lens.js:535639:188)
    at pi (http://30bbe6314d2de07136d5f4cef5436f4d.localhost:43493/build/Lens.js:535638:173)
    at ck (http://30bbe6314d2de07136d5f4cef5436f4d.localhost:43493/build/Lens.js:535721:427)
    at bk (http://30bbe6314d2de07136d5f4cef5436f4d.localhost:43493/build/Lens.js:535702:347)
    at ak (http://30bbe6314d2de07136d5f4cef5436f4d.localhost:43493/build/Lens.js:535702:278)
    at Tj (http://30bbe6314d2de07136d5f4cef5436f4d.localhost:43493/build/Lens.js:535702:138)
    at Lj (http://30bbe6314d2de07136d5f4cef5436f4d.localhost:43493/build/Lens.js:535695:163)
    at http://30bbe6314d2de07136d5f4cef5436f4d.localhost:43493/build/Lens.js:535575:115
    at exports.unstable_runWithPriority (http://30bbe6314d2de07136d5f4cef5436f4d.localhost:43493/build/Lens.js:535786:343)
    at gg (http://30bbe6314d2de07136d5f4cef5436f4d.localhost:43493/build/Lens.js:535574:325)
    at jg (http://30bbe6314d2de07136d5f4cef5436f4d.localhost:43493/build/Lens.js:535575:61)
    at ig (http://30bbe6314d2de07136d5f4cef5436f4d.localhost:43493/build/Lens.js:535574:428)
    at Jg (http://30bbe6314d2de07136d5f4cef5436f4d.localhost:43493/build/Lens.js:535689:203)
    at Object.enqueueSetState (http://30bbe6314d2de07136d5f4cef5436f4d.localhost:43493/build/Lens.js:535585:211)
    at r.C.setState (http://30bbe6314d2de07136d5f4cef5436f4d.localhost:43493/build/Lens.js:459170:369)
    at r.generateChartDataSeries (/home/sm/.k8slens/extensions/nevalla--kube-resource-map/dist/renderer.js:7:597517)
    at r.displayChart (/home/sm/.k8slens/extensions/nevalla--kube-resource-map/dist/renderer.js:7:597140)
    at r.componentDidMount (/home/sm/.k8slens/extensions/nevalla--kube-resource-map/dist/renderer.js:7:597935)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Kubeconfig:**
has nothing to do with it because the problem appeared after patch 5.2.4 - in 5.2.3 everything was fine

**Additional context**
The crash happends 2-3 seconds  after loading the overview tab

**Comment by nevalla** [comment]
Please upgrade kube resource map extension to version 1.0.1 (re-install the extension)

**Comment by SRBK21** [comment]
Hey guys! Not sure if you guys found the solution to it. We fixed the issue by deleting the data folder of lens, usually inside C drive program files folder but we were using one drive to save app data so it was inside C:/Users/<username>/AppData/Roaming/Lens/ Delete the lens folder and reinstall lens. This solved our issue.
