### ISSUE TITLE
An error occurs upon connecting to cluster

### ISSUE THREAD

**Issue by Drugoy** [kontena/lens#3907]
**Describe the bug**
An error occurs upon connecting to cluster.

**To Reproduce**
1. Run Lens
2. Open pre-saved cluster
3. Hit connect

**Expected behavior**
No error should occur.

**Environment (please complete the following information):**
- Lens Version: 5.2.4-latest.20210923.1
- OS: Windows 10
- Installation method (e.g. snap or AppImage in Linux): via installer

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Component stack:


at MonacoEditor (http://9736daf57e37e3b585319c83b21b8ffe.localhost:52861/build/Lens.js:107620:28)
at EditorPanel (http://9736daf57e37e3b585319c83b21b8ffe.localhost:52861/build/Lens.js:662549:9)
at div
at CreateResource (http://9736daf57e37e3b585319c83b21b8ffe.localhost:52861/build/Lens.js:662856:9)
at div
at div
at Dock (http://9736daf57e37e3b585319c83b21b8ffe.localhost:52861/build/Lens.js:665126:9)
at div
at div
at MainLayout (http://9736daf57e37e3b585319c83b21b8ffe.localhost:52861/build/Lens.js:572611:9)
at ErrorBoundary (http://9736daf57e37e3b585319c83b21b8ffe.localhost:52861/build/Lens.js:572072:47)
at ErrorBoundary (http://9736daf57e37e3b585319c83b21b8ffe.localhost:52861/build/Lens.js:572181:36)
at Router (http://9736daf57e37e3b585319c83b21b8ffe.localhost:52861/build/Lens.js:32134:30)
at App (http://9736daf57e37e3b585319c83b21b8ffe.localhost:52861/build/Lens.js:666352:9)
at ThemeProvider (http://9736daf57e37e3b585319c83b21b8ffe.localhost:52861/build/Lens.js:700028:24)
Error stack:


TypeError: Cannot read property 'toString' of undefined
at MODEL_ID (http://9736daf57e37e3b585319c83b21b8ffe.localhost:52861/build/Lens.js:195154:21)
at ModelServiceImpl.getModel (http://9736daf57e37e3b585319c83b21b8ffe.localhost:52861/build/Lens.js:195466:25)
at Object.getModel (http://9736daf57e37e3b585319c83b21b8ffe.localhost:52861/build/Lens.js:85029:65)
at MonacoModelsManager.getModel (http://9736daf57e37e3b585319c83b21b8ffe.localhost:52861/build/Lens.js:116765:90)
at Object.value [as editorDidMount] (http://9736daf57e37e3b585319c83b21b8ffe.localhost:52861/build/Lens.js:662575:83)
at MonacoEditor.editorDidMount (http://9736daf57e37e3b585319c83b21b8ffe.localhost:52861/build/Lens.js:107697:20)
at MonacoEditor.initMonaco (http://9736daf57e37e3b585319c83b21b8ffe.localhost:52861/build/Lens.js:107687:18)
at MonacoEditor.componentDidMount (http://9736daf57e37e3b585319c83b21b8ffe.localhost:52861/build/Lens.js:107628:14)
at Yi (http://9736daf57e37e3b585319c83b21b8ffe.localhost:52861/build/Lens.js:535671:411)
at dk (http://9736daf57e37e3b585319c83b21b8ffe.localhost:52861/build/Lens.js:535711:160)
at exports.unstable_runWithPriority (http://9736daf57e37e3b585319c83b21b8ffe.localhost:52861/build/Lens.js:535786:343)
at gg (http://9736daf57e37e3b585319c83b21b8ffe.localhost:52861/build/Lens.js:535574:325)
at Uj (http://9736daf57e37e3b585319c83b21b8ffe.localhost:52861/build/Lens.js:535704:279)
at Lj (http://9736daf57e37e3b585319c83b21b8ffe.localhost:52861/build/Lens.js:535695:371)
at http://9736daf57e37e3b585319c83b21b8ffe.localhost:52861/build/Lens.js:535575:115
at exports.unstable_runWithPriority (http://9736daf57e37e3b585319c83b21b8ffe.localhost:52861/build/Lens.js:535786:343)
at gg (http://9736daf57e37e3b585319c83b21b8ffe.localhost:52861/build/Lens.js:535574:325)
at jg (http://9736daf57e37e3b585319c83b21b8ffe.localhost:52861/build/Lens.js:535575:61)
at ig (http://9736daf57e37e3b585319c83b21b8ffe.localhost:52861/build/Lens.js:535574:428)
at Wj (http://9736daf57e37e3b585319c83b21b8ffe.localhost:52861/build/Lens.js:535696:190)
at reactionScheduler (http://9736daf57e37e3b585319c83b21b8ffe.localhost:52861/build/Lens.js:2679:12)
at http://9736daf57e37e3b585319c83b21b8ffe.localhost:52861/build/Lens.js:2680:14
at Gh (C:\Program Files\Lens\resources\extensions\lenscloud-lens-extension\dist\renderer.js:347:141185)
at reactionScheduler (http://9736daf57e37e3b585319c83b21b8ffe.localhost:52861/build/Lens.js:2679:12)
at runReactions (http://9736daf57e37e3b585319c83b21b8ffe.localhost:52861/build/Lens.js:2648:3)
at endBatch (http://9736daf57e37e3b585319c83b21b8ffe.localhost:52861/build/Lens.js:2315:5)
at _endAction (http://9736daf57e37e3b585319c83b21b8ffe.localhost:52861/build/Lens.js:1461:3)
at executeAction (http://9736daf57e37e3b585319c83b21b8ffe.localhost:52861/build/Lens.js:1414:5)
at storageHelper_StorageHelper.merge (http://9736daf57e37e3b585319c83b21b8ffe.localhost:52861/build/Lens.js:1393:12)
at value (http://9736daf57e37e3b585319c83b21b8ffe.localhost:52861/build/Lens.js:7191:26)
```

**Kubeconfig:**
I've checked that my kubeconfig is not malformed.

**Additional context**
Third time was the charm: it worked even though I hadn't changed anything.

**Comment by Nokel81** [comment]
Duplicate of https://github.com/lensapp/lens/issues/3972
