### ISSUE TITLE
autoupdate fails on alpha channel

### ISSUE THREAD

**Issue by jim-docker** [kontena/lens#4140]
In trying to update from 5.3.0-alpha.2 to alpha.3 these messages are logged:

info:  :black_small_square: [WINDOW-MANAGER]: Main window has reported that it has loaded +29ms
info:  :black_small_square: Update for version 5.3.0-alpha.2.20211013.1 is not available (latest version: 5.2.5-latest.20211001.2, downgrade is disallowed). +520ms
info:  :black_small_square: [UPDATE-CHECKER]: update not available from latest, will check null channel next +0ms
error:  :black_small_square: Error: Error: Channel must be a string, but got: null
  at Object.newError (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/out/index.js:47:19)
  at MacUpdater.set channel [as channel] (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:114:46)
  at MacUpdater.<anonymous> (/Applications/Lens.app/Contents/Resources/app.asar/static/build/main.js:1:264746)
  at MacUpdater.emit (events.js:315:20)
  at MacUpdater.EventEmitter.emit (domain.js:467:12)
  at MacUpdater.doCheckForUpdates (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:316:18)
  at runMicrotasks (<anonymous>)
  at processTicksAndRejections (internal/process/task_queues.js:93:5)
  at async du (/Applications/Lens.app/Contents/Resources/app.asar/static/build/main.js:1:264867)
  at async /Applications/Lens.app/Contents/Resources/app.asar/static/build/main.js:1:264775 +1ms
error:  ┏ [UPDATE-CHECKER]: failed with an error +0ms
error:  ┗ [1] { error: 'Error: Channel must be a string, but got: null' }

**Comment by Nokel81** [comment]
That problem has now been fixed, but the current problem is that auto-update doesn't do anything at all after downloading.
