### ISSUE TITLE
Dark clear during cluster connect in light theme UI

### ISSUE THREAD

**Issue by jim-docker** [kontena/lens#4408]
There is a flash of dark when connecting to a cluster for light theme UI.

https://user-images.githubusercontent.com/40840436/143148043-e4afaf0c-0e10-4644-a873-c5dfec10a63f.mov

5.3.0-beta.2

**Comment by DerGut** [comment]
It looks very similar in my case:


https://user-images.githubusercontent.com/12832754/143279830-df37a02b-f159-42e0-a7a7-d1b9a1646e9e.mov

I am running  Lens 5.2.7-latest.20211110.1 and macOS 12.0.1 on an M1 Pro.
I installed Lens yesterday and everything was working fine. After the first start today, I couldn't load the cluster page.

Neither restarting Lens, the Mac nor removing and re-adding the cluster to the kubeconfig seem to help.

Looking at the dev-tools console, I am getting a couple of errors but I am not sure whether they are related to the loading of the cluster page:
```
[IPC]: failed to send IPC message "extensions:renderer" to view "window=2"
"Error: Could not call remote method 'send'. Check that the method signature is correct. Underlying error: Object has been destroyed
Underlying stack: TypeError: Object has been destroyed
    at Object.b.send (electron/js2c/browser_init.js:161:2484)
    at /Applications/Lens.app/Contents/Resources/app.asar/node_modules/@electron/remote/dist/src/main/server.js:454:71
    at IpcMainImpl.<anonymous> (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/@electron/remote/dist/src/main/server.js:313:27)
    at IpcMainImpl.emit (events.js:315:20)
    at IpcMainImpl.EventEmitter.emit (domain.js:467:12)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:10374)
    at Object.emit (events.js:315:20)
    at Object.EventEmitter.emit (domain.js:467:12)
    at Object.emitter.emit (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/@sentry/electron/dist/main/integrations/electron.js:63:25)
"
```

**Comment by Nokel81** [comment]
@DerGut Actually what you are experiencing is #4018. Can you try the latest (and final beta) and see if your problem persists?

**Comment by DerGut** [comment]
Thanks! I'll move the conversation there 👍
