### ISSUE TITLE
App crash at /

### ISSUE THREAD

**Issue by utk231** [kontena/lens#4442]
**Describe the bug**
App crash at / while opening a single cluster. 

**To Reproduce**
1. Click on connect
2. Cluster resources not showing up
3. App Crashes (See error)

**Expected behavior**
Cluster Resources should open

**Screenshots**

<img width="1361" alt="Screenshot 2021-11-27 at 12 04 17 PM" src="https://user-images.githubusercontent.com/16745649/143671047-5347ab31-86eb-453b-9c53-dc0414ebd73d.png">

**Environment (please complete the following information):**
- Lens Version:Lens: 5.3.0-latest.20211125.
- OS: MacOS
- Installation method (e.g. snap or AppImage in Linux): .dmg

**Logs:**

```
Component stack:


    at wrappedComponent (http://032c1c3b972accbf835ce6bb7e03dc78.localhost:56202/build/Lens.js:10553:16)
    at div
    at Logs (http://032c1c3b972accbf835ce6bb7e03dc78.localhost:56202/build/chunks/5.js:7201:9)
    at div
    at div
    at Dock (http://032c1c3b972accbf835ce6bb7e03dc78.localhost:56202/build/chunks/5.js:7633:9)
    at div
    at div
    at MainLayout (http://032c1c3b972accbf835ce6bb7e03dc78.localhost:56202/build/Lens.js:286690:9)
    at ErrorBoundary (http://032c1c3b972accbf835ce6bb7e03dc78.localhost:56202/build/Lens.js:238000:9)
    at Router (http://032c1c3b972accbf835ce6bb7e03dc78.localhost:56202/build/Lens.js:79045:30)
    at ClusterFrame (http://032c1c3b972accbf835ce6bb7e03dc78.localhost:56202/build/chunks/5.js:7854:9)
    at ThemeProvider (http://032c1c3b972accbf835ce6bb7e03dc78.localhost:56202/build/Lens.js:604150:24)


Error stack:

TypeError: Cannot create a KubeObject from undefined
    at new KubeObject (http://032c1c3b972accbf835ce6bb7e03dc78.localhost:56202/build/Lens.js:32746:19)
    at new WorkloadKubeObject (http://032c1c3b972accbf835ce6bb7e03dc78.localhost:56202/build/Lens.js:124780:1)
    at new Pod (http://032c1c3b972accbf835ce6bb7e03dc78.localhost:56202/build/Lens.js:154478:9)
    at http://032c1c3b972accbf835ce6bb7e03dc78.localhost:56202/build/chunks/5.js:7133:17
    at http://032c1c3b972accbf835ce6bb7e03dc78.localhost:56202/build/Lens.js:10553:49
    at http://032c1c3b972accbf835ce6bb7e03dc78.localhost:56202/build/Lens.js:10517:25
    at trackDerivedFunction (http://032c1c3b972accbf835ce6bb7e03dc78.localhost:56202/build/Lens.js:3114:18)
    at Reaction.track (http://032c1c3b972accbf835ce6bb7e03dc78.localhost:56202/build/Lens.js:3642:18)
    at useObserver (http://032c1c3b972accbf835ce6bb7e03dc78.localhost:56202/build/Lens.js:10515:14)
    at wrappedComponent (http://032c1c3b972accbf835ce6bb7e03dc78.localhost:56202/build/Lens.js:10553:16)
    at Ch (http://032c1c3b972accbf835ce6bb7e03dc78.localhost:56202/build/Lens.js:550643:137)
    at li (http://032c1c3b972accbf835ce6bb7e03dc78.localhost:56202/build/Lens.js:550666:154)
    at ki (http://032c1c3b972accbf835ce6bb7e03dc78.localhost:56202/build/Lens.js:550664:169)
    at ii (http://032c1c3b972accbf835ce6bb7e03dc78.localhost:56202/build/Lens.js:550663:178)
    at ck (http://032c1c3b972accbf835ce6bb7e03dc78.localhost:56202/build/Lens.js:550760:126)
    at bk (http://032c1c3b972accbf835ce6bb7e03dc78.localhost:56202/build/Lens.js:550736:347)
```

**Additional context**
This issue started after I clicked on Daemon Set YAML edit in lens. Tried updating the Lens to latest version, Restarting the IDE, Clearing up the cache at `~/Library/Application\ Support/Lens/Cache/` and reconnecting the cluster but no luck.

**Comment by Nokel81** [comment]
I believe that this will be fixed by #4376

**Comment by utk231** [comment]
Thanks for the update @Nokel81 . Meanwhile this gets fixed, do you have any workaround for the same? I am unable to manage my main cluster due to this.

**Comment by vasyakrg** [comment]
Me too: App crash at opening a single cluster  :(

**Comment by Nokel81** [comment]
Yes, delete `~/Library/Application\ Support/Lens/lens-local-storage/032c1c3b972accbf835ce6bb7e03dc78.json`.

Your final file while be different. However the error message, like above, will give it to you.

**Comment by vasyakrg** [comment]
> Yes, delete `~/Library/Application\ Support/Lens/lens-local-storage/032c1c3b972accbf835ce6bb7e03dc78.json`.
> 
> Your final file while be different. However the error message, like above, will give it to you.

yes. worked.

**Comment by Nokel81** [comment]
Closing as this has been fixed in master.

Better fixes will be coming too.
