### ISSUE TITLE
Lens crashed while viewing pod logs; now always crashes for this single cluster only

### ISSUE THREAD

**Issue by mowings** [kontena/lens#4506]
**Describe the bug**
Lens now always crashes when attempting to connect to one of my clusters. The cluster is fully reachable. The issue begn when fetching a pod log. Lens crashed (info below) and then immediately crashes after connecting to this cluster (and only this single cluster). This behavior persists after restarting. The connection seems to be successful; the crash seems to actually occur
when attempting to display the cluster.

**To Reproduce**
Simply connect to the cluster in question. Lens crashes immediately. I cannot reproduce this behavior with any other cluster, unfortunately

**Expected behavior**
Lens would connect to the cluster and display the cluster screen

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 5.3.2-latest.20211201.1
- OS:  OSX
- Installation method: This version was the last upgrade taken

**Logs:**
Startup is fine. Only this cluster seems to crash. The error is as follows
`App crash at /`
```
Component stack:


    at wrappedComponent (http://3863dbca4b80df474930e0cfc76321c5.localhost:58504/build/Lens.js:10557:16)
    at div
    at Logs (http://3863dbca4b80df474930e0cfc76321c5.localhost:58504/build/chunks/5.js:7285:9)
    at div
    at div
    at Dock (http://3863dbca4b80df474930e0cfc76321c5.localhost:58504/build/chunks/5.js:7717:9)
    at div
    at div
    at MainLayout (http://3863dbca4b80df474930e0cfc76321c5.localhost:58504/build/Lens.js:286596:9)
    at ErrorBoundary (http://3863dbca4b80df474930e0cfc76321c5.localhost:58504/build/Lens.js:237949:9)
    at Router (http://3863dbca4b80df474930e0cfc76321c5.localhost:58504/build/Lens.js:79054:30)
    at ClusterFrame (http://3863dbca4b80df474930e0cfc76321c5.localhost:58504/build/chunks/5.js:7946:9)
    at ThemeProvider (http://3863dbca4b80df474930e0cfc76321c5.localhost:58504/build/Lens.js:609860:24)

Error stack:

TypeError: Cannot create a KubeObject from undefined
    at new KubeObject (http://3863dbca4b80df474930e0cfc76321c5.localhost:58504/build/Lens.js:32750:19)
    at new WorkloadKubeObject (http://3863dbca4b80df474930e0cfc76321c5.localhost:58504/build/Lens.js:124953:1)
    at new Pod (http://3863dbca4b80df474930e0cfc76321c5.localhost:58504/build/Lens.js:154508:9)
    at http://3863dbca4b80df474930e0cfc76321c5.localhost:58504/build/chunks/5.js:7217:17
    at http://3863dbca4b80df474930e0cfc76321c5.localhost:58504/build/Lens.js:10557:49
    at http://3863dbca4b80df474930e0cfc76321c5.localhost:58504/build/Lens.js:10521:25
    at trackDerivedFunction (http://3863dbca4b80df474930e0cfc76321c5.localhost:58504/build/Lens.js:3120:18)
    at Reaction.track (http://3863dbca4b80df474930e0cfc76321c5.localhost:58504/build/Lens.js:3649:18)
    at useObserver (http://3863dbca4b80df474930e0cfc76321c5.localhost:58504/build/Lens.js:10519:14)
    at wrappedComponent (http://3863dbca4b80df474930e0cfc76321c5.localhost:58504/build/Lens.js:10557:16)
    at Ch (http://3863dbca4b80df474930e0cfc76321c5.localhost:58504/build/Lens.js:556346:137)
    at li (http://3863dbca4b80df474930e0cfc76321c5.localhost:58504/build/Lens.js:556369:154)
    at ki (http://3863dbca4b80df474930e0cfc76321c5.localhost:58504/build/Lens.js:556367:169)
    at ii (http://3863dbca4b80df474930e0cfc76321c5.localhost:58504/build/Lens.js:556366:178)
    at ck (http://3863dbca4b80df474930e0cfc76321c5.localhost:58504/build/Lens.js:556463:126)
    at bk (http://3863dbca4b80df474930e0cfc76321c5.localhost:58504/build/Lens.js:556439:347)
```

**Kubeconfig:**
All other clusters in this file seem ok. I should note that I tried deleting this cluster from Lens; the delete attempt fails -- but with no error. Indeed, the problematic cluster was fine until the crash. I feel like if I could delete it and re-add it it would be fine

```
your kubeconfig here
```

**Additional context**

**Comment by mowings** [comment]
Interestingly, making a copy of the existing kube-config and resyncing from that does actually seem to fix the issue -- at least for now

**Comment by aleksfront** [comment]
Thanks for reporting this. We're working on the fix https://github.com/lensapp/lens/pull/4376

**Comment by Nokel81** [comment]
Closing as this has been fixed in master.

**Comment by gg-dt** [comment]
This happened to me again with Lens 5.3.4-latest.20220120.1 (which I guess does not contain the fixes from master yet).
Lens would not recover because it wanted to open the Log viewer for a Pod which was not there anymore. 
As a workaround I deleted the large JSON file in $HOME\AppData\Roaming\Lens\lens-local-storage

**Comment by locomoco28** [comment]
This happened to me aswell just now, the workaround that gg-dt posted above has helped.

I'm using the same Lens version as above

![grafik](https://user-images.githubusercontent.com/32169493/154310610-f51ce409-db9d-4168-86c0-d0109b6e7e21.png)

Edit:

Just now realized how recent the message of Nokel81 is and that the fix isn't live on stable yet. Looking forward for the next update :)
