### ISSUE TITLE
Lens not responding in latest versions

### ISSUE THREAD

**Issue by Razor0719** [kontena/lens#4526]
**Describe the bug**
not responding

**To Reproduce**
Always happens when typing on the command line
Sometimes it happens when you open the lens

**Expected behavior**
lens can work normally

**Screenshots**
![image](https://user-images.githubusercontent.com/19472866/145131512-a3cf5c8d-9b73-405f-a005-58cb105cdff8.png)
![image](https://user-images.githubusercontent.com/19472866/145131628-ba8326aa-0c38-4218-8dbc-fdae2c88fc80.png)

**Environment (please complete the following information):**
- Lens Version:
- Version of the last two weeks, with auto update
- Current Version:
- 
![image](https://user-images.githubusercontent.com/19472866/145131931-26628535-eb7a-409d-bc46-2e3a616b23b2.png)

- Windows 10

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
error: [KUBE-API] watch (weblink-11) throwed /apis/entities.k8slens.dev/v1/namespaces/default/weblinks?watch=1&resourceVersion= request to https://b11ae6dc-324c-466a-8f9a-f6fb5e72f5b9.catalog.k8slens.dev/apis/entities.k8slens.dev/v1/namespaces/default/weblinks?watch=1&resourceVersion=&timeoutSeconds=300 failed, reason: read ECONNRESET {"type":"system","errno":"ECONNRESET","code":"ECONNRESET","stack":"FetchError: request to https://b11ae6dc-324c-466a-8f9a-f6fb5e72f5b9.catalog.k8slens.dev/apis/entities.k8slens.dev/v1/namespaces/default/weblinks?watch=1&resourceVersion=&timeoutSeconds=300 failed, reason: read ECONNRESET\n    at ClientRequest.<anonymous> (C:\\Users\\Administrator\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\node-fetch\\lib\\index.js:1483:11)\n    at ClientRequest.emit (events.js:327:22)\n    at ClientRequest.EventEmitter.emit (domain.js:467:12)\n    at TLSSocket.socketErrorListener (_http_client.js:469:9)\n    at TLSSocket.emit (events.js:315:20)\n    at TLSSocket.EventEmitter.emit (domain.js:467:12)\n    at emitErrorNT (internal/streams/destroy.js:106:8)\n    at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)"}
info: [KUBE-API] watch (weblink-11) aborted /apis/entities.k8slens.dev/v1/namespaces/default/weblinks?watch=1&resourceVersion=
info: [KUBE-API] watch (weblink-12) started /apis/entities.k8slens.dev/v1/namespaces/default/weblinks?watch=1&resourceVersion=
info: [KUBE-API] watch (devcluster-16) error /apis/entities.k8slens.dev/v1beta1/namespaces/default/devclusters?watch=1&resourceVersion=
info: [KUBE-API] watch (devcluster-16) retried /apis/entities.k8slens.dev/v1beta1/namespaces/default/devclusters?watch=1&resourceVersion=
info: [CLUSTER]: refresh {"id":"e833db1194c32b4fafd2db33cabfa8d0","name":"275362819260395920-c675bec3d979649c9b2a01ab7bbeddd28","ready":true,"online":true,"accessible":true,"disconnected":false}
warn: [METRICS-ROUTE]: failed to get metrics for clusterId=e833db1194c32b4fafd2db33cabfa8d0: No Prometheus service found {"cause":["Error: Failed to list services for PrometheusLens in namespace='lens-metrics': services \"prometheus\" not found","Error: No service found for PrometheusHelm from any namespace","Error: No service found for PrometheusPrometheus Operator from any namespace","Error: Failed to list services for PrometheusStacklight in namespace='stacklight': services \"prometheus-server\" not found"],"stack":"Error: No Prometheus service found\n    at pa.getPrometheusService (C:\\Users\\Administrator\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\static\\build\\main.js:1:107284)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async pa.getPrometheusDetails (C:\\Users\\Administrator\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\static\\build\\main.js:1:106121)\n    at async Object.routeMetrics [as route] (C:\\Users\\Administrator\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\static\\build\\main.js:1:314745)\n    at async Cd.route (C:\\Users\\Administrator\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\static\\build\\main.js:1:328892)"}
info: [CLUSTER]: refresh {"id":"e833db1194c32b4fafd2db33cabfa8d0","name":"275362819260395920-c675bec3d979649c9b2a01ab7bbeddd28","ready":true,"online":true,"accessible":true,"disconnected":false}
info: [STORE]: SAVING C:\Users\Administrator\AppData\Roaming\Lens\extension-store\lenscloud-lens-extension\auth-token-store.json
info: [CLUSTER]: refresh {"id":"e833db1194c32b4fafd2db33cabfa8d0","name":"275362819260395920-c675bec3d979649c9b2a01ab7bbeddd28","ready":true,"online":true,"accessible":true,"disconnected":false}
info: [CLUSTER]: refresh {"id":"e833db1194c32b4fafd2db33cabfa8d0","name":"275362819260395920-c675bec3d979649c9b2a01ab7bbeddd28","ready":true,"online":true,"accessible":true,"disconnected":false}
warn: [METRICS-ROUTE]: failed to get metrics for clusterId=e833db1194c32b4fafd2db33cabfa8d0: No Prometheus service found {"cause":["Error: Failed to list services for PrometheusLens in namespace='lens-metrics': services \"prometheus\" not found","Error: No service found for PrometheusHelm from any namespace","Error: No service found for PrometheusPrometheus Operator from any namespace","Error: Failed to list services for PrometheusStacklight in namespace='stacklight': services \"prometheus-server\" not found"],"stack":"Error: No Prometheus service found\n    at pa.getPrometheusService (C:\\Users\\Administrator\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\static\\build\\main.js:1:107284)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async pa.getPrometheusDetails (C:\\Users\\Administrator\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\static\\build\\main.js:1:106121)\n    at async Object.routeMetrics [as route] (C:\\Users\\Administrator\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\static\\build\\main.js:1:314745)\n    at async Cd.route (C:\\Users\\Administrator\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\static\\build\\main.js:1:328892)"}
info: [CLUSTER]: refresh {"id":"e833db1194c32b4fafd2db33cabfa8d0","name":"275362819260395920-c675bec3d979649c9b2a01ab7bbeddd28","ready":true,"online":true,"accessible":true,"disconnected":false}
info: [CLUSTER]: refresh {"id":"e833db1194c32b4fafd2db33cabfa8d0","name":"275362819260395920-c675bec3d979649c9b2a01ab7bbeddd28","ready":true,"online":true,"accessible":true,"disconnected":false}
warn: [METRICS-ROUTE]: failed to get metrics for clusterId=e833db1194c32b4fafd2db33cabfa8d0: No Prometheus service found {"cause":["Error: Failed to list services for PrometheusLens in namespace='lens-metrics': services \"prometheus\" not found","Error: No service found for PrometheusHelm from any namespace","Error: No service found for PrometheusPrometheus Operator from any namespace","Error: Failed to list services for PrometheusStacklight in namespace='stacklight': services \"prometheus-server\" not found"],"stack":"Error: No Prometheus service found\n    at pa.getPrometheusService (C:\\Users\\Administrator\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\static\\build\\main.js:1:107284)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async pa.getPrometheusDetails (C:\\Users\\Administrator\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\static\\build\\main.js:1:106121)\n    at async Object.routeMetrics [as route] (C:\\Users\\Administrator\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\static\\build\\main.js:1:314745)\n    at async Cd.route (C:\\Users\\Administrator\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\static\\build\\main.js:1:328892)"}
info: [CLUSTER]: refresh {"id":"e833db1194c32b4fafd2db33cabfa8d0","name":"275362819260395920-c675bec3d979649c9b2a01ab7bbeddd28","ready":true,"online":true,"accessible":true,"disconnected":false}
warn: [METRICS-ROUTE]: failed to get metrics for clusterId=e833db1194c32b4fafd2db33cabfa8d0: No Prometheus service found {"cause":["Error: Failed to list services for PrometheusLens in namespace='lens-metrics': services \"prometheus\" not found","Error: No service found for PrometheusHelm from any namespace","Error: No service found for PrometheusPrometheus Operator from any namespace","Error: Failed to list services for PrometheusStacklight in namespace='stacklight': services \"prometheus-server\" not found"],"stack":"Error: No Prometheus service found\n    at pa.getPrometheusService (C:\\Users\\Administrator\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\static\\build\\main.js:1:107284)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async pa.getPrometheusDetails (C:\\Users\\Administrator\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\static\\build\\main.js:1:106121)\n    at async Object.routeMetrics [as route] (C:\\Users\\Administrator\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\static\\build\\main.js:1:314745)\n    at async Cd.route (C:\\Users\\Administrator\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\static\\build\\main.js:1:328892)"}
info: [KUBE-API] watch (devcluster-16) error /apis/entities.k8slens.dev/v1beta1/namespaces/default/devclusters?watch=1&resourceVersion=
info: [KUBE-API] watch (weblink-12) error /apis/entities.k8slens.dev/v1/namespaces/default/weblinks?watch=1&resourceVersion=
info: [CLUSTER]: refresh {"id":"e833db1194c32b4fafd2db33cabfa8d0","name":"275362819260395920-c675bec3d979649c9b2a01ab7bbeddd28","ready":true,"online":true,"accessible":true,"disconnected":false}
info: [KUBE-API] watch (devcluster-16) retried /apis/entities.k8slens.dev/v1beta1/namespaces/default/devclusters?watch=1&resourceVersion=
info: [KUBE-API] watch (weblink-12) retried /apis/entities.k8slens.dev/v1/namespaces/default/weblinks?watch=1&resourceVersion=
info: [CLUSTER]: refresh {"id":"e833db1194c32b4fafd2db33cabfa8d0","name":"275362819260395920-c675bec3d979649c9b2a01ab7bbeddd28","ready":true,"online":true,"accessible":true,"disconnected":false}
warn: [METRICS-ROUTE]: failed to get metrics for clusterId=e833db1194c32b4fafd2db33cabfa8d0: No Prometheus service found {"cause":["Error: Failed to list services for PrometheusLens in namespace='lens-metrics': services \"prometheus\" not found","Error: No service found for PrometheusHelm from any namespace","Error: No service found for PrometheusPrometheus Operator from any namespace","Error: Failed to list services for PrometheusStacklight in namespace='stacklight': services \"prometheus-server\" not found"],"stack":"Error: No Prometheus service found\n    at pa.getPrometheusService (C:\\Users\\Administrator\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\static\\build\\main.js:1:107284)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async pa.getPrometheusDetails (C:\\Users\\Administrator\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\static\\build\\main.js:1:106121)\n    at async Object.routeMetrics [as route] (C:\\Users\\Administrator\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\static\\build\\main.js:1:314745)\n    at async Cd.route (C:\\Users\\Administrator\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\static\\build\\main.js:1:328892)"}
info: [CLUSTER]: refresh {"id":"e833db1194c32b4fafd2db33cabfa8d0","name":"275362819260395920-c675bec3d979649c9b2a01ab7bbeddd28","ready":true,"online":true,"accessible":true,"disconnected":false}
info: [KUBE-API] watch (devcluster-16) error /apis/entities.k8slens.dev/v1beta1/namespaces/default/devclusters?watch=1&resourceVersion=
info: [KUBE-API] watch (weblink-12) error /apis/entities.k8slens.dev/v1/namespaces/default/weblinks?watch=1&resourceVersion=
info: [KUBE-API] watch (devcluster-16) retried /apis/entities.k8slens.dev/v1beta1/namespaces/default/devclusters?watch=1&resourceVersion=
info: [KUBE-API] watch (weblink-12) retried /apis/entities.k8slens.dev/v1/namespaces/default/weblinks?watch=1&resourceVersion=
info: [CLUSTER]: refresh {"id":"e833db1194c32b4fafd2db33cabfa8d0","name":"275362819260395920-c675bec3d979649c9b2a01ab7bbeddd28","ready":true,"online":true,"accessible":true,"disconnected":false}
warn: [METRICS-ROUTE]: failed to get metrics for clusterId=e833db1194c32b4fafd2db33cabfa8d0: No Prometheus service found {"cause":["Error: Failed to list services for PrometheusLens in namespace='lens-metrics': services \"prometheus\" not found","Error: No service found for PrometheusHelm from any namespace","Error: No service found for PrometheusPrometheus Operator from any namespace","Error: Failed to list services for PrometheusStacklight in namespace='stacklight': services \"prometheus-server\" not found"],"stack":"Error: No Prometheus service found\n    at pa.getPrometheusService (C:\\Users\\Administrator\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\static\\build\\main.js:1:107284)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async pa.getPrometheusDetails (C:\\Users\\Administrator\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\static\\build\\main.js:1:106121)\n    at async Object.routeMetrics [as route] (C:\\Users\\Administrator\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\static\\build\\main.js:1:314745)\n    at async Cd.route (C:\\Users\\Administrator\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\static\\build\\main.js:1:328892)"}
info: [CLUSTER]: refresh {"id":"e833db1194c32b4fafd2db33cabfa8d0","name":"275362819260395920-c675bec3d979649c9b2a01ab7bbeddd28","ready":true,"online":true,"accessible":true,"disconnected":false}
info: [CLUSTER]: refreshMetadata {"id":"e833db1194c32b4fafd2db33cabfa8d0","name":"275362819260395920-c675bec3d979649c9b2a01ab7bbeddd28","ready":true,"online":true,"accessible":true,"disconnected":false}
info: [STORE]: SAVING C:\Users\Administrator\AppData\Roaming\Lens\lens-cluster-store.json
info: [STORE]: SAVING C:\Users\Administrator\AppData\Roaming\Lens\extension-store\lenscloud-lens-extension\auth-token-store.json
info: [CLUSTER]: refresh {"id":"e833db1194c32b4fafd2db33cabfa8d0","name":"275362819260395920-c675bec3d979649c9b2a01ab7bbeddd28","ready":true,"online":true,"accessible":true,"disconnected":false}
warn: [METRICS-ROUTE]: failed to get metrics for clusterId=e833db1194c32b4fafd2db33cabfa8d0: No Prometheus service found {"cause":["Error: Failed to list services for PrometheusLens in namespace='lens-metrics': services \"prometheus\" not found","Error: No service found for PrometheusHelm from any namespace","Error: No service found for PrometheusPrometheus Operator from any namespace","Error: Failed to list services for PrometheusStacklight in namespace='stacklight': services \"prometheus-server\" not found"],"stack":"Error: No Prometheus service found\n    at pa.getPrometheusService (C:\\Users\\Administrator\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\static\\build\\main.js:1:107284)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async pa.getPrometheusDetails (C:\\Users\\Administrator\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\static\\build\\main.js:1:106121)\n    at async Object.routeMetrics [as route] (C:\\Users\\Administrator\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\static\\build\\main.js:1:314745)\n    at async Cd.route (C:\\Users\\Administrator\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\static\\build\\main.js:1:328892)"}
info: [KUBE-API] watch (weblink-12) error /apis/entities.k8slens.dev/v1/namespaces/default/weblinks?watch=1&resourceVersion=
info: [KUBE-API] watch (weblink-12) retried /apis/entities.k8slens.dev/v1/namespaces/default/weblinks?watch=1&resourceVersion=
error: [KUBE-API] watch (weblink-12) throwed /apis/entities.k8slens.dev/v1/namespaces/default/weblinks?watch=1&resourceVersion= request to https://b11ae6dc-324c-466a-8f9a-f6fb5e72f5b9.catalog.k8slens.dev/apis/entities.k8slens.dev/v1/namespaces/default/weblinks?watch=1&resourceVersion=&timeoutSeconds=300 failed, reason: read ECONNRESET {"type":"system","errno":"ECONNRESET","code":"ECONNRESET","stack":"FetchError: request to https://b11ae6dc-324c-466a-8f9a-f6fb5e72f5b9.catalog.k8slens.dev/apis/entities.k8slens.dev/v1/namespaces/default/weblinks?watch=1&resourceVersion=&timeoutSeconds=300 failed, reason: read ECONNRESET\n    at ClientRequest.<anonymous> (C:\\Users\\Administrator\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\node-fetch\\lib\\index.js:1483:11)\n    at ClientRequest.emit (events.js:327:22)\n    at ClientRequest.EventEmitter.emit (domain.js:467:12)\n    at TLSSocket.socketErrorListener (_http_client.js:469:9)\n    at TLSSocket.emit (events.js:315:20)\n    at TLSSocket.EventEmitter.emit (domain.js:467:12)\n    at emitErrorNT (internal/streams/destroy.js:106:8)\n    at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)"}
info: [KUBE-API] watch (weblink-12) aborted /apis/entities.k8slens.dev/v1/namespaces/default/weblinks?watch=1&resourceVersion=
info: [KUBE-API] watch (weblink-12) aborted /apis/entities.k8slens.dev/v1/namespaces/default/weblinks?watch=1&resourceVersion=
info: [KUBE-API] watch (weblink-12) aborted /apis/entities.k8slens.dev/v1/namespaces/default/weblinks?watch=1&resourceVersion=
info: [KUBE-API] watch (weblink-12) aborted /apis/entities.k8slens.dev/v1/namespaces/default/weblinks?watch=1&resourceVersion=
info: [KUBE-API] watch (weblink-13) started /apis/entities.k8slens.dev/v1/namespaces/default/weblinks?watch=1&resourceVersion=

```

**Comment by Razor0719** [comment]
i guess 
same as https://github.com/lensapp/lens/issues/4430 and https://github.com/lensapp/lens/issues/4490

**Comment by Nokel81** [comment]
Duplicate over those others
