### ISSUE TITLE
Lens doesn't show connected cluster data

### ISSUE THREAD

**Issue by ghost** [kontena/lens#4542]
Have updated LENS with the latest version and now it shows that cluster is connected but doesn't show cluster data (namespaces, pods etc.), just gray screen and that's it. Start application with logs and got message that certificate is missing.

**Expected behavior**
Choose existing cluster and see all its data

**Screenshots**
<img width="1792" alt="Screenshot 2021-12-09 at 14 32 14" src="https://user-images.githubusercontent.com/5645051/145393459-ce5d008b-7a6b-4a16-ab48-5e4126fec697.png">
<img width="1792" alt="Screenshot 2021-12-09 at 14 32 10" src="https://user-images.githubusercontent.com/5645051/145393501-26827558-559a-474a-8a3f-52d31f484a93.png">

**Environment (please complete the following information):**
- Lens Version: 5.3.2-latest.20211201.1
- OS: macOS Monterey V.12.0.1
- Installation method (e.g. snap or AppImage in Linux): dmg

**Logs:**

```
Last login: Thu Dec  9 14:55:57 on ttys003
user@users-MacBook-Pro ~ % /Applications/Lens.app/Contents/MacOS/Lens ; exit;
info:    ▪ 📟 Setting Lens as protocol client for lens:// +0ms
info:    ▪ 📟 Protocol client register succeeded ✅ +3ms
info:    ▪ [APP-PATHS]: initializing +0ms
info:    ▪ 🚀 Starting Lens from "/Applications/Lens.app/Contents/MacOS/Lens" +124ms
info:    ▪ 🐚 Syncing shell environment +1ms
info:    ▪ 💾 Loading stores +1s
info:    ▪ [USER-STORE]: LOADING from  ... +2ms
info:    ▪ [USER-STORE]: LOADED from /Users/sergei.budkevich/Library/Application Support/Lens/lens-user-store.json +22ms
info:    ▪ [CLUSTER-STORE]: LOADING from  ... +20ms
info:    ▪ [CLUSTER-STORE]: LOADED from /Users/sergei.budkevich/Library/Application Support/Lens/lens-cluster-store.json +12ms
info:    ▪ [HOTBAR-STORE]: LOADING from  ... +1ms
info:    ▪ [HOTBAR-STORE]: LOADED from /Users/sergei.budkevich/Library/Application Support/Lens/lens-hotbar-store.json +2ms
info:    ▪ [EXTENSIONS-STORE]: LOADING from  ... +0ms
info:    ▪ [EXTENSIONS-STORE]: LOADED from /Users/sergei.budkevich/Library/Application Support/Lens/lens-extensions.json +1ms
info:    ▪ [FILESYSTEM-PROVISIONER-STORE]: LOADING from  ... +1ms
info:    ▪ [FILESYSTEM-PROVISIONER-STORE]: LOADED from /Users/sergei.budkevich/Library/Application Support/Lens/lens-filesystem-provisioner-store.json +1ms
info:    ▪ [WEBLINK-STORE]: LOADING from  ... +0ms
info:    ▪ [WEBLINK-STORE]: LOADED from /Users/sergei.budkevich/Library/Application Support/Lens/lens-weblink-store.json +2ms
info:    ▪ 🔌 Starting LensProxy +10ms
info:    ▪ [LENS-PROXY]: Proxy server has started at 127.0.0.1:60065 +21ms
info:    ▪ 🔎 Testing LensProxy connection ... +1ms
info:    ▪ ⚡ LensProxy connection OK +18ms
info:    ▪ 🖥️  Starting WindowManager +5ms
info:    ▪ 🧩 Initializing extensions +117ms
info:    ▪ [EXTENSION-DISCOVERY] loading extensions from /Users/sergei.budkevich/Library/Application Support/Lens +0ms
info:    ▪ [EXTENSION-INSTALLER] installing dependencies at /Users/sergei.budkevich/Library/Application Support/Lens +215ms
info:    ▪ [WINDOW-MANAGER]: Loading Main window from url: http://localhost:60065 ... +493ms
info:    ▪ [EXTENSION-INSTALLER] dependencies installed at /Users/sergei.budkevich/Library/Application Support/Lens +942ms
info:    ▪ [EXTENSION-DISCOVERY] watching extension add/remove in /Users/sergei.budkevich/.k8slens/extensions +2ms
Native extraction module not loaded, msgpackr will still run, but with decreased performance. Cannot find module 'msgpackr-extract'
Lens Cloud Extension activated
info:    ▪ [EXTENSION-STORE-T]: LOADING from  ... +76ms
info:    ▪ [EXTENSION-STORE-T]: LOADED from /Users/sergei.budkevich/Library/Application Support/Lens/extension-store/lenscloud-lens-extension/auth-token-store.json +2ms
info:    ▪ [EXTENSION-STORE-T]: LOADING from  ... +2ms
info:    ▪ [EXTENSION-STORE-T]: LOADED from /Users/sergei.budkevich/Library/Application Support/Lens/extension-store/lens-survey/preferences-store.json +1ms
telemetry main extension activated
info:    ▪ [EXTENSION-STORE-T]: LOADING from  ... +41ms
info:    ▪ [EXTENSION-STORE-T]: LOADED from /Users/sergei.budkevich/Library/Application Support/Lens/extension-store/lens-telemetry/preferences-store.json +0ms
info:    ▪ [EXTENSION-STORE-T]: LOADING from  ... +5ms
info:    ▪ [EXTENSION-STORE-T]: LOADED from /Users/sergei.budkevich/Library/Application Support/Lens/extension-store/lenscloud-lens-extension/select-space-store.json +1ms
info:    ▪ [EXTENSION-STORE-T]: LOADING from  ... +430ms
info:    ▪ [EXTENSION-STORE-T]: LOADED from /Users/sergei.budkevich/Library/Application Support/Lens/extension-store/lenscloud-lens-extension/startup-store.json +1ms
info:    ▪ [EXTENSION]: enabled lens-license@5.3.2-latest.20211201.1 +0ms
info:    ▪ [EXTENSION]: enabled lens-survey@5.3.2-latest.20211201.1 +92ms
info:    ▪ [EXTENSION]: enabled lens-telemetry@5.3.2-latest.20211201.1 +0ms
info:    ┏ [IPC-RENDERER]: adding extension listener +15ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'deleteOneCluster',
info:    ┃ [3]   extension: { name: 'lenscloud-lens-extension', version: '5.3.2-latest.20211201.1' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension listener +2ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'deleteOneSpace',
info:    ┃ [3]   extension: { name: 'lenscloud-lens-extension', version: '5.3.2-latest.20211201.1' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension listener +0ms
info:    ┗ [1] { channel: 'logOut', extension: { name: 'lenscloud-lens-extension', version: '5.3.2-latest.20211201.1' } }
info:    ┏ [IPC-RENDERER]: adding extension listener +0ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'createWeblink',
info:    ┃ [3]   extension: { name: 'lenscloud-lens-extension', version: '5.3.2-latest.20211201.1' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension listener +1ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'deleteOneWeblink',
info:    ┃ [3]   extension: { name: 'lenscloud-lens-extension', version: '5.3.2-latest.20211201.1' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension listener +0ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'loadRemoteSpacesClusters',
info:    ┃ [3]   extension: { name: 'lenscloud-lens-extension', version: '5.3.2-latest.20211201.1' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension listener +0ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'createOneSpace',
info:    ┃ [3]   extension: { name: 'lenscloud-lens-extension', version: '5.3.2-latest.20211201.1' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension listener +0ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'leaveOneSpace',
info:    ┃ [3]   extension: { name: 'lenscloud-lens-extension', version: '5.3.2-latest.20211201.1' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension listener +0ms
info:    ┗ [1] { channel: 'selectSpace', extension: { name: 'lenscloud-lens-extension', version: '5.3.2-latest.20211201.1' } }
spaceId 3f9e7e2f-5f3f-4155-975c-18a5ce27c41b not found, selecting Personal Space
ERROR: Personal Space not found, space not found from spaces.
info:    ┏ [IPC-RENDERER]: adding extension listener +489ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'network:offline',
info:    ┃ [3]   extension: { name: 'lenscloud-lens-extension', version: '5.3.2-latest.20211201.1' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension listener +1ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'network:online',
info:    ┃ [3]   extension: { name: 'lenscloud-lens-extension', version: '5.3.2-latest.20211201.1' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension listener +0ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'provisionDevCluster',
info:    ┃ [3]   extension: { name: 'lenscloud-lens-extension', version: '5.3.2-latest.20211201.1' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension listener +1ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'removeDevCluster',
info:    ┃ [3]   extension: { name: 'lenscloud-lens-extension', version: '5.3.2-latest.20211201.1' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension listener +0ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'stopDevClusterEvent',
info:    ┃ [3]   extension: { name: 'lenscloud-lens-extension', version: '5.3.2-latest.20211201.1' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension listener +0ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'startDevClusterEvent',
info:    ┃ [3]   extension: { name: 'lenscloud-lens-extension', version: '5.3.2-latest.20211201.1' }
info:    ┗ [4] }
info:    ▪ [EXTENSION]: enabled lenscloud-lens-extension@5.3.2-latest.20211201.1 +0ms
info:    ▪ [WINDOW-MANAGER]: Main window loaded +921ms
info:    ▪ [KUBECONFIG-SYNC]: starting requested syncs +1s
info:    ┏ [KUBECONFIG-SYNC]: starting sync of file/folder +1ms
info:    ┗ [1] { filePath: '/Users/sergei.budkevich/Library/Application Support/Lens/kubeconfigs' }
info:    ┏ [KUBECONFIG-SYNC]: starting sync of file/folder +0ms
info:    ┗ [1] { filePath: '/Users/sergei.budkevich/.kube' }
info:    ▪ 📡 Checking for app updates +2ms
info:    ▪ [AUTO-UPDATE]: electron-updater: Checking for update +0ms
info:    ▪ [KUBECONFIG-SYNC]: ignoring '/Users/sergei.budkevich/.kube/.DS_Store' due to ignore glob: .DS_Store +5ms
info:    ▪ [WINDOW-MANAGER]: Main window has reported that it has loaded +42ms
info:    ▪ [AUTO-UPDATE]: electron-updater: Update for version 5.3.2-latest.20211201.1 is not available (latest version: 5.3.2-latest.20211201.1, downgrade is disallowed). +298ms
info:    ▪ [UPDATE-CHECKER]: update not available from latest, will check latest channel next +1ms
info:    ▪ [STORE]: SAVING /Users/sergei.budkevich/Library/Application Support/Lens/extension-store/lenscloud-lens-extension/auth-token-store.json +1s
[LENS-SPACES-EXTENSION]: Connecting to catalog api of Space id 3f9e7e2f-5f3f-4155-975c-18a5ce27c41b...
[LENS-SPACES-EXTENSION] Error getSpaceCa(), retrying... Error: Certificate authority missing for Space siarhei.budkevich catalog api https://3f9e7e2f-5f3f-4155-975c-18a5ce27c41b.catalog.lc-staging1.staging-k8slens.cloud
    at e.startingDelay [as request] (/Applications/Lens.app/Contents/Resources/extensions/lenscloud-lens-extension/dist/main.js:23:553236)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[LENS-SPACES-EXTENSION] Error getSpaceCa(), retrying... Error: Certificate authority missing for Space siarhei.budkevich catalog api https://3f9e7e2f-5f3f-4155-975c-18a5ce27c41b.catalog.lc-staging1.staging-k8slens.cloud
    at e.startingDelay [as request] (/Applications/Lens.app/Contents/Resources/extensions/lenscloud-lens-extension/dist/main.js:23:553236)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
info:    ┏ APP:ACTIVATE +14s
info:    ┗ [1] { hasVisibleWindows: true }
info:    ┏ [CLUSTER]: activate +3s
info:    ┃ [1] {
info:    ┃ [2]   id: '5ea24b78ea4ba376e0a8b65f547d153a',
info:    ┃ [3]   name: 'gke_third-hope-267810_us-central1-a_hackathon-cluster',
info:    ┃ [4]   ready: false,
info:    ┃ [5]   online: false,
info:    ┃ [6]   accessible: false,
info:    ┃ [7]   disconnected: true
info:    ┗ [8] }
info:    ┏ [CLUSTER]: bind events +0ms
info:    ┃ [1] {
info:    ┃ [2]   id: '5ea24b78ea4ba376e0a8b65f547d153a',
info:    ┃ [3]   name: 'gke_third-hope-267810_us-central1-a_hackathon-cluster',
info:    ┃ [4]   ready: false,
info:    ┃ [5]   online: false,
info:    ┃ [6]   accessible: false,
info:    ┃ [7]   disconnected: true
info:    ┗ [8] }
info:    ┏ [CLUSTER]: reconnect +1ms
info:    ┃ [1] {
info:    ┃ [2]   id: '5ea24b78ea4ba376e0a8b65f547d153a',
info:    ┃ [3]   name: 'gke_third-hope-267810_us-central1-a_hackathon-cluster',
info:    ┃ [4]   ready: false,
info:    ┃ [5]   online: false,
info:    ┃ [6]   accessible: false,
info:    ┃ [7]   disconnected: true
info:    ┗ [8] }
[LENS-SPACES-EXTENSION] Error getSpaceCa(), retrying... Error: Certificate authority missing for Space siarhei.budkevich catalog api https://3f9e7e2f-5f3f-4155-975c-18a5ce27c41b.catalog.lc-staging1.staging-k8slens.cloud
    at e.startingDelay [as request] (/Applications/Lens.app/Contents/Resources/extensions/lenscloud-lens-extension/dist/main.js:23:553236)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

```

**Comment by ghost** [comment]
Some manipulations with kubeconfig, removed and download them one more time and seems that it's ok now
