### ISSUE TITLE
App crash when viewing helm charts

### ISSUE THREAD

**Issue by NangiDev** [kontena/lens#4898]
**Describe the bug**
Press any charts resource and it will crash

**To Reproduce**
1. Go to 'Apps/Charts'
2. Click on any chart resource

**Expected behavior**
I expect to see the resource to be able to install it from inside the interface

**Screenshots**
![image](https://user-images.githubusercontent.com/8998287/154650359-d6c35905-fbcb-4e9e-aad8-1f55d08567e5.png)

**Environment (please complete the following information):**
- Lens Version: 5.3.4-latest.20220120.1
- OS: Windows 10
- Installation method (e.g. snap or AppImage in Linux): .Exe from website

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Component stack:


    at p
    at div
    at div
    at div
    at div
    at Animate (http://91fea776c5427d6b29213c157a893e5f.localhost:1073/build/Lens.js:148420:9)
    at drawer_Drawer (http://91fea776c5427d6b29213c157a893e5f.localhost:1073/build/Lens.js:14197:9)
    at HelmChartDetails (http://91fea776c5427d6b29213c157a893e5f.localhost:1073/build/chunks/5.js:2871:9)
    at HelmCharts (http://91fea776c5427d6b29213c157a893e5f.localhost:1073/build/chunks/5.js:3074:9)
    at Route (http://91fea776c5427d6b29213c157a893e5f.localhost:1073/build/Lens.js:79343:29)
    at Switch (http://91fea776c5427d6b29213c157a893e5f.localhost:1073/build/Lens.js:79509:29)
    at ErrorBoundary (http://91fea776c5427d6b29213c157a893e5f.localhost:1073/build/Lens.js:238009:9)
    at main
    at div
    at wrappedComponent (http://91fea776c5427d6b29213c157a893e5f.localhost:1073/build/Lens.js:10507:16)
    at Apps (http://91fea776c5427d6b29213c157a893e5f.localhost:1073/build/chunks/5.js:4494:26)
    at Route (http://91fea776c5427d6b29213c157a893e5f.localhost:1073/build/Lens.js:79343:29)
    at Switch (http://91fea776c5427d6b29213c157a893e5f.localhost:1073/build/Lens.js:79509:29)
    at ErrorBoundary (http://91fea776c5427d6b29213c157a893e5f.localhost:1073/build/Lens.js:238009:9)
    at div
    at div
    at MainLayout (http://91fea776c5427d6b29213c157a893e5f.localhost:1073/build/Lens.js:286661:9)
    at ErrorBoundary (http://91fea776c5427d6b29213c157a893e5f.localhost:1073/build/Lens.js:238009:9)
    at Router (http://91fea776c5427d6b29213c157a893e5f.localhost:1073/build/Lens.js:79008:30)
    at ClusterFrame (http://91fea776c5427d6b29213c157a893e5f.localhost:1073/build/chunks/5.js:7940:9)
    at ThemeProvider (http://91fea776c5427d6b29213c157a893e5f.localhost:1073/build/Lens.js:609896:24)
```
```
Error stack:

Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Berror%2C%20messages%2C%20isUsedForNotification%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Rg (http://91fea776c5427d6b29213c157a893e5f.localhost:1073/build/Lens.js:556467:47)
    at http://91fea776c5427d6b29213c157a893e5f.localhost:1073/build/Lens.js:556477:265
    at fi (http://91fea776c5427d6b29213c157a893e5f.localhost:1073/build/Lens.js:556503:171)
    at ck (http://91fea776c5427d6b29213c157a893e5f.localhost:1073/build/Lens.js:556598:134)
    at bk (http://91fea776c5427d6b29213c157a893e5f.localhost:1073/build/Lens.js:556577:347)
    at ak (http://91fea776c5427d6b29213c157a893e5f.localhost:1073/build/Lens.js:556577:278)
    at Tj (http://91fea776c5427d6b29213c157a893e5f.localhost:1073/build/Lens.js:556577:138)
    at Lj (http://91fea776c5427d6b29213c157a893e5f.localhost:1073/build/Lens.js:556570:163)
    at http://91fea776c5427d6b29213c157a893e5f.localhost:1073/build/Lens.js:556450:115
    at exports.unstable_runWithPriority (http://91fea776c5427d6b29213c157a893e5f.localhost:1073/build/Lens.js:556661:343)
    at gg (http://91fea776c5427d6b29213c157a893e5f.localhost:1073/build/Lens.js:556449:325)
    at jg (http://91fea776c5427d6b29213c157a893e5f.localhost:1073/build/Lens.js:556450:61)
    at ig (http://91fea776c5427d6b29213c157a893e5f.localhost:1073/build/Lens.js:556449:428)
    at Wj (http://91fea776c5427d6b29213c157a893e5f.localhost:1073/build/Lens.js:556571:190)
    at reactionScheduler (http://91fea776c5427d6b29213c157a893e5f.localhost:1073/build/Lens.js:3776:12)
    at http://91fea776c5427d6b29213c157a893e5f.localhost:1073/build/Lens.js:3777:14
```

**Additional context**
I often have problems with proxy settings. Could this be a cause of that? I have spent a couple of hours trying different proxy settings so I hope this is something else

**Comment by Nokel81** [comment]
If you pull up the devtools is there an error printed to the console?

**Comment by NangiDev** [comment]
> If you pull up the devtools is there an error printed to the console?

It just throws a react.js error
![image](https://user-images.githubusercontent.com/8998287/154685684-fbaef73c-b204-46e5-a84e-f85ec2366f77.png)

**Comment by Nokel81** [comment]
What helm chart repos do you have added?

**Comment by NangiDev** [comment]
> What helm chart repos do you have added?

Only these
bitnami                 https://charts.bitnami.com/bitnami
agones                  https://agones.dev/chart/stable
prometheus-community    https://prometheus-community.github.io/helm-charts
grafana                 https://grafana.github.io/helm-charts

**Comment by Nokel81** [comment]
Thanks that should help narrow down why this crash is happening.

**Comment by aleksfront** [comment]
@NangiDev I've created a PR which show fetch errors correctly #4905 but it won't fully solve your problem. It's obviously that you have some connection/proxy problem and helm details can not be properly downloaded.

There is some workaround for you to quickly look at the exact error you have while opening Helm chart details. Please open devtools and add logpoint to see the actual message.

https://user-images.githubusercontent.com/9607060/154929116-471af6ec-6c3e-4fb3-a16b-9b270f8f7e03.mov

**Comment by NangiDev** [comment]
> @NangiDev I've created a PR which show fetch errors correctly #4905 but it won't fully solve your problem. It's obviously that you have some connection/proxy problem and helm details can not be properly downloaded.
> 
> There is some workaround for you to quickly look at the exact error you have while opening Helm chart details. Please open devtools and add logpoint to see the actual message.
> 
>  chart.fetch.error.workaround.mov

Thanks for the video! I follow your instructions and just got this error message
"Error: failed to download "prometheus-community/prometheus" at version "15.3.0" (hint: running `helm repo update` may help)"

I tried following the hint and I successfully could update the repos from terminal. Also I can still install all packages from the terminal it is just the Lens interface that doesn't work. I am still looking into the proxy issue, but so success so far.

**Comment by NangiDev** [comment]
When going to Settings ->Kubernetes it will fail loading Helm Chars repos
with error 
![image](https://user-images.githubusercontent.com/8998287/154986574-ff1e4cfb-1d0f-4abd-9923-968a3752a348.png)

**Comment by Nokel81** [comment]
@NangiDev If you run lens from the terminal do you still get this issue? If you run lens with `DEBUG=true` then do you see a log line: `[SHELL-SYNC]: Synced shell env, and updating`?

**Comment by NangiDev** [comment]
Don't know why this was closed. I still have the problem.

@Nokel81 
Should I just run like
``` 
Lens.exe DEBUG=true
```

Nothing happens except Lens starts and outputs this
```
info:    Ôû¬ ­ƒôƒ Setting Lens as protocol client for lens:// +0ms
info:    Ôû¬ ­ƒôƒ Protocol client register succeeded Ô£à +1ms
info:    Ôû¬ [APP-PATHS]: initializing +0ms
```

I had some issues with Docker for Windows earlier this week. That got solved by setting NO_PROXY to .docker.internal
Is there any url I should whitelist in proxy you can think of?

**Comment by Nokel81** [comment]
@NangiDev This was closed because the PR that fixes the crash has been merged and is on track to be released as part of 5.4 next week.

As to your other comment:

to set env variables on windows PS you need to do the following:

```
$Env:DEBUG=true Lens.exe
```

>  Is there any url I should whitelist in proxy you can think of?

Yes, `localhost` and `127.0.0.1`

**Comment by NangiDev** [comment]
Okay thanks!

I got more output now and found ```[SHELL-SYNC]: Synced shell env, and updating```
the http_proxy and https_proxy isnt in there.

Adding ```localhost``` and ```127.0.0.1``` didnt help either, but I guess I'll just wait for the new release

Thanks again!

**Comment by Nokel81** [comment]
I would check you `c:\WINDOWS\system32\drivers\etc\hosts` file (I think that is what it is) and see if `localhost` is indeed pointing to `127.0.0.1`

**Comment by NangiDev** [comment]
@Nokel81 
Found the file.
It only contains:
```
# Added by Docker Desktop
<local office IP> host.docker.internal
<local office IP> gateway.docker.internal
# To allow the same kube context to work on the host and the container:
127.0.0.1 kubernetes.docker.internal
# End of section
```

**Comment by Nokel81** [comment]
Is Docker desktop currently running?

**Comment by NangiDev** [comment]
@Nokel81 
Yes it is. I can connect to the cluster.
It is only fetching the helm charts for apps from within the interface that does not work.

**Comment by Nokel81** [comment]
Can you start up a port forward or does that fail too?

**Comment by NangiDev** [comment]
@Nokel81 
Yes that seems to work fine. It is only loading the helm charts in the gui that is the problem
