### ISSUE TITLE
Crash by Parse.parseError

### ISSUE THREAD

**Issue by cforce** [kontena/lens#4999]
Component stack:

    at CrdResourceDetails (http://e1f1df19d99c982b330d4c7a6ba292bb.localhost:59974/build/Lens.js:246735:47)
    at div
    at div
    at div
    at Animate (http://e1f1df19d99c982b330d4c7a6ba292bb.localhost:59974/build/Lens.js:148420:9)
    at drawer_Drawer (http://e1f1df19d99c982b330d4c7a6ba292bb.localhost:59974/build/Lens.js:14197:9)
    at KubeObjectDetails (http://e1f1df19d99c982b330d4c7a6ba292bb.localhost:59974/build/Lens.js:289362:9)
    at ErrorBoundary (http://e1f1df19d99c982b330d4c7a6ba292bb.localhost:59974/build/Lens.js:238009:9)
    at Router (http://e1f1df19d99c982b330d4c7a6ba292bb.localhost:59974/build/Lens.js:79008:30)
    at ClusterFrame (http://e1f1df19d99c982b330d4c7a6ba292bb.localhost:59974/build/chunks/5.js:7940:9)
    at ThemeProvider (http://e1f1df19d99c982b330d4c7a6ba292bb.localhost:59974/build/Lens.js:609896:24)
Error stack:

Error: Parse error on line 1:
...ernal.currentValue..
-----------------------^
Expecting 'STAR', 'IDENTIFIER', 'SCRIPT_EXPRESSION', 'INTEGER', 'END', '[', got '1'
    at Parser.parseError (http://e1f1df19d99c982b330d4c7a6ba292bb.localhost:59974/build/Lens.js:227349:15)
    at Parser.parser.yy.parseError (http://e1f1df19d99c982b330d4c7a6ba292bb.localhost:59974/build/Lens.js:228549:17)
    at Parser.parse (http://e1f1df19d99c982b330d4c7a6ba292bb.localhost:59974/build/Lens.js:227407:22)
    at JSONPath._normalize (http://e1f1df19d99c982b330d4c7a6ba292bb.localhost:59974/build/Lens.js:228483:24)
    at JSONPath.stringify (http://e1f1df19d99c982b330d4c7a6ba292bb.localhost:59974/build/Lens.js:228453:15)
    at JSONPath.value (http://e1f1df19d99c982b330d4c7a6ba292bb.localhost:59974/build/Lens.js:228348:31)
    at http://e1f1df19d99c982b330d4c7a6ba292bb.localhost:59974/build/Lens.js:246737:201
    at Array.map (<anonymous>)
    at CrdResourceDetails.renderAdditionalColumns (http://e1f1df19d99c982b330d4c7a6ba292bb.localhost:59974/build/Lens.js:246737:24)
    at CrdResourceDetails.render (http://e1f1df19d99c982b330d4c7a6ba292bb.localhost:59974/build/Lens.js:246767:18)
    at allowStateChanges (http://e1f1df19d99c982b330d4c7a6ba292bb.localhost:59974/build/Lens.js:2571:12)
    at http://e1f1df19d99c982b330d4c7a6ba292bb.localhost:59974/build/Lens.js:10958:59
    at trackDerivedFunction (http://e1f1df19d99c982b330d4c7a6ba292bb.localhost:59974/build/Lens.js:3120:18)
    at Reaction.track (http://e1f1df19d99c982b330d4c7a6ba292bb.localhost:59974/build/Lens.js:3649:18)
    at CrdResourceDetails.reactiveRender [as render] (http://e1f1df19d99c982b330d4c7a6ba292bb.localhost:59974/build/Lens.js:10956:14)
    at CrdResourceDetails.makeComponentReactive (http://e1f1df19d99c982b330d4c7a6ba292bb.localhost:59974/build/Lens.js:10971:25)

**Comment by Nokel81** [comment]
Would you able to provide the custom resource definition for that resource?
