### ISSUE TITLE
App crash when clicking on a NetworkPolicy

### ISSUE THREAD

**Issue by robinbraemer** [kontena/lens#5013]
**Describe the bug**
- App crash

**To Reproduce**
1. Go to 'Network > Network Policies'
2. Click on a network policy
3. See App crash

**Expected behavior**
Should display the network policy

**Screenshots**
![image](https://user-images.githubusercontent.com/22003767/158411228-6a39e4c2-911a-4f74-89ba-79af94d439a8.png)

This is what I did
![Peek 2022-03-15 16-22](https://user-images.githubusercontent.com/22003767/158411614-75c5df20-950d-46c8-bfaa-aabacaf576e5.gif)

**Environment (please complete the following information):**
- Lens Version: 5.3.3-latest.20211214.2
- OS: [Pop!_OS](https://system76.com/pop) (Ubuntu based)
- Installation method (e.g. snap or AppImage in Linux):

**Logs:**

```
Component stack:


    at NetworkPolicyDetails (http://8a0ca09b41966e044bc821d5ca75b8d9.localhost:33037/build/Lens.js:476092:51)
    at div
    at div
    at div
    at Animate (http://8a0ca09b41966e044bc821d5ca75b8d9.localhost:33037/build/Lens.js:148838:9)
    at drawer_Drawer (http://8a0ca09b41966e044bc821d5ca75b8d9.localhost:33037/build/Lens.js:14247:9)
    at KubeObjectDetails (http://8a0ca09b41966e044bc821d5ca75b8d9.localhost:33037/build/Lens.js:289281:9)
    at ErrorBoundary (http://8a0ca09b41966e044bc821d5ca75b8d9.localhost:33037/build/Lens.js:237976:9)
    at Router (http://8a0ca09b41966e044bc821d5ca75b8d9.localhost:33037/build/Lens.js:79057:30)
    at ClusterFrame (http://8a0ca09b41966e044bc821d5ca75b8d9.localhost:33037/build/chunks/5.js:7941:9)
    at ThemeProvider (http://8a0ca09b41966e044bc821d5ca75b8d9.localhost:33037/build/Lens.js:609784:24)
```

```
Error stack:

TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at NetworkPolicyDetails.renderIPolicySelector (http://8a0ca09b41966e044bc821d5ca75b8d9.localhost:33037/build/Lens.js:476112:14)
    at http://8a0ca09b41966e044bc821d5ca75b8d9.localhost:33037/build/Lens.js:476125:22
    at Array.map (<anonymous>)
    at NetworkPolicyDetails.renderNetworkPolicyPeers (http://8a0ca09b41966e044bc821d5ca75b8d9.localhost:33037/build/Lens.js:476123:19)
    at http://8a0ca09b41966e044bc821d5ca75b8d9.localhost:33037/build/Lens.js:476159:26
    at Array.map (<anonymous>)
    at NetworkPolicyDetails.render (http://8a0ca09b41966e044bc821d5ca75b8d9.localhost:33037/build/Lens.js:476157:25)
    at allowStateChanges (http://8a0ca09b41966e044bc821d5ca75b8d9.localhost:33037/build/Lens.js:2571:12)
    at http://8a0ca09b41966e044bc821d5ca75b8d9.localhost:33037/build/Lens.js:11008:59
    at trackDerivedFunction (http://8a0ca09b41966e044bc821d5ca75b8d9.localhost:33037/build/Lens.js:3120:18)
    at Reaction.track (http://8a0ca09b41966e044bc821d5ca75b8d9.localhost:33037/build/Lens.js:3649:18)
    at NetworkPolicyDetails.reactiveRender [as render] (http://8a0ca09b41966e044bc821d5ca75b8d9.localhost:33037/build/Lens.js:11006:14)
    at NetworkPolicyDetails.makeComponentReactive (http://8a0ca09b41966e044bc821d5ca75b8d9.localhost:33037/build/Lens.js:11021:25)
    at NetworkPolicyDetails.target.render (http://8a0ca09b41966e044bc821d5ca75b8d9.localhost:33037/build/Lens.js:10934:34)
    at qi (http://8a0ca09b41966e044bc821d5ca75b8d9.localhost:33037/build/Lens.js:556402:188)
```

**Kubeconfig:**
Just a kind local cluster

**Network policy I clicked on:**

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: argocd-dex-server-network-policy
  namespace: argocd
  uid: be3a25b1-c5a0-4686-8de2-4a57dd998f46
  resourceVersion: '798'
  generation: 1
  creationTimestamp: '2022-03-15T15:14:30Z'
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"networking.k8s.io/v1","kind":"NetworkPolicy","metadata":{"annotations":{},"name":"argocd-dex-server-network-policy","namespace":"argocd"},"spec":{"ingress":[{"from":[{"podSelector":{"matchLabels":{"app.kubernetes.io/name":"argocd-server"}}}],"ports":[{"port":5556,"protocol":"TCP"},{"port":5557,"protocol":"TCP"}]},{"from":[{"namespaceSelector":{}}],"ports":[{"port":5558,"protocol":"TCP"}]}],"podSelector":{"matchLabels":{"app.kubernetes.io/name":"argocd-dex-server"}},"policyTypes":["Ingress"]}}
  managedFields:
    - manager: kubectl-client-side-apply
      operation: Update
      apiVersion: networking.k8s.io/v1
      time: '2022-03-15T15:14:30Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:spec:
          f:ingress: {}
          f:podSelector: {}
          f:policyTypes: {}
  selfLink: >-
    /apis/networking.k8s.io/v1/namespaces/argocd/networkpolicies/argocd-dex-server-network-policy
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: argocd-dex-server
  ingress:
    - ports:
        - protocol: TCP
          port: 5556
        - protocol: TCP
          port: 5557
      from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: argocd-server
    - ports:
        - protocol: TCP
          port: 5558
      from:
        - namespaceSelector: {}
  policyTypes:
    - Ingress
```

**Comment by Nokel81** [comment]
This was fixed by #4500 please upgrade to the latest version of Lens
