### ISSUE TITLE
Socket hangup on getting metrics

### ISSUE THREAD

**Issue by joshuapare** [kontena/lens#5047]
**Describe the bug**
I have the kube-prometheus operator installed on multiple clusters, and for some of them it's fine, but a recent install in our non-govcloud clusters (ironically) end up having the metrics spin forever, and result in a socket hangup. I've tried letting it auto-configure, setting it to connect to the operator service, connect to the non-operator prometheus service, and nothing seems to work for the recently added clusters. They have the same configuration as far as settings go and have not had issues until today.

**To Reproduce**
1. Open the Lens app with the 
2. Click on anything to show metrics

**Expected behavior**
Metrics either error out immediately to show improper configuration or display metrics

**Actual behavior**
All metrics spin forever. If I wait long enough, they finally come back with metrics errors. Eventually, the logs come back with socket hangups as well.

**Screenshots**
<img width="896" alt="image" src="https://user-images.githubusercontent.com/65102852/159164323-18908479-f8fc-4f88-9cd6-a7102f14bade.png">

**Environment (please complete the following information):**
- Lens Version: 5.4.3-latest.20220317.1
- MacOS
- Installation method (e.g. snap or AppImage in Linux): Mac Installer

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:

Errors on first connection:
```
debug:   ┏ [CLUSTER]: broadcasting connection update Connected, waiting for view to load ... +1ms
debug:   ┃ [ 1] {
debug:   ┃ [ 2]   isError: false,
debug:   ┃ [ 3]   meta: {
debug:   ┃ [ 4]     id: '7d72c0ee469feccc1e73fd2c04dd2fd1',
debug:   ┃ [ 5]     name: 'ops',
debug:   ┃ [ 6]     ready: true,
debug:   ┃ [ 7]     online: true,
debug:   ┃ [ 8]     accessible: true,
debug:   ┃ [ 9]     disconnected: false
debug:   ┃ [10]   }
debug:   ┗ [11] }
debug:   ▪ Acquired a lock for 1.21.9 +7ms
info:    ▪ Creating a new port-forward monitoring/service/prometheus-operated:9090 +296ms
debug:   ▪ Local kubectl is version 1.21.9 +411ms
debug:   ▪ [KUBECTL]: Releasing lock for 1.21.9 +1ms
debug:   ▪ [PORT-FORWARD-ROUTE]: kubectl port-forward process stderr: I0320 09:40:36.495145   35778 log.go:184] (0xc0005fa420) (0xc000afb7c0) Create stream
I0320 09:40:36.495682   35778 log.go:184] (0xc0005fa420) (0xc000afb7c0) Stream added, broadcasting: 1
 +3s
debug:   ▪ [PORT-FORWARD-ROUTE]: kubectl port-forward process stderr: I0320 09:40:36.529373   35778 log.go:184] (0xc0005fa420) Reply frame received for 1
I0320 09:40:36.529396   35778 log.go:184] (0xc000afb7c0) (1) Writing data frame
 +34ms
debug:   ▪ [PORT-FORWARD-ROUTE]: kubectl port-forward process stderr: I0320 09:40:36.529433   35778 log.go:184] (0xc0005fa420) (0xc000ae28c0) Create stream
I0320 09:40:36.529441   35778 log.go:184] (0xc0005fa420) (0xc000ae28c0) Stream added, broadcasting: 3
 +1ms
debug:   ▪ [PORT-FORWARD-ROUTE]: kubectl port-forward process stderr: I0320 09:40:36.564144   35778 log.go:184] (0xc0005fa420) Reply frame received for 3
 +34ms
debug:   ▪ [PORT-FORWARD-ROUTE]: kubectl port-forward process stderr: I0320 09:40:36.564288   35778 log.go:184] (0xc000ae28c0) (3) Writing data frame
 +1ms
debug:   ▪ [PORT-FORWARD-ROUTE]: kubectl port-forward process stderr: I0320 09:40:37.603831   35778 log.go:184] (0xc0005fa420) Data frame received for 1
I0320 09:40:37.603860   35778 log.go:184] (0xc000afb7c0) (1) Data frame handling
I0320 09:40:37.603877   35778 log.go:184] (0xc0005fa420) (0xc000afb7c0) Stream removed, broadcasting: 1
I0320 09:40:37.603896   35778 log.go:184] (0xc0005fa420) Data frame received for 3
I0320 09:40:37.603906   35778 log.go:184] (0xc000ae28c0) (3) Data frame handling
I0320 09:40:37.603937   35778 log.go:184] (0xc0005fa420) (0xc000ae28c0) Stream removed, broadcasting: 3
```

Errors after connecting:
```
debug:   ┏ [CLUSTER]: broadcasting connection update E0320 09:24:56.497045   34601 proxy_server.go:147] Error while proxying request: context canceled

error:   ┏ [Metrics]: metrics not available Error: socket hang up +2ms
error:   ┃ [ 1] RequestError: Error: socket hang up
error:   ┃ [ 2]     at new RequestError (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/errors.js:14:15)
error:   ┃ [ 3]     at Request.plumbing.callback (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:87:29)
error:   ┃ [ 4]     at Request.RP$callback [as _callback] (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:46:31)
error:   ┃ [ 5]     at self.callback (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/request/request.js:185:22)
error:   ┃ [ 6]     at Request.emit (events.js:376:20)
error:   ┃ [ 7]     at Request.emit (domain.js:470:12)
error:   ┃ [ 8]     at Request.onRequestError (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/request/request.js:877:8)
error:   ┃ [ 9]     at ClientRequest.emit (events.js:388:22)
error:   ┃ [10]     at ClientRequest.emit (domain.js:470:12)
error:   ┃ [11]     at Socket.socketOnEnd (_http_client.js:499:9)
error:   ┃ [12] {
error:   ┃ [13]   name: 'RequestError',
error:   ┃ [14]   cause: Error: socket hang up
error:   ┃ [15]       at connResetException (internal/errors.js:611:14)
error:   ┃ [16]       at Socket.socketOnEnd (_http_client.js:499:23)
error:   ┃ [17]       at Socket.emit (events.js:388:22)
error:   ┃ [18]       at Socket.emit (domain.js:470:12)
error:   ┃ [19]       at endReadableNT (internal/streams/readable.js:1336:12)
error:   ┃ [20]       at processTicksAndRejections (internal/process/task_queues.js:82:21) {
error:   ┃ [21]     code: 'ECONNRESET'
error:   ┃ [22]   },
error:   ┃ [23]   error: Error: socket hang up
error:   ┃ [24]       at connResetException (internal/errors.js:611:14)
error:   ┃ [25]       at Socket.socketOnEnd (_http_client.js:499:23)
error:   ┃ [26]       at Socket.emit (events.js:388:22)
error:   ┃ [27]       at Socket.emit (domain.js:470:12)
error:   ┃ [28]       at endReadableNT (internal/streams/readable.js:1336:12)
error:   ┃ [29]       at processTicksAndRejections (internal/process/task_queues.js:82:21) {
error:   ┃ [30]     code: 'ECONNRESET'
error:   ┃ [31]   },
error:   ┃ [32]   options: {
error:   ┃ [33]     timeout: 0,
error:   ┃ [34]     resolveWithFullResponse: false,
error:   ┃ [35]     json: true,
error:   ┃ [36]     method: 'POST',
error:   ┃ [37]     form: {
error:   ┃ [38]       query: 'sum(node_filesystem_size_bytes{mountpoint="/"} * on (pod,namespace) group_left(node) kube_pod_info) by (node)',
error:   ┃ [39]       start: '1647778740',
error:   ┃ [40]       end: '1647782340',
error:   ┃ [41]       step: '60',
error:   ┃ [42]       kubernetes_namespace: ''
error:   ┃ [43]     },
error:   ┃ [44]     headers: { Host: '7d72c0ee469feccc1e73fd2c04dd2fd1.localhost:63648' },
error:   ┃ [45]     uri: 'http://localhost:63648/api-kube/api/v1/namespaces/monitoring/services/monitoring-prometheus:9090/proxy/api/v1/query_range',
error:   ┃ [46]     callback: [Function: RP$callback],
error:   ┃ [47]     transform: undefined,
error:   ┃ [48]     simple: true,
error:   ┃ [49]     transform2xxOnly: false
error:   ┃ [50]   },
error:   ┃ [51]   response: undefined
error:   ┗ [52] }
```

Manually port forwarding the service works fine: 
<img width="1207" alt="image" src="https://user-images.githubusercontent.com/65102852/159166069-53aa1aa8-bf2e-46d7-bd6b-153385051d19.png">
<img width="566" alt="image" src="https://user-images.githubusercontent.com/65102852/159166093-d964763f-fff9-43f2-a911-2b98d2b84801.png">

**Comment by joshuapare** [comment]
I apologize, it seems I forgot something crucial - *nodes need to allow 9090 from the control plane because of how this works*. 

Adding the security group rule fixed the issue. Closing.

Here is the comment that led me to this: https://github.com/lensapp/lens/issues/1731#issuecomment-779196430
