### ISSUE TITLE
Workloads / Overview crash

### ISSUE THREAD

**Issue by haimbell** [kontena/lens#5144]
Whenever I click the Overview menu item I get an error

Running the latest version: 5.4.4-latest.20220325.1

Component stack:

    at r (C:\Users\blhai\.k8slens\extensions\nevalla--kube-resource-map\dist\renderer.js:7:595820)
    at div
    at div
    at Details
    at div
    at NonInjectedWorkloadsOverview (http://4815062c060dcea17359c9da2b4539a5.localhost:56020/build/Lens.js:470702:9)
    at Route (http://4815062c060dcea17359c9da2b4539a5.localhost:56020/build/Lens.js:71627:29)
    at Switch (http://4815062c060dcea17359c9da2b4539a5.localhost:56020/build/Lens.js:71793:29)
    at ErrorBoundary (http://4815062c060dcea17359c9da2b4539a5.localhost:56020/build/Lens.js:228125:9)
    at main
    at div
    at wrappedComponent (http://4815062c060dcea17359c9da2b4539a5.localhost:56020/build/Lens.js:100450:16)
    at wrappedComponent (http://4815062c060dcea17359c9da2b4539a5.localhost:56020/build/Lens.js:100450:16)
    at Route (http://4815062c060dcea17359c9da2b4539a5.localhost:56020/build/Lens.js:71627:29)
    at Switch (http://4815062c060dcea17359c9da2b4539a5.localhost:56020/build/Lens.js:71793:29)
    at ErrorBoundary (http://4815062c060dcea17359c9da2b4539a5.localhost:56020/build/Lens.js:228125:9)
    at div
    at div
    at NonInjectedMainLayout (http://4815062c060dcea17359c9da2b4539a5.localhost:56020/build/Lens.js:296237:9)
    at ErrorBoundary (http://4815062c060dcea17359c9da2b4539a5.localhost:56020/build/Lens.js:228125:9)
    at Router (http://4815062c060dcea17359c9da2b4539a5.localhost:56020/build/Lens.js:71292:30)
    at NonInjectedClusterFrame (http://4815062c060dcea17359c9da2b4539a5.localhost:56020/build/chunks/4.js:4220:9)
    at ThemeProvider (http://4815062c060dcea17359c9da2b4539a5.localhost:56020/build/Lens.js:592495:24)

Error stack:

TypeError: Cannot read properties of undefined (reading 'clientWidth')
    at render (C:\Users\blhai\.k8slens\extensions\nevalla--kube-resource-map\dist\renderer.js:7:608021)
    at allowStateChanges (http://4815062c060dcea17359c9da2b4539a5.localhost:56020/build/Lens.js:1535:12)
    at http://4815062c060dcea17359c9da2b4539a5.localhost:56020/build/Lens.js:9915:84
    at trackDerivedFunction (http://4815062c060dcea17359c9da2b4539a5.localhost:56020/build/Lens.js:2084:18)
    at Reaction.track (http://4815062c060dcea17359c9da2b4539a5.localhost:56020/build/Lens.js:2613:18)
    at reactiveRender [as render] (http://4815062c060dcea17359c9da2b4539a5.localhost:56020/build/Lens.js:9913:14)
    at qi (http://4815062c060dcea17359c9da2b4539a5.localhost:56020/build/Lens.js:540445:188)
    at pi (http://4815062c060dcea17359c9da2b4539a5.localhost:56020/build/Lens.js:540444:173)
    at ck (http://4815062c060dcea17359c9da2b4539a5.localhost:56020/build/Lens.js:540527:427)
    at bk (http://4815062c060dcea17359c9da2b4539a5.localhost:56020/build/Lens.js:540508:347)

![image](https://user-images.githubusercontent.com/54363796/160838445-0029e217-ec55-4795-9774-055e5462a51d.png)

**Comment by Nokel81** [comment]
Please search for previous issues next time. This has been reported many times before and is not a bug with Lens but with the kube-resource-map extension. Please upgrade that.
