### ISSUE TITLE
App crash at ClusterStatus

### ISSUE THREAD

**Issue by aleksfront** [kontena/lens#5238]
As reported from the community:

App crash at /cluster/5d0e86ac3c1d30f483817124a0e5d134
Version 5.4.5-latest.20220405.1

```
ClusterStatus (http://localhost:63386/build/chunks/5.js:2817:9)
    at div
    at ClusterView (http://localhost:63386/build/chunks/5.js:3085:9)
    at Route (http://localhost:63386/build/Lens.js:71644:29)
    at Switch (http://localhost:63386/build/Lens.js:71810:29)
    at main
    at div
    at NonInjectedClusterManager (http://localhost:63386/build/chunks/5.js:4294:49)
    at Route (http://localhost:63386/build/Lens.js:71644:29)
    at Switch (http://localhost:63386/build/Lens.js:71810:29)
    at ErrorBoundary (http://localhost:63386/build/Lens.js:228144:9)
    at Router (http://localhost:63386/build/Lens.js:71309:30)
    at NonInjectedRootFrame (http://localhost:63386/build/chunks/5.js:4382:9)
    at ThemeProvider (http://localhost:63386/build/Lens.js:592515:24)
Error stack:
TypeError: message.trim is not a function
    at http://localhost:63386/build/chunks/5.js:2889:248
    at http://localhost:63386/build/Lens.js:4208:23
    at Array.map (<anonymous>)
    at Proxy.<anonymous> (http://localhost:63386/build/Lens.js:4207:36)
    at ClusterStatus.renderAuthenticationOutput (http://localhost:63386/build/chunks/5.js:2889:76)
    at ClusterStatus.render (http://localhost:63386/build/chunks/5.js:2916:22)
    at allowStateChanges (http://localhost:63386/build/Lens.js:1535:12)
    at http://localhost:63386/build/Lens.js:9915:84
    at trackDerivedFunction (http://localhost:63386/build/Lens.js:2084:18)
    at Reaction.track (http://localhost:63386/build/Lens.js:2613:18)
    at ClusterStatus.reactiveRender [as render] (http://localhost:63386/build/Lens.js:9913:14)
    at qi (http://localhost:63386/build/Lens.js:540465:188)
    at pi (http://localhost:63386/build/Lens.js:540464:173)
    at ck (http://localhost:63386/build/Lens.js:540547:427)
    at bk (http://localhost:63386/build/Lens.js:540528:347)
    at ak (http://localhost:63386/build/Lens.js:540528:278)
    at Tj (http://localhost:63386/build/Lens.js:540528:138)
    at Lj (http://localhost:63386/build/Lens.js:540521:163)
    at http://localhost:63386/build/Lens.js:540401:115
    at exports.unstable_runWithPriority (http://localhost:63386/build/Lens.js:540612:343)
    at gg (http://localhost:63386/build/Lens.js:540400:325)
    at jg (http://localhost:63386/build/Lens.js:540401:61)
    at ig (http://localhost:63386/build/Lens.js:540400:428)
    at Wj (http://localhost:63386/build/Lens.js:540522:190)
    at reactionScheduler (http://localhost:63386/build/Lens.js:2740:12)
    at http://localhost:63386/build/Lens.js:2741:14
    at Bh (C:\Program Files\Lens\resources\extensions\lenscloud-lens-extension\dist\renderer.js:115:141185)
    at reactionScheduler (http://localhost:63386/build/Lens.js:2740:12)
    at runReactions (http://localhost:63386/build/Lens.js:2709:3)
    at endBatch (http://localhost:63386/build/Lens.js:2377:5)
    at Atom.reportChanged (http://localhost:63386/build/Lens.js:823:5)
    at ObservableArrayAdministration.notifyArraySplice_ (http://localhost:63386/build/Lens.js:3977:16)
    at ObservableArrayAdministration.spliceWithArray_ (http://localhost:63386/build/Lens.js:3916:58)
    at Proxy.push (http://localhost:63386/build/Lens.js:4102:9)
    at EventEmitter.<anonymous> (http://localhost:63386/build/chunks/5.js:2878:33)
    at EventEmitter.emit (events.js:376:20)
    at Object.onMessage (electron/js2c/renderer_init.js:81:1017)
```

**Comment by vkannemacher** [comment]
Hello, I had the same issue because I was not using user impersonation correctly.
I am using Teleport to access my cluster and multiple Kubernetes users linked to my Teleport user.
After setting only one user and loging again, the bug disappeared.
It would be nice to add a feature to Lens (or maybe i didn't see it) to allow user impersonation, in the same way it can be used with the `--as` option.
