### ISSUE TITLE
Crash accessing cluster with "message.trim is not a function" error (v5.4.6-latest.20220428.1)

### ISSUE THREAD

**Issue by alanbchristie** [kontena/lens#5323]
**Describe the bug**
Crashes accessing a cluster with the error `TypeError: message.trim is not a function`

Component stack: -

```
Component stack:


    at ClusterStatus (http://localhost:53528/build/chunks/5.js:2817:9)
    at div
    at ClusterView (http://localhost:53528/build/chunks/5.js:3085:9)
    at Route (http://localhost:53528/build/Lens.js:71492:29)
    at Switch (http://localhost:53528/build/Lens.js:71658:29)
    at main
    at div
    at NonInjectedClusterManager (http://localhost:53528/build/chunks/5.js:4294:49)
    at Route (http://localhost:53528/build/Lens.js:71492:29)
    at Switch (http://localhost:53528/build/Lens.js:71658:29)
    at ErrorBoundary (http://localhost:53528/build/Lens.js:228295:9)
    at Router (http://localhost:53528/build/Lens.js:71157:30)
    at NonInjectedRootFrame (http://localhost:53528/build/chunks/5.js:4382:9)
    at ThemeProvider (http://localhost:53528/build/Lens.js:592771:24)
```

Error stack: -

```
Error stack:

TypeError: message.trim is not a function
    at http://localhost:53528/build/chunks/5.js:2889:248
    at http://localhost:53528/build/Lens.js:4208:23
    at Array.map (<anonymous>)
    at Proxy.<anonymous> (http://localhost:53528/build/Lens.js:4207:36)
    at ClusterStatus.renderAuthenticationOutput (http://localhost:53528/build/chunks/5.js:2889:76)
    at ClusterStatus.render (http://localhost:53528/build/chunks/5.js:2916:22)
    at allowStateChanges (http://localhost:53528/build/Lens.js:1535:12)
    at http://localhost:53528/build/Lens.js:9915:84
    at trackDerivedFunction (http://localhost:53528/build/Lens.js:2084:18)
    at Reaction.track (http://localhost:53528/build/Lens.js:2613:18)
    at ClusterStatus.reactiveRender [as render] (http://localhost:53528/build/Lens.js:9913:14)
    at qi (http://localhost:53528/build/Lens.js:540718:188)
    at pi (http://localhost:53528/build/Lens.js:540717:173)
    at ck (http://localhost:53528/build/Lens.js:540800:427)
    at bk (http://localhost:53528/build/Lens.js:540781:347)
    at ak (http://localhost:53528/build/Lens.js:540781:278)
    at Tj (http://localhost:53528/build/Lens.js:540781:138)
    at Lj (http://localhost:53528/build/Lens.js:540774:163)
    at http://localhost:53528/build/Lens.js:540654:115
    at exports.unstable_runWithPriority (http://localhost:53528/build/Lens.js:540865:343)
    at gg (http://localhost:53528/build/Lens.js:540653:325)
    at jg (http://localhost:53528/build/Lens.js:540654:61)
    at ig (http://localhost:53528/build/Lens.js:540653:428)
    at Wj (http://localhost:53528/build/Lens.js:540775:190)
    at reactionScheduler (http://localhost:53528/build/Lens.js:2740:12)
    at http://localhost:53528/build/Lens.js:2741:14
    at _h (/Applications/Lens.app/Contents/Resources/extensions/lenscloud-lens-extension/dist/renderer.js:103:141185)
    at reactionScheduler (http://localhost:53528/build/Lens.js:2740:12)
    at runReactions (http://localhost:53528/build/Lens.js:2709:3)
    at endBatch (http://localhost:53528/build/Lens.js:2377:5)
    at Atom.reportChanged (http://localhost:53528/build/Lens.js:823:5)
    at ObservableArrayAdministration.notifyArraySplice_ (http://localhost:53528/build/Lens.js:3977:16)
    at ObservableArrayAdministration.spliceWithArray_ (http://localhost:53528/build/Lens.js:3916:58)
    at Proxy.push (http://localhost:53528/build/Lens.js:4102:9)
    at EventEmitter.<anonymous> (http://localhost:53528/build/chunks/5.js:2878:33)
    at EventEmitter.emit (events.js:376:20)
    at Object.onMessage (electron/js2c/renderer_init.js:81:1017)
```

**To Reproduce**
1. Maybe specific to my cluster but earlier lens versions fail to connect, this one crahses

**Expected behavior**
Not to crash, whatever the problem.

**Screenshots**
<img width="1810" alt="Screenshot 2022-05-04 at 10 59 30" src="https://user-images.githubusercontent.com/29806285/166661548-f67e359d-1cc5-4d01-8550-15463a96a542.png">

**Environment (please complete the following information):**
- Lens Version: `5.4.6-latest.20220428.1`
- OS: `macOS 11.6.5 (Intel/amd64)`
- Installation method (e.g. snap or AppImage in Linux): `Direct Download`

**Logs:**
Not provided

**Kubeconfig:**
Cannot provide config, it's a confidential cluster.

**Additional context**
If it's helpful [k9s] has no trouble accessing and navigating the cluster using the same KUBECONFIG.

[k9s]: https://k9scli.io

**Comment by Nokel81** [comment]
Duplicate of #5238
