### ISSUE TITLE
5.5.beta crashes on startup

### ISSUE THREAD

**Issue by jweak** [kontena/lens#5336]
**Describe the bug**
Updated the app to Version 5.5.0-beta.0.20220505.1 (5.5.0-beta.0.20220505.1.20220505.1) and it crashes on startup.

**To Reproduce**
1. Update app
2. Open the app
3. See error 

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
<img width="270" alt="Screenshot 2022-05-05 at 17 39 21" src="https://user-images.githubusercontent.com/774344/166949491-44ef882f-45b6-42e0-ad4c-7d71f69420a9.png">

- Lens Version: 5.5.0-beta.0.20220505.1
- OS: macOS 11.5.2 M1 arm

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Uncaught Exception:
Error: 
Something went wrong installing the "sharp" module

dlopen(/Applications/Lens.app/Contents/Resources/app.asar.unpacked/node_modules/sharp/build/Release/sharp-darwin-arm64v8.node, 1): Library not loaded: @rpath/libvips-cpp.42.dylib
Referenced from: /Applications/Lens.app/Contents/Resources/app.asar.unpacked/node_modules/sharp/build/Release/sharp-darwin-arm64v8.node
Reason: image not found

Possible solutions:
- Install with the --verbose flag and look for errors: "npm install --ignore-scripts=false --verbose sharp"
- Install for the current darwin-arm64v8 runtime: "npm install --platform=darwin --arch=arm64v8 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
at Object.<anonymous> (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/sharp/lib/sharp.js:31:9)
at Module._compile (internal/modules/cjs/loader.js:1083:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1113:10)
at Module.load (internal/modules/cjs/loader.js:940:32)
at Module._load (internal/modules/cjs/loader.js:781:14)
at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
at Module.require (internal/modules/cjs/loader.js:964:19)
at require (internal/modules/cjs/helpers.js:88:18)
at Object.<anonymous> (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/sharp/lib/constructor.js:8:1)
at Module._compile (internal/modules/cjs/loader.js:1083:30)
```

**Comment by shawlz** [comment]
Crash experienced on Lens: 5.5.0-beta.0.20220505.1
Electron: 14.2.9
Chrome: 93.0.4577.82
Node: 14.17.0
macOS Monterey version 12.3

![image](https://user-images.githubusercontent.com/222459/167138212-2e8077e8-dc67-4e2a-8f62-8d2d3df8328a.png)

Component stack:
```
    at t (/Applications/Lens.app/Contents/Resources/extensions/lenscloud-lens-extension/dist/renderer.js:1438:42338)
    at /Applications/Lens.app/Contents/Resources/extensions/lenscloud-lens-extension/dist/renderer.js:21:268323
    at /Applications/Lens.app/Contents/Resources/extensions/lenscloud-lens-extension/dist/renderer.js:158:135171
    at /Applications/Lens.app/Contents/Resources/extensions/lenscloud-lens-extension/dist/renderer.js:1:4556
    at div
    at /Applications/Lens.app/Contents/Resources/extensions/lenscloud-lens-extension/dist/renderer.js:158:125007
    at /Applications/Lens.app/Contents/Resources/extensions/lenscloud-lens-extension/dist/renderer.js:158:131412
    at /Applications/Lens.app/Contents/Resources/extensions/lenscloud-lens-extension/dist/renderer.js:158:137442
    at /Applications/Lens.app/Contents/Resources/extensions/lenscloud-lens-extension/dist/renderer.js:1:4556
    at c (/Applications/Lens.app/Contents/Resources/extensions/lenscloud-lens-extension/dist/renderer.js:158:101984)
    at c (/Applications/Lens.app/Contents/Resources/extensions/lenscloud-lens-extension/dist/renderer.js:158:101984)
    at div
    at div
    at observerComponent (http://localhost:64654/build/Lens.js?8829547ca093ab2291af:266273:16)
    at div
    at NonInjectedClusterManager (http://localhost:64654/build/chunks/8185.js:1216:33)
    at ErrorBoundary (http://localhost:64654/build/Lens.js?8829547ca093ab2291af:582029:9)
    at RootFrame (http://localhost:64654/build/chunks/8185.js:1300:9)
    at ThemeProvider (http://localhost:64654/build/Lens.js?8829547ca093ab2291af:127160:24)
    at Router (http://localhost:64654/build/Lens.js?8829547ca093ab2291af:454723:30)
```

Error stack:
```
TypeError: Cannot set properties of undefined (setting 'getCurrentStack')
    at je (/Applications/Lens.app/Contents/Resources/extensions/lenscloud-lens-extension/dist/renderer.js:90:11579)
    at /Applications/Lens.app/Contents/Resources/extensions/lenscloud-lens-extension/dist/renderer.js:103:174485
    at Object.t.findDOMNode (/Applications/Lens.app/Contents/Resources/extensions/lenscloud-lens-extension/dist/renderer.js:103:174511)
    at t.n.performEnter (/Applications/Lens.app/Contents/Resources/extensions/lenscloud-lens-extension/dist/renderer.js:1438:43615)
    at t.n.updateStatus (/Applications/Lens.app/Contents/Resources/extensions/lenscloud-lens-extension/dist/renderer.js:1438:43358)
    at t.n.componentDidMount (/Applications/Lens.app/Contents/Resources/extensions/lenscloud-lens-extension/dist/renderer.js:1438:42761)
    at ak (http://localhost:64654/build/Lens.js?8829547ca093ab2291af:453298:219)
    at Yj (http://localhost:64654/build/Lens.js?8829547ca093ab2291af:453297:450)
    at Xj (http://localhost:64654/build/Lens.js?8829547ca093ab2291af:453296:148)
    at Mk (http://localhost:64654/build/Lens.js?8829547ca093ab2291af:453320:81)
    at Fk (http://localhost:64654/build/Lens.js?8829547ca093ab2291af:453318:396)
    at uk (http://localhost:64654/build/Lens.js?8829547ca093ab2291af:453310:439)
    at dg (http://localhost:64654/build/Lens.js?8829547ca093ab2291af:453165:105)
    at Mk (http://localhost:64654/build/Lens.js?8829547ca093ab2291af:453320:404)
    at Fk (http://localhost:64654/build/Lens.js?8829547ca093ab2291af:453318:396)
    at wk (http://localhost:64654/build/Lens.js?8829547ca093ab2291af:453308:253)
    at J (http://localhost:64654/build/Lens.js?8829547ca093ab2291af:467258:203)
    at Immediate.R [as _onImmediate] (http://localhost:64654/build/Lens.js?8829547ca093ab2291af:467259:128)
    at processImmediate (internal/timers.js:462:21)
```

**Comment by chenhunghan** [comment]
> Crash experienced on Lens: 5.5.0-beta.0.20220505.1 Electron: 14.2.9 Chrome: 93.0.4577.82 Node: 14.17.0 macOS Monterey version 12.3
> 
> ![image](https://user-images.githubusercontent.com/222459/167138212-2e8077e8-dc67-4e2a-8f62-8d2d3df8328a.png)
> 
> Component stack:
> 
> ```
>     at t (/Applications/Lens.app/Contents/Resources/extensions/lenscloud-lens-extension/dist/renderer.js:1438:42338)
>     at /Applications/Lens.app/Contents/Resources/extensions/lenscloud-lens-extension/dist/renderer.js:21:268323
>     at /Applications/Lens.app/Contents/Resources/extensions/lenscloud-lens-extension/dist/renderer.js:158:135171
>     at /Applications/Lens.app/Contents/Resources/extensions/lenscloud-lens-extension/dist/renderer.js:1:4556
>     at div
>     at /Applications/Lens.app/Contents/Resources/extensions/lenscloud-lens-extension/dist/renderer.js:158:125007
>     at /Applications/Lens.app/Contents/Resources/extensions/lenscloud-lens-extension/dist/renderer.js:158:131412
>     at /Applications/Lens.app/Contents/Resources/extensions/lenscloud-lens-extension/dist/renderer.js:158:137442
>     at /Applications/Lens.app/Contents/Resources/extensions/lenscloud-lens-extension/dist/renderer.js:1:4556
>     at c (/Applications/Lens.app/Contents/Resources/extensions/lenscloud-lens-extension/dist/renderer.js:158:101984)
>     at c (/Applications/Lens.app/Contents/Resources/extensions/lenscloud-lens-extension/dist/renderer.js:158:101984)
>     at div
>     at div
>     at observerComponent (http://localhost:64654/build/Lens.js?8829547ca093ab2291af:266273:16)
>     at div
>     at NonInjectedClusterManager (http://localhost:64654/build/chunks/8185.js:1216:33)
>     at ErrorBoundary (http://localhost:64654/build/Lens.js?8829547ca093ab2291af:582029:9)
>     at RootFrame (http://localhost:64654/build/chunks/8185.js:1300:9)
>     at ThemeProvider (http://localhost:64654/build/Lens.js?8829547ca093ab2291af:127160:24)
>     at Router (http://localhost:64654/build/Lens.js?8829547ca093ab2291af:454723:30)
> ```
> 
> Error stack:
> 
> ```
> TypeError: Cannot set properties of undefined (setting 'getCurrentStack')
>     at je (/Applications/Lens.app/Contents/Resources/extensions/lenscloud-lens-extension/dist/renderer.js:90:11579)
>     at /Applications/Lens.app/Contents/Resources/extensions/lenscloud-lens-extension/dist/renderer.js:103:174485
>     at Object.t.findDOMNode (/Applications/Lens.app/Contents/Resources/extensions/lenscloud-lens-extension/dist/renderer.js:103:174511)
>     at t.n.performEnter (/Applications/Lens.app/Contents/Resources/extensions/lenscloud-lens-extension/dist/renderer.js:1438:43615)
>     at t.n.updateStatus (/Applications/Lens.app/Contents/Resources/extensions/lenscloud-lens-extension/dist/renderer.js:1438:43358)
>     at t.n.componentDidMount (/Applications/Lens.app/Contents/Resources/extensions/lenscloud-lens-extension/dist/renderer.js:1438:42761)
>     at ak (http://localhost:64654/build/Lens.js?8829547ca093ab2291af:453298:219)
>     at Yj (http://localhost:64654/build/Lens.js?8829547ca093ab2291af:453297:450)
>     at Xj (http://localhost:64654/build/Lens.js?8829547ca093ab2291af:453296:148)
>     at Mk (http://localhost:64654/build/Lens.js?8829547ca093ab2291af:453320:81)
>     at Fk (http://localhost:64654/build/Lens.js?8829547ca093ab2291af:453318:396)
>     at uk (http://localhost:64654/build/Lens.js?8829547ca093ab2291af:453310:439)
>     at dg (http://localhost:64654/build/Lens.js?8829547ca093ab2291af:453165:105)
>     at Mk (http://localhost:64654/build/Lens.js?8829547ca093ab2291af:453320:404)
>     at Fk (http://localhost:64654/build/Lens.js?8829547ca093ab2291af:453318:396)
>     at wk (http://localhost:64654/build/Lens.js?8829547ca093ab2291af:453308:253)
>     at J (http://localhost:64654/build/Lens.js?8829547ca093ab2291af:467258:203)
>     at Immediate.R [as _onImmediate] (http://localhost:64654/build/Lens.js?8829547ca093ab2291af:467259:128)
>     at processImmediate (internal/timers.js:462:21)
> ```

Thanks for reporting. This will be fixed in next beta.
