### ISSUE TITLE
Cannot build 5.5.0 or higher

### ISSUE THREAD

**Issue by ogarcia** [kontena/lens#5458]
**Describe the bug**
Cannot build version 5.5.0. It fails with an error that I do not know how to interpret (I'm not node developer).

**To Reproduce**
1. Download source code
2. Build
3. See error

**Environment (please complete the following information):**
- Lens Version: 5.5.0
- OS: Arch Linux
- Installation method (e.g. snap or AppImage in Linux): n/a

**Logs:**
Build log (the failure part)
```
$ env NODE_ENV=production concurrently yarn:compile:*
[compile:*main] $ yarn run webpack --config webpack/main.ts
[compile:*renderer] $ yarn run webpack --config webpack/renderer.ts
[compile:*extension-types] $ yarn run webpack --config webpack/extensions.ts
[compile:*main] $ /build/lens/src/lens-5.5.0/node_modules/.bin/webpack --config webpack/main.ts
[compile:*renderer] $ /build/lens/src/lens-5.5.0/node_modules/.bin/webpack --config webpack/renderer.ts
[compile:*extension-types] $ /build/lens/src/lens-5.5.0/node_modules/.bin/webpack --config webpack/extensions.ts
[compile:*renderer] WEBPACK:renderer {
[compile:*renderer]   assetsFolderName: 'assets',
[compile:*renderer]   isDevelopment: false,
[compile:*renderer]   rendererDir: '/build/lens/src/lens-5.5.0/src/renderer',
[compile:*renderer]   buildDir: '/build/lens/src/lens-5.5.0/static/build',
[compile:*renderer]   appName: 'OpenLens',
[compile:*renderer]   htmlTemplate: '/build/lens/src/lens-5.5.0/src/renderer/template.html',
[compile:*renderer]   publicPath: '/build/'
[compile:*renderer] }
[compile:*main] WEBPACK:main {
[compile:*main]   isDevelopment: false,
[compile:*main]   mainDir: '/build/lens/src/lens-5.5.0/src/main',
[compile:*main]   buildDir: '/build/lens/src/lens-5.5.0/static/build'
[compile:*main] }
[compile:*main] asset main.js 417 KiB [emitted] [minimized] (name: main) 1 related asset
[compile:*main] orphan modules 419 KiB [orphan] 224 modules
[compile:*main] runtime modules 937 bytes 4 modules
[compile:*main] modules by path ../ 983 KiB
[compile:*main]   modules by path ../src/common/ 457 KiB 223 modules
[compile:*main]   modules by path ../src/main/ 403 KiB 90 modules
[compile:*main]   modules by path ../src/extensions/ 80.8 KiB 23 modules
[compile:*main]   modules by path ../src/renderer/ 30.2 KiB 5 modules
[compile:*main]   modules by path ../src/migrations/ 1.09 KiB 2 modules
[compile:*main]   + 1 module
[compile:*main] modules by path external "lodash/ 168 bytes
[compile:*main]   external "lodash/orderBy" 42 bytes [built] [code generated]
[compile:*main]   external "lodash/isEqual" 42 bytes [built] [code generated]
[compile:*main]   external "lodash/fp" 42 bytes [built] [code generated]
[compile:*main]   external "lodash/get" 42 bytes [built] [code generated]
[compile:*main] + 35 modules
[compile:*main] lens-app-main (webpack 5.72.0) compiled successfully in 85520 ms
[compile:*main] yarn run compile:main exited with code 0
[compile:*renderer] assets by path chunks/*.js 4.82 MiB
[compile:*renderer]   assets by chunk 4.05 MiB (id hint: vendors) 14 assets
[compile:*renderer]   + 71 assets
[compile:*renderer] assets by path assets/ 1.74 MiB 27 assets
[compile:*renderer] assets by path *.js 26.3 MiB
[compile:*renderer]   asset OpenLens.js 25.2 MiB [emitted] (name: OpenLens) 1 related asset
[compile:*renderer]   + 2 assets
[compile:*renderer] assets by path *.css 231 KiB
[compile:*renderer]   asset OpenLens.css 207 KiB [emitted] (name: OpenLens)
[compile:*renderer]   asset 888.css 13.9 KiB [emitted]
[compile:*renderer]   asset 8185.css 10.3 KiB [emitted]
[compile:*renderer] assets by path *.node 206 KiB
[compile:*renderer]   asset 757dd2dc5031e2651296c33d39faa131.node 115 KiB [emitted] (auxiliary id hint: vendors)
[compile:*renderer]   asset 935e5cd0f470d7d3b7db3968a941c7bd.node 90.5 KiB [emitted] (auxiliary id hint: vendors)
[compile:*renderer] asset OpenLens.html 363 bytes [emitted]
[compile:*renderer] Entrypoint OpenLens 25.4 MiB (28.8 MiB) = OpenLens.css 207 KiB OpenLens.js 25.2 MiB 1 auxiliary asset
[compile:*renderer] orphan modules 9.49 MiB (javascript) 1.74 MiB (asset) 257 KiB (runtime) [orphan] 3542 modules
[compile:*renderer] runtime modules 9.95 KiB 15 modules
[compile:*renderer] modules by path ./ 28.5 MiB (javascript) 229 KiB (css/mini-extract)
[compile:*renderer]   modules by path ./node_modules/ 25.1 MiB (javascript) 78.3 KiB (css/mini-extract)
[compile:*renderer]     javascript modules 24.7 MiB 2555 modules
[compile:*renderer]     css modules 78.3 KiB 69 modules
[compile:*renderer]     json modules 463 KiB 30 modules
[compile:*renderer]   modules by path ./src/ 3.4 MiB (javascript) 151 KiB (css/mini-extract)
[compile:*renderer]     javascript modules 3.33 MiB 757 modules
[compile:*renderer]     css modules 151 KiB 212 modules
[compile:*renderer]     asset modules 72.2 KiB 22 modules
[compile:*renderer]     ./src/renderer/components/monaco-editor/monaco-themes/clouds-midnight.json 1.83 KiB [built] [code generated]
[compile:*renderer]   ./package.json 10.7 KiB [built] [code generated]
[compile:*renderer] + 26 modules
[compile:*renderer] 
[compile:*renderer] WARNING in ./node_modules/chokidar/lib/fsevents-handler.js 9:13-32
[compile:*renderer] Module not found: Error: Can't resolve 'fsevents' in '/build/lens/src/lens-5.5.0/node_modules/chokidar/lib'
[compile:*renderer]  @ ./node_modules/chokidar/index.js 15:24-57
[compile:*renderer]  @ ./src/extensions/extension-discovery/extension-discovery.ts 14:0-33 209:8-13
[compile:*renderer]  @ ./src/extensions/extension-discovery/extension-discovery.injectable.ts 6:0-59 17:29-47
[compile:*renderer]  @ ./src/renderer/bootstrap.tsx 27:0-108 92:41-69
[compile:*renderer] 
[compile:*renderer] 1 warning has detailed information that is not shown.
[compile:*renderer] Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.
[compile:*renderer] 
[compile:*renderer] lens-app-renderer (webpack 5.72.0) compiled with 1 warning in 129049 ms
[compile:*renderer] yarn run compile:renderer exited with code 0
[compile:*extension-types] WARNING in ./node_modules/chokidar/lib/fsevents-handler.js 9:13-32
[compile:*extension-types] Module not found: Error: Can't resolve 'fsevents' in '/build/lens/src/lens-5.5.0/node_modules/chokidar/lib'
[compile:*extension-types] 
[compile:*extension-types] webpack compiled with 1 warning
[compile:*extension-types] yarn run compile:extension-types exited with code 0
  • electron-builder  version=23.0.3 os=5.17.9-arch1-1
  • loaded configuration  file=package.json ("build" field)
  • rebuilding native dependencies  dependencies=node-pty@0.10.1 platform=linux arch=x64
  • rebuilding native dependency  name=node-pty version=0.10.1
  ⨯ cannot execute  cause=exit status 1
                    out=$ node scripts/install.js
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

                    errorOut=/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
    /bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
    sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
    /bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
    gyp info it worked if it ends with ok
    gyp info using node-gyp@9.0.0
    gyp info using node@14.19.3 | linux | x64
    gyp info find Python using Python version 3.10.4 found at "/usr/bin/python3"
    gyp http GET https://atom.io/download/electron/v14.2.4/node-v14.2.4-headers.tar.gz
    gyp http 200 https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v14.2.4/node-v14.2.4-headers.tar.gz
    gyp http GET https://atom.io/download/electron/v14.2.4/SHASUMS256.txt
    gyp http 200 https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v14.2.4/SHASUMS256.txt
    gyp info spawn /usr/bin/python3
    gyp info spawn args [
    gyp info spawn args   '/usr/lib/node_modules/node-gyp/gyp/gyp_main.py',
    gyp info spawn args   'binding.gyp',
    gyp info spawn args   '-f',
    gyp info spawn args   'make',
    gyp info spawn args   '-I',
    gyp info spawn args   '/build/lens/src/lens-5.5.0/node_modules/node-pty/build/config.gypi',
    gyp info spawn args   '-I',
    gyp info spawn args   '/usr/lib/node_modules/node-gyp/addon.gypi',
    gyp info spawn args   '-I',
    gyp info spawn args   '/build/.electron-gyp/14.2.4/include/node/common.gypi',
    gyp info spawn args   '-Dlibrary=shared_library',
    gyp info spawn args   '-Dvisibility=default',
    gyp info spawn args   '-Dnode_root_dir=/build/.electron-gyp/14.2.4',
    gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/node-gyp',
    gyp info spawn args   '-Dnode_lib_file=/build/.electron-gyp/14.2.4/<(target_arch)/node.lib',
    gyp info spawn args   '-Dmodule_root_dir=/build/lens/src/lens-5.5.0/node_modules/node-pty',
    gyp info spawn args   '-Dnode_engine=v8',
    gyp info spawn args   '--depth=.',
    gyp info spawn args   '--no-parallel',
    gyp info spawn args   '--generator-output',
    gyp info spawn args   'build',
    gyp info spawn args   '-Goutput_dir=.'
    gyp info spawn args ]
    /bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
    /bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
    gyp: Call to 'node -e "require('nan')"' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
    gyp ERR! configure error 
    gyp ERR! stack Error: `gyp` failed with exit code: 1
    gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/node-gyp/lib/configure.js:261:16)
    gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)
    gyp ERR! System Linux 5.17.9-arch1-1
    gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /build/lens/src/lens-5.5.0/node_modules/node-pty
    gyp ERR! node -v v14.19.3
    gyp ERR! node-gyp -v v9.0.0
    gyp ERR! not ok 
    error Command failed with exit code 1.
    
                    command=/usr/bin/node /usr/lib/node_modules/yarn/bin/yarn.js run install
                    workingDir=/build/lens/src/lens-5.5.0/node_modules/node-pty
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Additional context**
This is important to update the [AUR Arch Linux package](https://aur.archlinux.org/packages/lens).

**Comment by ogarcia** [comment]
Same error with 5.5.1

**Comment by jakolehm** [comment]
@ogarcia based on the logs it seems that `node-gyp` (or python3) is not working correctly. Could you check that nodejs/node-gyp dev/build environment works?

**Comment by ogarcia** [comment]
After doing a lot of checks, what I see is that the error occurs when using a clean chroot to build the package (in Arch Linux we use `extra-x86_64-build`). If the build is done directly the system does not fail. I don't understand this error, because the content inside and outside the chroot is exactly the same.

In any case this problem is unique to Arch Linux, so I close this issue. Sorry for the inconvenience.

**Comment by ogarcia** [comment]
Finally the mistery is solved. The chroot configures locales to `en_US-UTF-8` so you need change it to C whith `export LANG=C LC_ALL=''` before run `make`.
