### ISSUE TITLE
App crash at /cluster/34766fbfe411dbfc5cd6028301b92a06

### ISSUE THREAD

**Issue by vovtz** [kontena/lens#5500]
**Describe the bug**
(Re-)connected to a cluster.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start Lens
2. Click a cluster in the sidebar

**Expected behaviour**
Show the resources available in the cluster.

**Screenshots**
![image](https://user-images.githubusercontent.com/1536228/170978572-28fc71e8-9932-4ea5-84b9-503ac8f1eace.png)

**Environment (please complete the following information):**
- Lens Version: 5.5.1-latest.20220526.1
- OS: macOS, 10.15.7 (19H1922)
- Installation method (e.g. snap or AppImage in Linux): Download (I seem to remember)

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Component stack:


    at Gr (/Applications/Lens.app/Contents/Resources/extensions/lenscloud-lens-extension/dist/renderer.js:90:621716)
    at div
    at /Applications/Lens.app/Contents/Resources/extensions/lenscloud-lens-extension/dist/renderer.js:90:617770
    at /Applications/Lens.app/Contents/Resources/extensions/lenscloud-lens-extension/dist/renderer.js:90:624173
    at /Applications/Lens.app/Contents/Resources/extensions/lenscloud-lens-extension/dist/renderer.js:1187:1287
    at /Applications/Lens.app/Contents/Resources/extensions/lenscloud-lens-extension/dist/renderer.js:1:4598
    at Ig (/Applications/Lens.app/Contents/Resources/extensions/lenscloud-lens-extension/dist/renderer.js:1206:247)
    at Og (/Applications/Lens.app/Contents/Resources/extensions/lenscloud-lens-extension/dist/renderer.js:1220:924)
    at div
    at /Applications/Lens.app/Contents/Resources/extensions/lenscloud-lens-extension/dist/renderer.js:16:129968
    at observerComponent (http://localhost:62705/build/Lens.js?199da6d1e6f9f3aa156b:266273:16)
    at div
    at div
    at observerComponent (http://localhost:62705/build/Lens.js?199da6d1e6f9f3aa156b:266273:16)
    at div
    at NonInjectedClusterManager (http://localhost:62705/build/chunks/8185.js:1216:33)
    at ErrorBoundary (http://localhost:62705/build/Lens.js?199da6d1e6f9f3aa156b:582238:9)
    at RootFrame (http://localhost:62705/build/chunks/8185.js:1300:9)
    at ThemeProvider (http://localhost:62705/build/Lens.js?199da6d1e6f9f3aa156b:127160:24)
    at Router (http://localhost:62705/build/Lens.js?199da6d1e6f9f3aa156b:454780:30)
Error stack:

TypeError: Cannot read properties of null (reading 'focus')
    at HTMLElement.e.focus (electron/js2c/renderer_init.js:117:3314)
    at Gr.r.createElement.r.createElement.tabIndex (/Applications/Lens.app/Contents/Resources/extensions/lenscloud-lens-extension/dist/renderer.js:90:623106)
    at fk (http://localhost:62705/build/Lens.js?199da6d1e6f9f3aa156b:453398:224)
    at exports.unstable_runWithPriority (http://localhost:62705/build/Lens.js?199da6d1e6f9f3aa156b:467326:343)
    at gg (http://localhost:62705/build/Lens.js?199da6d1e6f9f3aa156b:453258:325)
    at Oj (http://localhost:62705/build/Lens.js?199da6d1e6f9f3aa156b:453397:308)
    at Lj (http://localhost:62705/build/Lens.js?199da6d1e6f9f3aa156b:453379:50)
    at http://localhost:62705/build/Lens.js?199da6d1e6f9f3aa156b:453259:115
    at exports.unstable_runWithPriority (http://localhost:62705/build/Lens.js?199da6d1e6f9f3aa156b:467326:343)
    at gg (http://localhost:62705/build/Lens.js?199da6d1e6f9f3aa156b:453258:325)
    at jg (http://localhost:62705/build/Lens.js?199da6d1e6f9f3aa156b:453259:61)
    at ig (http://localhost:62705/build/Lens.js?199da6d1e6f9f3aa156b:453258:428)
    at Hb (http://localhost:62705/build/Lens.js?199da6d1e6f9f3aa156b:453428:101)
    at gd (http://localhost:62705/build/Lens.js?199da6d1e6f9f3aa156b:453209:352)
    at HTMLBodyElement.sentryWrapped (http://localhost:62705/build/Lens.js?199da6d1e6f9f3aa156b:543541:23)
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**

**Comment by Nokel81** [comment]
Closing as this has now been fixed.
