### ISSUE TITLE
Empty screen after application launch

### ISSUE THREAD

**Issue by activaigor** [kontena/lens#5502]
**Describe the bug**
After the application runs there is an empty window without any UI controls on it

**To Reproduce**
It's hard to tell how this problem happened, since no specific actions were done before the bug occured
The whole removing of ~/Library/Application Support/Lens did not help (as well as reinstallation of the app)

**Expected behavior**
Application shows it's UI elements

**Screenshots**
<img width="1352" alt="image" src="https://user-images.githubusercontent.com/8046594/171008723-9719b713-6a95-4211-b230-3c660bf368ad.png">

**Environment (please complete the following information):**
- Lens Version: 5.5.1
- OS: MacOS Monterey 12.3.1
- Installation method (e.g. snap or AppImage in Linux): apple silicon DMG

**Logs**
```
[USER-STORE]: LOADING from  ...
instrument.js:109 [USER-STORE]: LOADED from /Users/igorrizhyi/Library/Application Support/Lens/lens-user-store.json
instrument.js:109 [BOOTSTRAP-ROOT-FRAME]: initializing Registries
instrument.js:109 [BOOTSTRAP-ROOT-FRAME]: initializing EntitySettingsRegistry
instrument.js:109 [BOOTSTRAP-ROOT-FRAME]: initializing KubeObjectDetailRegistry
instrument.js:109 [BOOTSTRAP-ROOT-FRAME]: initializing CatalogEntityDetailRegistry
instrument.js:109 [BOOTSTRAP-ROOT-FRAME]: initializing CatalogCategoryRegistryEntries
instrument.js:109 [BOOTSTRAP-ROOT-FRAME]: initializing Catalog
instrument.js:109 [EXTENSIONS-STORE]: LOADING from  ...
instrument.js:109 [EXTENSIONS-STORE]: LOADED from /Users/igorrizhyi/Library/Application Support/Lens/lens-extensions.json
instrument.js:109 [FILESYSTEM-PROVISIONER-STORE]: LOADING from  ...
instrument.js:109 [FILESYSTEM-PROVISIONER-STORE]: LOADED from /Users/igorrizhyi/Library/Application Support/Lens/lens-filesystem-provisioner-store.json
instrument.js:109 [BOOTSTRAP-ROOT-FRAME]: initializing IpcRendererListeners
instrument.js:109 [CLUSTER-STORE]: LOADING from  ...
instrument.js:109 [CLUSTER-STORE]: LOADED from /Users/igorrizhyi/Library/Application Support/Lens/lens-cluster-store.json
instrument.js:109 [CLUSTER-STORE] requesting initial state sync
instrument.js:109 [HOTBAR-STORE]: LOADING from  ...
instrument.js:109 [HOTBAR-STORE]: LOADED from /Users/igorrizhyi/Library/Application Support/Lens/lens-hotbar-store.json
instrument.js:109 [WEBLINK-STORE]: LOADING from  ...
instrument.js:109 [WEBLINK-STORE]: LOADED from /Users/igorrizhyi/Library/Application Support/Lens/lens-weblink-store.json
instrument.js:109 [CLUSTER-STORE] start to listen (1)
instrument.js:109 License renderer extension activated
instrument.js:109 [EXTENSION-STORE-T]: LOADING from  ...
instrument.js:109 [EXTENSION-STORE-T]: LOADED from /Users/igorrizhyi/Library/Application Support/Lens/extension-store/lens-survey/preferences-store.json
instrument.js:109 telemetry extension activated
instrument.js:109 [EXTENSION-STORE-T]: LOADING from  ...
instrument.js:109 [EXTENSION-STORE-T]: LOADED from /Users/igorrizhyi/Library/Application Support/Lens/extension-store/lens-telemetry/preferences-store.json
instrument.js:109 [IPC-RENDERER]: adding extension listener Object
instrument.js:109 [ELECTRON-SYNC-STORE]: 2022-05-30T14:07:37.032Z - select-space-store ~ ElectronSyncStore:initialize, path /Users/igorrizhyi/Library/Application Support/Lens/extension-store/lenscloud-lens-extension/select-space-store.json model {}
instrument.js:109 [ELECTRON-SYNC-STORE]: 2022-05-30T14:07:37.032Z - select-space-store ~ ipcListen
instrument.js:109 [IPC-RENDERER]: adding extension listener Object
instrument.js:109 Can't access https://k8slens.dev/welcome_banners/welcome_banner_05.html?machine_id=a53866d469ee81b1a337a3c8d8a6a785a915a3a2f5f6b35b19c0c825c9590e91
(anonymous) @ instrument.js:109
instrument.js:109 [IPC-RENDERER]: adding extension listener Object
instrument.js:109 [IPC-RENDERER]: adding extension listener Object
instrument.js:109 [IPC-RENDERER]: adding extension listener Object
instrument.js:109 [LENS-SPACES-EXTENSION]: 30/05/2022, 17:07:37 Lens Spaces Extension activated
instrument.js:109 [EXTENSION]: enabled kube-object-event-status@5.5.1-latest.20220526.1
instrument.js:109 [EXTENSION]: enabled lens-license-extension@5.5.1-latest.20220526.1
instrument.js:109 [EXTENSION]: enabled lenscloud-lens-extension@5.5.1-latest.20220526.1
instrument.js:109 [EXTENSION]: enabled lens-metrics-cluster-feature@5.5.1-latest.20220526.1
instrument.js:109 [EXTENSION]: enabled lens-node-menu@5.5.1-latest.20220526.1
instrument.js:109 [EXTENSION]: enabled lens-pod-menu@5.5.1-latest.20220526.1
instrument.js:109 [EXTENSION]: enabled lens-survey@5.5.1-latest.20220526.1
instrument.js:109 [EXTENSION]: enabled lens-telemetry@5.5.1-latest.20220526.1
instrument.js:109 [PROTOCOL ROUTER]: internal registering /preferences
instrument.js:109 [PROTOCOL ROUTER]: internal registering /
instrument.js:109 [PROTOCOL ROUTER]: internal registering /landing
instrument.js:109 [PROTOCOL ROUTER]: internal registering /landing/view/:group/:kind
instrument.js:109 [PROTOCOL ROUTER]: internal registering /cluster
instrument.js:109 [PROTOCOL ROUTER]: internal registering /entity/:entityId/settings
instrument.js:109 [PROTOCOL ROUTER]: internal registering /cluster/:clusterId
instrument.js:109 [PROTOCOL ROUTER]: internal registering /cluster/:clusterId/settings
instrument.js:109 [PROTOCOL ROUTER]: internal registering /extensions
instrument.js:109 [PROTOCOL ROUTER]: internal registering /extensions/install/:LENS_INTERNAL_EXTENSION_PUBLISHER_MATCH(@[A-Za-z0-9_]+)?/:LENS_INTERNAL_EXTENSION_NAME_MATCH
instrument.js:109 [StorageHelper]: loading finished for /Users/igorrizhyi/Library/Application Support/Lens/lens-local-storage/app.json
instrument.js:109 [LENS-SPACES-EXTENSION]: (from:AuthCallbackServer) 30/05/2022, 17:07:37 Running AuthCallbackServer on http://localhost:49713
```

**Comment by ghost** [comment]
The same goes for me on Windows. Even uninstalling the 5.5.1 version and installing a 5.3.4 with renamed app data folder of `lens` doesn't help here. What the fuck happened here?!

**Comment by Omniscience-COS** [comment]
Lens has become unusable over the last 5 days. All of a sudden seeing this out of nowhere. ^^^

**Comment by flash-me** [comment]
Same On Linux

```
error:   ┃ [140]   error: OPError: expected 200 OK, got: 503 Service Unavailable
error:   ┃ [141]       at e.exports (/home/---/.config/Lens/extensions/lenscloud-lens-extension/dist/main.js:9:236642)
error:   ┃ [142]       at Function.discover (/home/---/.config/Lens/extensions/lenscloud-lens-extension/dist/main.js:9:1066560)
error:   ┃ [143]       at processTicksAndRejections (internal/process/task_queues.js:95:5) {
error:   ┃ [144]     error: 'expected 200 OK, got: 503 Service Unavailable'
error:   ┃ [145]   }
```

Maybe related to that ? 

cheers
flash ⚡

**Comment by nefelim4ag** [comment]
Looks like because they recently forcefully everyone to use oAuth, the Lens can't work without a connection to upstream 
https://app.k8slens.dev
```
upstream request timeout
```

So marketing faggots :)

**Comment by flash-me** [comment]
> Looks like because they recently forcefully everyone to use oAuth, the Lens can't work without a connection to upstream https://app.k8slens.dev
> 
> ```
> upstream request timeout
> ```
> 
> So marketing faggots :)

Seems like that page can't really handle that load...
![image](https://user-images.githubusercontent.com/5240450/171011223-572a7083-7f71-4a04-91b0-3e9ec8d2f738.png)

🤦🏽‍♂️ 

cheers
flash ⚡

**Comment by OneideLuizSchneider** [comment]
It took 5min to open the Login screen :/

![Screen Shot 2022-05-30 at 16 27 22](https://user-images.githubusercontent.com/5761239/171012670-f11d73bb-1f92-4db6-9be5-a124f68ab8eb.png)
![Screen Shot 2022-05-30 at 16 28 01](https://user-images.githubusercontent.com/5761239/171012788-d2eae231-e71e-4ec8-8960-f3006b1d36fa.png)

**Comment by activaigor** [comment]
works fine now. looks like they solved server issues

**Comment by Nokel81** [comment]
Yes the servers have been fixed. Closing this issue for the timing being.

**Comment by Nokel81** [comment]
We are working to make sure that Lens is will usable even when our IDP servers are not available.

**Comment by activaigor** [comment]
thanks guys, you are doing a really great job here!
