### ISSUE TITLE
Unable to start lens when no internet connection is present

### ISSUE THREAD

**Issue by danscarf** [kontena/lens#5503]
**Describe the bug**
Unable to start lens when no internet connection

**To Reproduce**
On a machine with no internet connection:
1. Start Lens
4. User is blocked from proceeding past the Lens ID screen (see screenshot)

**Expected behavior**
User should be able to start the application if the machine is not connected to the internet. 

**Screenshots**
![lens_bug](https://user-images.githubusercontent.com/8267608/171008421-6a9f957d-f452-4bde-a12c-840c2240dbcf.png)

**Environment (please complete the following information):**
- Lens Version: Lens Setup 5.5.1-latest.20220526.1.exe
- OS: Windows 11
- Installation method: Installer, which was downloaded from the 'latest releases'.

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
info:    Γû¬ ≡ƒôƒ Setting Lens as protocol client for lens:// +0ms
info:    Γû¬ ≡ƒôƒ Protocol client register succeeded Γ£à +1ms
info:    Γû¬ [EXTENSIONS-STORE]: LOADING from  ... +16ms
info:    Γû¬ [EXTENSIONS-STORE]: LOADED from C:\Users\dscar\AppData\Roaming\Lens\lens-extensions.json +9ms
info:    Γû¬ [FILESYSTEM-PROVISIONER-STORE]: LOADING from  ... +10ms
info:    Γû¬ [FILESYSTEM-PROVISIONER-STORE]: LOADED from C:\Users\dscar\AppData\Roaming\Lens\lens-filesystem-provisioner-store.json +4ms
info:    Γû¬ ≡ƒÜÇ Starting Lens from "C:\Users\dscar\AppData\Local\Programs\Lens\Lens.exe" +9ms
info:    Γû¬ ≡ƒÉÜ Syncing shell environment +0ms
info:    Γû¬ ≡ƒÆ╛ Loading stores +15ms
info:    Γû¬ [USER-STORE]: LOADING from  ... +2ms
info:    Γû¬ [USER-STORE]: LOADED from C:\Users\dscar\AppData\Roaming\Lens\lens-user-store.json +23ms
info:    Γû¬ [CLUSTER-STORE]: LOADING from  ... +24ms
info:    Γû¬ [CLUSTER-STORE]: LOADED from C:\Users\dscar\AppData\Roaming\Lens\lens-cluster-store.json +4ms
info:    Γû¬ [HOTBAR-STORE]: LOADING from  ... +2ms
info:    Γû¬ [HOTBAR-STORE]: LOADED from C:\Users\dscar\AppData\Roaming\Lens\lens-hotbar-store.json +5ms
info:    Γû¬ [WEBLINK-STORE]: LOADING from  ... +1ms
info:    Γû¬ [WEBLINK-STORE]: LOADED from C:\Users\dscar\AppData\Roaming\Lens\lens-weblink-store.json +6ms
info:    Γû¬ ≡ƒöî Starting LensProxy +28ms
info:    Γû¬ [LENS-PROXY]: Proxy server has started at 127.0.0.1:50962 +49ms
info:    Γû¬ ≡ƒöÄ Testing LensProxy connection ... +1ms
info:    Γû¬ ΓÜí LensProxy connection OK +42ms
info:    Γû¬ ≡ƒûÑ∩╕Å  Starting WindowManager +23ms
info:    Γû¬ ≡ƒº⌐ Initializing extensions +59ms
info:    Γû¬ [EXTENSION-DISCOVERY] loading extensions from C:\Users\dscar\AppData\Roaming\Lens +0ms
info:    Γû¬ [EXTENSION-INSTALLER] installing dependencies at C:\Users\dscar\AppData\Roaming\Lens +43ms
info:    Γû¬ [MENU]: autoUpdateDisabled=false +26ms
info:    Γû¬ [WINDOW-MANAGER]: Loading Main window from url: http://localhost:50962 ... +284ms
info:    Γû¬ [EXTENSION-INSTALLER] dependencies installed at C:\Users\dscar\AppData\Roaming\Lens +687ms
info:    Γû¬ [EXTENSION-DISCOVERY] watching extension add/remove in C:\Users\dscar\.k8slens\extensions +3ms
License main extension activated
Native extraction module not loaded, msgpackr will still run, but with decreased performance. Cannot find module 'msgpackr-extract'
info:    Γû¬ [LENS-SPACES-EXTENSION]: 5/30/2022, 7:07:46 AM Lens Spaces Extension activated +115ms
info:    Γû¬ [EXTENSION-STORE-T]: LOADING from  ... +7ms
info:    Γû¬ [EXTENSION-STORE-T]: LOADED from C:\Users\dscar\AppData\Roaming\Lens\extension-store\lens-survey\preferences-store.json +5ms
telemetry main extension activated
info:    Γû¬ [EXTENSION-STORE-T]: LOADING from  ... +60ms
info:    Γû¬ [EXTENSION-STORE-T]: LOADED from C:\Users\dscar\AppData\Roaming\Lens\extension-store\lens-telemetry\preferences-store.json +5ms
info:    Γû¬ [MENU]: autoUpdateDisabled=false +15ms
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: getaddrinfo ENOTFOUND api.segment.io
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
[ELECTRON-SYNC-STORE]: 2022-05-30T14:07:46.228Z - startup-store ~ ElectronSyncStore:initialize, path C:\Users\dscar\AppData\Roaming\Lens\extension-store\lenscloud-lens-extension\startup-store.json model {"skipSignup":false}
[ELECTRON-SYNC-STORE]: 2022-05-30T14:07:46.229Z - startup-store ~ ipcListen
[ELECTRON-SYNC-STORE]: 2022-05-30T14:07:46.229Z - select-space-store ~ ElectronSyncStore:initialize, path C:\Users\dscar\AppData\Roaming\Lens\extension-store\lenscloud-lens-extension\select-space-store.json model {}
[ELECTRON-SYNC-STORE]: 2022-05-30T14:07:46.231Z - select-space-store ~ ipcListen
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: getaddrinfo ENOTFOUND api.segment.io
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
info:    Γû¬ [WINDOW-MANAGER]: Main window loaded +2s
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: getaddrinfo ENOTFOUND api.segment.io
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
[ELECTRON-SYNC-STORE]: 2022-05-30T14:07:48.530Z - select-space-store ~ ipc electron-sync-store:renderer:initialize:select-space-store received
[ELECTRON-SYNC-STORE]: 2022-05-30T14:07:48.530Z - startup-store ~ ipc electron-sync-store:renderer:initialize:startup-store received
[ELECTRON-SYNC-STORE]: 2022-05-30T14:07:48.546Z - select-space-store ~ ipc electron-sync-store:renderer:initialize:select-space-store received
info:    Γû¬ [WINDOW-MANAGER]: Main window has reported that it has loaded +3s
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: getaddrinfo ENOTFOUND api.segment.io
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
info:    Γû¬ [KUBECONFIG-SYNC]: starting requested syncs +181ms
info:    ΓöÅ [KUBECONFIG-SYNC]: starting sync of file/folder +1ms
info:    Γöù [1] { filePath: 'C:\\Users\\dscar\\AppData\\Roaming\\Lens\\kubeconfigs' }
info:    ΓöÅ [KUBECONFIG-SYNC]: starting sync of file/folder +3ms
info:    Γöù [1] { filePath: 'C:\\Users\\dscar\\.kube' }
info:    Γû¬ ≡ƒôí Checking for app updates +2ms
info:    Γû¬ [AUTO-UPDATE]: electron-updater: Checking for update +0ms
error:   Γû¬ [AUTO-UPDATE]: electron-updater: Error: Error: net::ERR_NAME_NOT_RESOLVED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:7068)
    at SimpleURLLoaderWrapper.emit (events.js:376:20)
    at SimpleURLLoaderWrapper.emit (domain.js:470:12) +27ms
error:   ΓöÅ [UPDATE-CHECKER]: failed with an error net::ERR_NAME_NOT_RESOLVED +1ms
error:   Γöâ [1] Error: net::ERR_NAME_NOT_RESOLVED
error:   Γöâ [2]     at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:7068)
error:   Γöâ [3]     at SimpleURLLoaderWrapper.emit (events.js:376:20)
error:   Γöù [4]     at SimpleURLLoaderWrapper.emit (domain.js:470:12)
(node:3464) electron: The default of nativeWindowOpen is deprecated and will be changing from false to true in Electron 15.  See https://github.com/electron/electron/issues/28511 for more information.
(Use `Lens --trace-warnings ...` to show where the warning was created)
(node:3464) electron: Failed to load URL: https://app.k8slens.dev/signin/realms/lensCloud/protocol/openid-connect/auth?client_id=lens-extension&scope=openid%20offline_access&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A55304%2Flogin&state=ngsAw213-Ga1uST04o5rLdSP_QO12LAW98V8gldeHqg&response_mode=query&machine_id=de11e1dd67c558fe8979b05a080aa0c9228201a3848ff0e4833411319d72b312&inApp=true with error: ERR_NAME_NOT_RESOLVED
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: getaddrinfo ENOTFOUND api.segment.io
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: getaddrinfo ENOTFOUND api.segment.io
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: getaddrinfo ENOTFOUND api.segment.io
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
(node:3464) electron: The default of nativeWindowOpen is deprecated and will be changing from false to true in Electron 15.  See https://github.com/electron/electron/issues/28511 for more information.
(node:3464) electron: Failed to load URL: https://app.k8slens.dev/signin/realms/lensCloud/protocol/openid-connect/auth?client_id=lens-extension&scope=openid%20offline_access&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A55304%2Flogin&state=ngsAw213-Ga1uST04o5rLdSP_QO12LAW98V8gldeHqg&response_mode=query&machine_id=de11e1dd67c558fe8979b05a080aa0c9228201a3848ff0e4833411319d72b312&inApp=true with error: ERR_NAME_NOT_RESOLVED
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: getaddrinfo ENOTFOUND api.segment.io
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)

```

**Comment by superbiche** [comment]
Apparently it's now mandatory to sign-in to our Lens ID...  
Even if "Login with Github" is broken (no healthy upstream).  

So, yeah, going back to `kubectl` for today

**Comment by Nokel81** [comment]
The servers have now been fixed.
