### ISSUE TITLE
Unable to connect to Pods' shell using lens

### ISSUE THREAD

**Issue by 18191518054** [kontena/lens#5513]
click shell Always present  Connecting ...  But it doesn't connect

**Comment by 18191518054** [comment]
Always Connecting ...

**Comment by Nokel81** [comment]
Would you be able to provide more information?

**Comment by 18191518054** [comment]
![Snipaste_2022-06-01_16-34-12](https://user-images.githubusercontent.com/69226167/171362946-42e0a8a3-7ce3-49f1-a90f-05925b544be5.png)
Always Connecting ...

**Comment by Nokel81** [comment]
Any logs? Either from devtools console or when you quit the application completely and run it from the command line with DEBUG=true?

**Comment by 18191518054** [comment]
```
[LENS-SPACES-EXTENSION] Error getSpaceCa(), retrying... Error: Catalog api missing for Space 18191518054
    at e.J.Object.startingDelay [as request] (F:\workspace\Lens\resources\extensions\lenscloud-lens-extension\dist\main.js:9:1136521)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
error:   鈹?[22m [SHELL-SESSION]: failed to open a local shell File not found:  +18s
error:   鈹?[22m [1] Error: File not found:
error:   鈹?[22m [2]     at new WindowsPtyAgent (F:\workspace\Lens\resources\app.asar\node_modules\node-pty\lib\windowsPtyAgent.js:78:36)
error:   鈹?[22m [3]     at new WindowsTerminal (F:\workspace\Lens\resources\app.asar\node_modules\node-pty\lib\windowsTerminal.js:50:24)
error:   鈹?[22m [4]     at Object.spawn (F:\workspace\Lens\resources\app.asar\node_modules\node-pty\lib\index.js:28:12)
error:   鈹?[22m [5]     at l.ensureShellProcess (F:\workspace\Lens\resources\app.asar\static\build\main.js:1:317449)
error:   鈹?[22m [6]     at l.openShellProcess (F:\workspace\Lens\resources\app.asar\static\build\main.js:1:318082)
error:   鈹?[22m [7]     at async l.open (F:\workspace\Lens\resources\app.asar\static\build\main.js:1:307458)
(node:29216) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```


This is the software runtime log-----------------------

**Comment by Nokel81** [comment]
Thanks for the logs

**Comment by jason-hobbs** [comment]
I have this problem with with Rancher clusters.  When I try to open a shell from a pod on a rancher cluster I get:
<img width="310" alt="Screen Shot 2022-06-13 at 9 36 22 PM" src="https://user-images.githubusercontent.com/8509501/173481764-6b0e5692-73ee-4685-bc5b-7c7ea2a354bd.png">

Any non rancher cluster works fine.  

Here is the log:
```
info: [SHELL-SESSION]: shell has exited for 0da0e43917925facc7bd1dc7a4e2d0cd:3a952ed3-4928-4b1d-ae14-0ec768dc8fa3 closed with exitcode=1
info: [CLUSTER]: refresh {"accessible":true,"disconnected":false,"id":"0da0e43917925facc7bd1dc7a4e2d0cd","name":"stage-new","online":true,"ready":true}
info: [SHELL-SESSION]: websocket for 0da0e43917925facc7bd1dc7a4e2d0cd:3a952ed3-4928-4b1d-ae14-0ec768dc8fa3 closed with code=NormalClosure(1000) {"cluster":{"accessible":true,"disconnected":false,"id":"0da0e43917925facc7bd1dc7a4e2d0cd","name":"stage-new","online":true,"ready":true}}
```

**Comment by Nokel81** [comment]
What is your PTYSHELL env variable set to?

**Comment by Nokel81** [comment]
Or do you have the `shell` user preference set?

**Comment by jason-hobbs** [comment]
It is /bin/zsh

**Comment by Nokel81** [comment]
Okay thanks, can you open a new issue for rancher clusters in particular, but given that the OP is on windows and the logs provided what you are seeing is a separate issue.

**Comment by PavelMikhailouski** [comment]
Changing 
`File > Preferences > Terminal > Terminal Shell Path` from `sh` to `wsl` (or `powershell.exe`) solved the issue in my case
For some reason `sh` was the default value for this property even though I use Windows

**Comment by Nokel81** [comment]
@PavelMikhailouski Thanks for noticing that

**Comment by wqfra** [comment]
In Windows 10, you can install WSL using PowerShell with the command wsl --install. After completing the installation, you will need to restart your system, and then WSL should be ready for normal use.

**Comment by fadyabuhatoum1** [comment]
I have the issue now on macbook pro M3 , any suggestions here please?

**Comment by xorinzor** [comment]
Same issue still persistent. Connecting to a rancher node. Pod gets created, and I can shell into the pod, but the terminal window will stay stuck in connecting and eventually think the pod never got created and exit (after which the shell pod is removed).

On a macbook M1 Pro.

**Comment by Nokel81** [comment]
Would you be able to provide logs please?

**Comment by xorinzor** [comment]
@Nokel81 seeing a lot of connection errors, that is unfortunately something we've been running into a lot since we've been connecting via Rancher. But seems like that might interfere with Lens's ability to detect the shell pod being up and running (while this is happening I can connect manually to the shell pod and interact with it without issues, via lens)

<details>

<summary>log</summary>

```
2025-07-15T07:08:50.787Z error: 	[INTERNAL-PROXY-MAIN]: Connection Update { update: '2025/07/15 09:08:50 httputil: ReverseProxy read error during body copy: unexpected EOF\n2025/07/15 09:08:50 httputil: ReverseProxy read error during body copy: unexpected EOF\n2025/07/15 09:08:50 httputil: ReverseProxy read error during body copy: unexpected EOF\n', clusterId: '07d14d8a65e1b04b21545b56b7bb231c' }
2025-07-15T07:08:50.788Z error: 	[INTERNAL-PROXY-MAIN]: Connection Update { update: '2025/07/15 09:08:50 httputil: ReverseProxy read error during body copy: unexpected EOF\n2025/07/15 09:08:50 httputil: ReverseProxy read error during body copy: unexpected EOF\n2025/07/15 09:08:50 httputil: ReverseProxy read error during body copy: unexpected EOF\n2025/07/15 09:08:50 httputil: ReverseProxy read error during body copy: unexpected EOF\n2025/07/15 09:08:50 httputil: ReverseProxy read error during body copy: unexpected EOF\n2025/07/15 09:08:50 httputil: ReverseProxy read error during body copy: unexpected EOF\n', clusterId: '07d14d8a65e1b04b21545b56b7bb231c' }
2025-07-15T07:08:50.789Z warn: 	[INTERNAL-PROXY-MAIN]: Proxy response for clusterId=07d14d8a65e1b04b21545b56b7bb231c to url="/apis/apiextensions.k8s.io/v1/customresourcedefinitions?watch=1&resourceVersion=37367270&timeoutSeconds=600" errored with "ECONNRESET"
2025-07-15T07:08:50.789Z warn: 	[INTERNAL-PROXY-MAIN]: Proxy response for clusterId=07d14d8a65e1b04b21545b56b7bb231c to url="/apis/apiextensions.k8s.io/v1/customresourcedefinitions?watch=1&resourceVersion=37367274&timeoutSeconds=600" errored with "ECONNRESET"
2025-07-15T07:08:50.789Z warn: 	[INTERNAL-PROXY-MAIN]: Proxy response for clusterId=07d14d8a65e1b04b21545b56b7bb231c to url="/apis/apiextensions.k8s.io/v1/customresourcedefinitions?watch=1&resourceVersion=37362423&timeoutSeconds=600" errored with "ECONNRESET"
2025-07-15T07:08:50.789Z warn: 	[INTERNAL-PROXY-MAIN]: Proxy response for clusterId=07d14d8a65e1b04b21545b56b7bb231c to url="/api/v1/namespaces?watch=1&resourceVersion=37362423&timeoutSeconds=600" errored with "ECONNRESET"
2025-07-15T07:08:50.789Z warn: 	[INTERNAL-PROXY-MAIN]: Proxy response for clusterId=07d14d8a65e1b04b21545b56b7bb231c to url="/apis/apiextensions.k8s.io/v1/customresourcedefinitions?watch=1&resourceVersion=37362180&timeoutSeconds=600" errored with "ECONNRESET"
2025-07-15T07:08:50.789Z warn: 	[INTERNAL-PROXY-MAIN]: Proxy response for clusterId=07d14d8a65e1b04b21545b56b7bb231c to url="/api/v1/namespaces?watch=1&resourceVersion=37367274&timeoutSeconds=600" errored with "ECONNRESET"
2025-07-15T07:08:50.790Z warn: 	[INTERNAL-PROXY-MAIN]: Proxy response for clusterId=07d14d8a65e1b04b21545b56b7bb231c to url="/apis/apiextensions.k8s.io/v1/customresourcedefinitions?watch=1&resourceVersion=37367270&timeoutSeconds=600" errored with "ECONNRESET"
2025-07-15T07:08:50.790Z warn: 	[INTERNAL-PROXY-MAIN]: Proxy response for clusterId=07d14d8a65e1b04b21545b56b7bb231c to url="/api/v1/namespaces?watch=1&resourceVersion=37362182&timeoutSeconds=600" errored with "ECONNRESET"
2025-07-15T07:08:50.790Z warn: 	[INTERNAL-PROXY-MAIN]: Proxy response for clusterId=07d14d8a65e1b04b21545b56b7bb231c to url="/apis/apiextensions.k8s.io/v1/customresourcedefinitions?watch=1&resourceVersion=37362182&timeoutSeconds=600" errored with "ECONNRESET"
2025-07-15T07:09:42.186Z error: 	[INTERNAL-PROXY-MAIN]: Connection Update { update: '2025/07/15 09:09:42 httputil: ReverseProxy read error during body copy: unexpected EOF\n2025/07/15 09:09:42 httputil: ReverseProxy read error during body copy: unexpected EOF\n2025/07/15 09:09:42 httputil: ReverseProxy read error during body copy: unexpected EOF\n2025/07/15 09:09:42 httputil: ReverseProxy read error during body copy: unexpected EOF\n2025/07/15 09:09:42 httputil: ReverseProxy read error during body copy: unexpected EOF\n2025/07/15 09:09:42 httputil: ReverseProxy read error during body copy: unexpected EOF\n2025/07/15 09:09:42 httputil: ReverseProxy read error during body copy: unexpected EOF\n2025/07/15 09:09:42 httputil: ReverseProxy read error during body copy: unexpected EOF\n', clusterId: '07d14d8a65e1b04b21545b56b7bb231c' }
2025-07-15T07:09:42.188Z warn: 	[INTERNAL-PROXY-MAIN]: Proxy response for clusterId=07d14d8a65e1b04b21545b56b7bb231c to url="/apis/apiextensions.k8s.io/v1/customresourcedefinitions?watch=1&resourceVersion=37367270&timeoutSeconds=600" errored with "ECONNRESET"
2025-07-15T07:09:42.188Z warn: 	[INTERNAL-PROXY-MAIN]: Proxy response for clusterId=07d14d8a65e1b04b21545b56b7bb231c to url="/apis/apiextensions.k8s.io/v1/customresourcedefinitions?watch=1&resourceVersion=37362182&timeoutSeconds=600" errored with "ECONNRESET"
2025-07-15T07:09:42.189Z warn: 	[INTERNAL-PROXY-MAIN]: Proxy response for clusterId=07d14d8a65e1b04b21545b56b7bb231c to url="/api/v1/namespaces?watch=1&resourceVersion=37362182&timeoutSeconds=600" errored with "ECONNRESET"
2025-07-15T07:09:42.189Z warn: 	[INTERNAL-PROXY-MAIN]: Proxy response for clusterId=07d14d8a65e1b04b21545b56b7bb231c to url="/apis/apiextensions.k8s.io/v1/customresourcedefinitions?watch=1&resourceVersion=37362180&timeoutSeconds=600" errored with "ECONNRESET"
2025-07-15T07:09:42.189Z warn: 	[INTERNAL-PROXY-MAIN]: Proxy response for clusterId=07d14d8a65e1b04b21545b56b7bb231c to url="/apis/apiextensions.k8s.io/v1/customresourcedefinitions?watch=1&resourceVersion=37362423&timeoutSeconds=600" errored with "ECONNRESET"
2025-07-15T07:09:42.189Z warn: 	[INTERNAL-PROXY-MAIN]: Proxy response for clusterId=07d14d8a65e1b04b21545b56b7bb231c to url="/apis/apiextensions.k8s.io/v1/customresourcedefinitions?watch=1&resourceVersion=37367274&timeoutSeconds=600" errored with "ECONNRESET"
2025-07-15T07:09:42.190Z warn: 	[INTERNAL-PROXY-MAIN]: Proxy response for clusterId=07d14d8a65e1b04b21545b56b7bb231c to url="/apis/apiextensions.k8s.io/v1/customresourcedefinitions?watch=1&resourceVersion=37367270&timeoutSeconds=600" errored with "ECONNRESET"
2025-07-15T07:09:42.190Z warn: 	[INTERNAL-PROXY-MAIN]: Proxy response for clusterId=07d14d8a65e1b04b21545b56b7bb231c to url="/api/v1/namespaces?watch=1&resourceVersion=37367274&timeoutSeconds=600" errored with "ECONNRESET"
2025-07-15T07:09:42.191Z error: 	[INTERNAL-PROXY-MAIN]: Connection Update { update: '2025/07/15 09:09:42 httputil: ReverseProxy read error during body copy: unexpected EOF\n', clusterId: '07d14d8a65e1b04b21545b56b7bb231c' }
2025-07-15T07:09:42.192Z warn: 	[INTERNAL-PROXY-MAIN]: Proxy response for clusterId=07d14d8a65e1b04b21545b56b7bb231c to url="/api/v1/namespaces?watch=1&resourceVersion=37362423&timeoutSeconds=600" errored with "ECONNRESET"
2025-07-15T07:10:06.296Z error: 	[INTERNAL-PROXY-MAIN]: Connection Update { update: '2025/07/15 09:10:06 httputil: ReverseProxy read error during body copy: http2: server sent GOAWAY and closed the connection; LastStreamID=1999, ErrCode=NO_ERROR, debug=""\n2025/07/15 09:10:06 httputil: ReverseProxy read error during body copy: http2: server sent GOAWAY and closed the connection; LastStreamID=1999, ErrCode=NO_ERROR, debug=""\n2025/07/15 09:10:06 httputil: ReverseProxy read error during body copy: http2: server sent GOAWAY and closed the connection; LastStreamID=1999, ErrCode=NO_ERROR, debug=""\n2025/07/15 09:10:06 httputil: ReverseProxy read error during body copy: http2: server sent GOAWAY and closed the connection; LastStreamID=1999, ErrCode=NO_ERROR, debug=""\n2025/07/15 09:10:06 httputil: ReverseProxy read error during body copy: http2: server sent GOAWAY and closed the connection; LastStreamID=1999, ErrCode=NO_ERROR, debug=""\n2025/07/15 09:10:06 httputil: ReverseProxy read error during body copy: http2: server sent GOAWAY and closed the connection; LastStreamID=1999, ErrCode=NO_ERROR, debug=""\n2025/07/15 09:10:06 httputil: ReverseProxy read error during body copy: http2: server sent GOAWAY and closed the connection; LastStreamID=1999, ErrCode=NO_ERROR, debug=""\n2025/07/15 09:10:06 httputil: ReverseProxy read error during body copy: http2: server sent GOAWAY and closed the connection; LastStreamID=1999, ErrCode=NO_ERROR, debug=""\n2025/07/15 09:10:06 httputil: ReverseProxy read error during body copy: http2: server sent GOAWAY and closed the connection; LastStreamID=1999, ErrCode=NO_ERROR, debug=""\n2025/07/15 09:10:06 httputil: ReverseProxy read error during body copy: http2: server sent GOAWAY and closed the connection; LastStreamID=1999, ErrCode=NO_ERROR, debug=""\n2025/07/15 09:10:06 httputil: ReverseProxy read error during body copy: http2: server sent GOAWAY and closed the connection; LastStreamID=1999, ErrCode=NO_ERROR, debug=""\n2025/07/15 09:10:06 httputil: ReverseProxy read error during body copy: http2: server sent GOAWAY and closed the connection; LastStreamID=1999, ErrCode=NO_ERROR, debug=""\n', clusterId: 'e6782cd2f23ba359b1c872d1260a7ee6' }
2025-07-15T07:10:06.299Z warn: 	[INTERNAL-PROXY-MAIN]: Proxy response for clusterId=e6782cd2f23ba359b1c872d1260a7ee6 to url="/api/v1/namespaces?watch=1&resourceVersion=34983155&timeoutSeconds=600" errored with "ECONNRESET"
2025-07-15T07:10:06.299Z warn: 	[INTERNAL-PROXY-MAIN]: Proxy response for clusterId=e6782cd2f23ba359b1c872d1260a7ee6 to url="/apis/apiextensions.k8s.io/v1/customresourcedefinitions?watch=1&resourceVersion=34989740&timeoutSeconds=600" errored with "ECONNRESET"
2025-07-15T07:10:06.299Z warn: 	[INTERNAL-PROXY-MAIN]: Proxy response for clusterId=e6782cd2f23ba359b1c872d1260a7ee6 to url="/api/v1/namespaces?watch=1&resourceVersion=34978413&timeoutSeconds=600" errored with "ECONNRESET"
2025-07-15T07:10:06.300Z warn: 	[INTERNAL-PROXY-MAIN]: Proxy response for clusterId=e6782cd2f23ba359b1c872d1260a7ee6 to url="/api/v1/namespaces?watch=1&resourceVersion=34989733&timeoutSeconds=600" errored with "ECONNRESET"
2025-07-15T07:10:06.300Z warn: 	[INTERNAL-PROXY-MAIN]: Proxy response for clusterId=e6782cd2f23ba359b1c872d1260a7ee6 to url="/apis/apiextensions.k8s.io/v1/customresourcedefinitions?watch=1&resourceVersion=34978412&timeoutSeconds=600" errored with "ECONNRESET"
2025-07-15T07:10:06.301Z warn: 	[INTERNAL-PROXY-MAIN]: Proxy response for clusterId=e6782cd2f23ba359b1c872d1260a7ee6 to url="/apis/apiextensions.k8s.io/v1/customresourcedefinitions?watch=1&resourceVersion=34978111&timeoutSeconds=600" errored with "ECONNRESET"
2025-07-15T07:10:06.301Z warn: 	[INTERNAL-PROXY-MAIN]: Proxy response for clusterId=e6782cd2f23ba359b1c872d1260a7ee6 to url="/api/v1/namespaces?watch=1&resourceVersion=34978111&timeoutSeconds=600" errored with "ECONNRESET"
2025-07-15T07:10:06.301Z warn: 	[INTERNAL-PROXY-MAIN]: Proxy response for clusterId=e6782cd2f23ba359b1c872d1260a7ee6 to url="/apis/apiextensions.k8s.io/v1/customresourcedefinitions?watch=1&resourceVersion=34983155&timeoutSeconds=600" errored with "ECONNRESET"
2025-07-15T07:10:06.301Z warn: 	[INTERNAL-PROXY-MAIN]: Proxy response for clusterId=e6782cd2f23ba359b1c872d1260a7ee6 to url="/apis/apiextensions.k8s.io/v1/customresourcedefinitions?watch=1&resourceVersion=34978653&timeoutSeconds=600" errored with "ECONNRESET"
2025-07-15T07:10:06.302Z warn: 	[INTERNAL-PROXY-MAIN]: Proxy response for clusterId=e6782cd2f23ba359b1c872d1260a7ee6 to url="/api/v1/namespaces/deep-edge/pods?watch=1&resourceVersion=34989877&timeoutSeconds=600" errored with "ECONNRESET"
2025-07-15T07:10:06.303Z error: 	[INTERNAL-PROXY-MAIN]: Connection Update { update: '2025/07/15 09:10:06 httputil: ReverseProxy read error during body copy: http2: server sent GOAWAY and closed the connection; LastStreamID=1999, ErrCode=NO_ERROR, debug=""\n2025/07/15 09:10:06 httputil: ReverseProxy read error during body copy: http2: server sent GOAWAY and closed the connection; LastStreamID=1999, ErrCode=NO_ERROR, debug=""\n2025/07/15 09:10:06 httputil: ReverseProxy read error during body copy: http2: server sent GOAWAY and closed the connection; LastStreamID=1999, ErrCode=NO_ERROR, debug=""\n2025/07/15 09:10:06 httputil: ReverseProxy read error during body copy: http2: server sent GOAWAY and closed the connection; LastStreamID=1999, ErrCode=NO_ERROR, debug=""\n2025/07/15 09:10:06 httputil: ReverseProxy read error during body copy: http2: server sent GOAWAY and closed the connection; LastStreamID=1999, ErrCode=NO_ERROR, debug=""\n2025/07/15 09:10:06 httputil: ReverseProxy read error during body copy: http2: server sent GOAWAY and closed the connection; LastStreamID=1999, ErrCode=NO_ERROR, debug=""\n2025/07/15 09:10:06 httputil: ReverseProxy read error during body copy: http2: server sent GOAWAY and closed the connection; LastStreamID=1999, ErrCode=NO_ERROR, debug=""\n2025/07/15 09:10:06 httputil: ReverseProxy read error during body copy: http2: server sent GOAWAY and closed the connection; LastStreamID=1999, ErrCode=NO_ERROR, debug=""\n', clusterId: 'e6782cd2f23ba359b1c872d1260a7ee6' }
2025-07-15T07:10:06.304Z warn: 	[INTERNAL-PROXY-MAIN]: Proxy response for clusterId=e6782cd2f23ba359b1c872d1260a7ee6 to url="/api/v1/nodes?watch=1&resourceVersion=34989733&timeoutSeconds=600" errored with "ECONNRESET"
2025-07-15T07:10:06.305Z warn: 	[INTERNAL-PROXY-MAIN]: Proxy response for clusterId=e6782cd2f23ba359b1c872d1260a7ee6 to url="/apis/apiextensions.k8s.io/v1/customresourcedefinitions?watch=1&resourceVersion=34989733&timeoutSeconds=600" errored with "ECONNRESET"
2025-07-15T07:10:06.305Z warn: 	[INTERNAL-PROXY-MAIN]: Proxy response for clusterId=e6782cd2f23ba359b1c872d1260a7ee6 to url="/api/v1/namespaces?watch=1&resourceVersion=34989733&timeoutSeconds=600" errored with "ECONNRESET"
2025-07-15T07:10:06.305Z warn: 	[INTERNAL-PROXY-MAIN]: Proxy response for clusterId=e6782cd2f23ba359b1c872d1260a7ee6 to url="/apis/apiextensions.k8s.io/v1/customresourcedefinitions?watch=1&resourceVersion=34978753&timeoutSeconds=600" errored with "ECONNRESET"
2025-07-15T07:10:06.305Z warn: 	[INTERNAL-PROXY-MAIN]: Proxy response for clusterId=e6782cd2f23ba359b1c872d1260a7ee6 to url="/apis/apiextensions.k8s.io/v1/customresourcedefinitions?watch=1&resourceVersion=34987430&timeoutSeconds=600" errored with "ECONNRESET"
2025-07-15T07:10:06.305Z warn: 	[INTERNAL-PROXY-MAIN]: Proxy response for clusterId=e6782cd2f23ba359b1c872d1260a7ee6 to url="/api/v1/namespaces?watch=1&resourceVersion=34978653&timeoutSeconds=600" errored with "ECONNRESET"
2025-07-15T07:10:06.306Z warn: 	[INTERNAL-PROXY-MAIN]: Proxy response for clusterId=e6782cd2f23ba359b1c872d1260a7ee6 to url="/apis/apiextensions.k8s.io/v1/customresourcedefinitions?watch=1&resourceVersion=34537204&timeoutSeconds=600" errored with "ECONNRESET"
2025-07-15T07:10:06.306Z warn: 	[INTERNAL-PROXY-MAIN]: Proxy response for clusterId=e6782cd2f23ba359b1c872d1260a7ee6 to url="/api/v1/namespaces/deep-edge/events?watch=1&resourceVersion=34989733&timeoutSeconds=600" errored with "ECONNRESET"
2025-07-15T07:10:06.306Z warn: 	[INTERNAL-PROXY-MAIN]: Proxy response for clusterId=e6782cd2f23ba359b1c872d1260a7ee6 to url="/api/v1/namespaces?watch=1&resourceVersion=34987430&timeoutSeconds=600" errored with "ECONNRESET"
2025-07-15T07:10:06.306Z warn: 	[INTERNAL-PROXY-MAIN]: Proxy response for clusterId=e6782cd2f23ba359b1c872d1260a7ee6 to url="/api/v1/namespaces?watch=1&resourceVersion=34978753&timeoutSeconds=600" errored with "ECONNRESET"
2025-07-15T07:10:15.417Z error: 	[NODE-SHELL]: aborting wait for node-shell-88c30d02-66f9-418b-aed5-9c2652d2782c, timing out
2025-07-15T07:10:15.418Z info: 	[INTERNAL-PROXY]: watch (pod-4) aborted /api/v1/namespaces/kube-system/pods?watch=1&resourceVersion=32929430
2025-07-15T07:10:15.420Z error: 	[SHELL-SESSION]: failed to open a node shell failed to create node pod
2025-07-15T07:10:15.545Z debug: 	[INTERNAL-PROXY]: [JSON-API] request DELETE https://127.0.0.1:54128/api-kube/api/v1/namespaces/kube-system/pods/node-shell-88c30d02-66f9-418b-aed5-9c2652d2782c?propagationPolicy=Background { data: { kind: 'Pod', apiVersion: 'v1', metadata: { name: 'node-shell-88c30d02-66f9-418b-aed5-9c2652d2782c', namespace: 'kube-system', uid: 'bfa1f3cf-d6df-4242-9365-42cb5ae7bff2', resourceVersion: '34990674', creationTimestamp: '2025-07-15T07:08:15Z', deletionTimestamp: '2025-07-15T07:10:15Z', deletionGracePeriodSeconds: 0, managedFields: [Array] }, spec: { volumes: [Array], containers: [Array], restartPolicy: 'Never', terminationGracePeriodSeconds: 0, dnsPolicy: 'ClusterFirst', serviceAccountName: 'default', serviceAccount: 'default', nodeName: 'node1', hostNetwork: true, hostPID: true, hostIPC: true, securityContext: {}, schedulerName: 'default-scheduler', tolerations: [Array], priorityClassName: 'system-node-critical', priority: 2000001000, enableServiceLinks: true, preemptionPolicy: 'PreemptLowerPriority' }, status: { phase: 'Running', conditions: [Array], hostIP: '10.187.11.10', hostIPs: [Array], podIP: '10.187.11.10', podIPs: [Array], startTime: '2025-07-15T07:08:15Z', containerStatuses: [Array], qosClass: 'BestEffort' } }, reqInit: { method: 'delete', headers: { 'content-type': 'application/json', host: 'e6782cd2f23ba359b1c872d1260a7ee6.lens.app:54128' } } }

```

</details>


And in the shell window in lens:
```
Error occurred: Pod creation timed outfailed to open a node shell: failed to create node podError occurred: Pod creation timed outfailed to open a node shell: failed to create node podError occurred: Error: Failed to POST "https://127.0.0.1:54128/api-kube/api/v1/namespaces/kube-system/pods": Internal Server Error (500)failed to open a node shell: failed to create node pod: Failed to POST "https://127.0.0.1:54128/api-kube/api/v1/namespaces/kube-system/pods": Internal Server Error (500)
```

**Comment by Nokel81** [comment]
Yeah, if we are getting 500s then that certainly would mess with the ability to know that the pod was created successfully. Thanks for the reply

**Comment by xorinzor** [comment]
is this something that can be resolved? the pod is getting created, so perhaps a different api call with retry to check if it succeeded?
