### ISSUE TITLE
Crash on upgrading Helm release

### ISSUE THREAD

**Issue by joaocc** [kontena/lens#5645]
**Describe the bug**
Crash when trying to upgrade Helm release

**To Reproduce**
1. Go to Helm/Releases
2. Click on "Upgrade" on a release

**Expected behavior**
Not crash

**Environment (please complete the following information):**
- Lens Version: 5.5.4
- OS: macOS [x64 on M1]
- Installation method (e.g. snap or AppImage in Linux): brew

```
Component stack:


    at MonacoEditor (http://f73273cfd98ffa64ec8a9f2e1b856eba.localhost:52348/build/Lens.js?19ea31497117aa70e6c7:587405:9)
    at NonInjectedEditorPanel (http://f73273cfd98ffa64ec8a9f2e1b856eba.localhost:52348/build/chunks/888.js:853:9)
    at div
    at NonInjectedUpgradeChart (http://f73273cfd98ffa64ec8a9f2e1b856eba.localhost:52348/build/chunks/888.js:2541:9)
    at div
    at ErrorBoundary (http://f73273cfd98ffa64ec8a9f2e1b856eba.localhost:52348/build/Lens.js?19ea31497117aa70e6c7:582233:9)
    at div
    at NonInjectedDock (http://f73273cfd98ffa64ec8a9f2e1b856eba.localhost:52348/build/chunks/888.js:2739:9)
    at div
    at div
    at NonInjectedMainLayout (http://f73273cfd98ffa64ec8a9f2e1b856eba.localhost:52348/build/Lens.js?19ea31497117aa70e6c7:586175:9)
    at ErrorBoundary (http://f73273cfd98ffa64ec8a9f2e1b856eba.localhost:52348/build/Lens.js?19ea31497117aa70e6c7:582233:9)
    at NonInjectedClusterFrame (http://f73273cfd98ffa64ec8a9f2e1b856eba.localhost:52348/build/chunks/888.js:2924:9)
    at ThemeProvider (http://f73273cfd98ffa64ec8a9f2e1b856eba.localhost:52348/build/Lens.js?19ea31497117aa70e6c7:127160:24)
    at Router (http://f73273cfd98ffa64ec8a9f2e1b856eba.localhost:52348/build/Lens.js?19ea31497117aa70e6c7:454780:30)

```

```
Error stack:

TypeError: factory.create is not a function
    at createTextBuffer (http://f73273cfd98ffa64ec8a9f2e1b856eba.localhost:52348/build/Lens.js?19ea31497117aa70e6c7:363066:20)
    at new TextModel (http://f73273cfd98ffa64ec8a9f2e1b856eba.localhost:52348/build/Lens.js?19ea31497117aa70e6c7:363155:44)
    at ModelServiceImpl._createModelData (http://f73273cfd98ffa64ec8a9f2e1b856eba.localhost:52348/build/Lens.js?19ea31497117aa70e6c7:371152:23)
    at ModelServiceImpl.createModel (http://f73273cfd98ffa64ec8a9f2e1b856eba.localhost:52348/build/Lens.js?19ea31497117aa70e6c7:371193:30)
    at doCreateModel (http://f73273cfd98ffa64ec8a9f2e1b856eba.localhost:52348/build/Lens.js?19ea31497117aa70e6c7:419096:25)
    at createTextModel (http://f73273cfd98ffa64ec8a9f2e1b856eba.localhost:52348/build/Lens.js?19ea31497117aa70e6c7:419090:12)
    at Object.createModel (http://f73273cfd98ffa64ec8a9f2e1b856eba.localhost:52348/build/Lens.js?19ea31497117aa70e6c7:427958:12)
    at MonacoEditor.get model (http://f73273cfd98ffa64ec8a9f2e1b856eba.localhost:52348/build/Lens.js?19ea31497117aa70e6c7:587475:35)
    at ComputedValue.computeValue_ (http://f73273cfd98ffa64ec8a9f2e1b856eba.localhost:52348/build/Lens.js?19ea31497117aa70e6c7:268929:33)
    at ComputedValue.get (http://f73273cfd98ffa64ec8a9f2e1b856eba.localhost:52348/build/Lens.js?19ea31497117aa70e6c7:268850:28)

```

**Comment by jim-docker** [comment]
Can't reproduce. @joaocc was it just for a specific release? The error log implicates the Monaco Editor, which is used in the dock tabs (like Create resource, Helm installs, upgrades) Did you have other tabs open at the time?

**Comment by joaocc** [comment]
Hi. Can no longer reproduce, and I don't remember enough to be able to answer your question properly. Sorry.

**Comment by aleksfront** [comment]
Reproduced similar error while opening `Install chart` tab. This happens what not a string references passed to `MonacoEditor` as a value.

**Comment by aleksfront** [comment]
Not reproducible anymore.
