### ISSUE TITLE
helm charts

### ISSUE THREAD

**Issue by goalidea** [kontena/lens#6086]
**Describe the bug**
helm charts has no content, when toggle developer tools here is error message:

```
The user aborted a request. 
AbortError {type: 'aborted', message: 'The user aborted a request.', stack: 'AbortError: The user aborted a request.\n    at abo…8596/build/Lens.js?638f230ede63077704e9:240795:12'}
message: "The user aborted a request."
type: "aborted"
stack: "AbortError: The user aborted a request.
    at abort (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/node-fetch/lib/index.js:1440:16)
    at AbortSignal.abortAndFinalize (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/node-fetch/lib/index.js:1455:4)
    at AbortSignal.<anonymous> (http://cbe3f8c49b56568152c52f37e276a187.localhost:58596/build/Lens.js?638f230ede63077704e9:522675:18)
    at AbortSignal.<anonymous> (http://cbe3f8c49b56568152c52f37e276a187.localhost:58596/build/Lens.js?638f230ede63077704e9:522675:18)
    at http://cbe3f8c49b56568152c52f37e276a187.localhost:58596/build/Lens.js?638f230ede63077704e9:623278:28
    at http://cbe3f8c49b56568152c52f37e276a187.localhost:58596/build/Lens.js?638f230ede63077704e9:225659:25
    at http://cbe3f8c49b56568152c52f37e276a187.localhost:58596/build/Lens.js?638f230ede63077704e9:241235:15
    at Array.forEach (<anonymous>)
    at NonInjectedClusterOverview.runDisposersOnWillUnmount (http://cbe3f8c49b56568152c52f37e276a187.localhost:58596/build/Lens.js?638f230ede63077704e9:241229:66)
    at http://cbe3f8c49b56568152c52f37e276a187.localhost:58596/build/Lens.js?638f230ede63077704e9:240795:12"
[[Prototype]]: Error
```

**To Reproduce**
1. Go to 'cluster'
2. Click on 'helm'
3. Scroll down to 'charts'

**Expected behavior**
helm charts list.

**Screenshots**
![](https://www.v2ex.com/i/1aa7oIb9.png)
![](https://www.v2ex.com/i/633KQfEI.png)

**Environment (please complete the following information):**
- Lens Version: 6.0.1-latest.20220810.2
- OS: 10.15.7
- Installation method (e.g. snap or AppImage in Linux): brew

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**

**Comment by Nokel81** [comment]
Can you show a screenshot please?

**Comment by goalidea** [comment]
> Can you show a screenshot please?

https://www.v2ex.com/i/1aa7oIb9.png

**Comment by Nokel81** [comment]
Those error messages are unrelated to the loading of helm charts.

Would you be able to run Lens from the command line (after fully quitting via the tray menu) as posting any related logs to helm charts?

Another possible hint would be if you are able to run `helm repo upgrade` from the terminal.

**Comment by goalidea** [comment]
> Those error messages are unrelated to the loading of helm charts.
> 
> Would you be able to run Lens from the command line (after fully quitting via the tray menu) as posting any related logs to helm charts?
> 
> Another possible hint would be if you are able to run `helm repo upgrade` from the terminal.

i am not install helm. However, the previous version does not have this problem. Upgrading to the latest version of lens helm has no content
