### ISSUE TITLE
HTTP(S) proxy resolving does not work if no windows open

### ISSUE THREAD

**Issue by jakolehm** [kontena/lens#6159]
**Describe the bug**
If app does not have any windows it will log these errors:
```
error:   ┏ Error resolving proxy Tried to resolve proxy for "https://api.k8slens.dev/", but no browser window was available +20s
error:   ┃ [ 1] Error: Tried to resolve proxy for "https://api.k8slens.dev/", but no browser window was available
```

**Expected behavior**
Proxy resolver should work even if windows are closed. Maybe Lens could spawn a lightweight hidden window for this purpose (if main window does not exist)?.

**Comment by sbollap1** [comment]
I am using Lens 
![image](https://user-images.githubusercontent.com/4892241/223861805-c923f227-af6f-4090-9b30-8eecca16269b.png)
and I seeing such issue. any work around for this?
```

error: [LENS-PROXY]: http proxy errored for cluster: Error: read ECONNRESET {"url":"/version"}
debug: Failed proxy to target: {
  "protocol": "https:",
  "host": "127.0.0.1",
  "port": 57352,
  "path": "/54c51ddde7ffa065",
  "ca": "-----BEGIN CERTIFICATE-----\r\m7em8sOJXIqzdi\r\nQiS0XAYYPedY1snH9AnU//V5UlbOPfh3oPkf6cLWU0rbMvi/jMGzIl0=\r\n-----END CERTIFICATE-----\r\n"
}
error: [CLUSTER]: Failed to connect to "abcdtest1": Error: Failed to get /version for clusterId=c3dbdbdbdkirirl103043: Internal Server Error
error: Failed to get /version for clusterId=c3dbdbdbdkirirl103043: Internal Server Error {"meta":{"accessible":false,"disconnected":true,"id":"c3dbdbdbdkirirl103043","name":"abcdtest1","online":false,"ready":false}}
error: Error resolving proxy Tried to resolve proxy for "https://api.k8slens.dev", but no browser window was available {"stack":"Error: Tried to resolve proxy for \"https://api.k8slens.dev\", but no browser window was available\n    at C:\\Users\\pollaset\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\@k8slens\\core\\static\\build\\library\\main.js:50540:23\n    at C:\\Users\\pollaset\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\@k8slens\\core\\static\\build\\library\\main.js:23971:31\n    at C:\\Users\\pollaset\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\@k8slens\\core\\static\\build\\library\\main.js:50574:25\n    at PacProxyAgent.getProxyString (C:\\Users\\pollaset\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\@k8slens\\core\\static\\build\\library\\main.js:53576:12)\n    at PacProxyAgent.callback (C:\\Users\\pollaset\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\@lensapp\\lenscloud-lens-extension\\dist\\main.js:2:26710)\n    at PacProxyAgent.addRequest (C:\\Users\\pollaset\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\@lensapp\\lenscloud-lens-extension\\dist\\main.js:2:66726)\n    at new ClientRequest (node:_http_client:305:16)\n    at request (node:https:353:10)\n    at Request._makeRequest (C:\\Users\\pollaset\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\@lensapp\\lenscloud-lens-extension\\dist\\main.js:2:310076)\n    at C:\\Users\\pollaset\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\@lensapp\\lenscloud-lens-extension\\dist\\main.js:2:294575"}
info: [CREATE-ELECTRON-WINDOW]: Loading content for window "splash" from file: C:\Users\pollaset\AppData\Local\Programs\Lens\resources\app.asar\static\splash.html...
info: [CREATE-ELECTRON-WINDOW]: Window "splash" loaded
info: [CREATE-ELECTRON-WINDOW]: Loading content for window "first-application-window" from url: https://lens.app:57232...
info: [CREATE-ELECTRON-WINDOW]: Window "first-application-window" loaded
info: [CLUSTER]: activate {"accessible":false,"disconnected":true,"id":"c3dbdbdbdkirirl103043","name":"abcdtest1","online":false,"ready":false}
info: [CLUSTER]: bind events {"accessible":false,"disconnected":true,"id":"c3dbdbdbdkirirl103043","name":"abcdtest1","online":false,"ready":false}
info: Starting connection ... {"meta":{"accessible":false,"disconnected":true,"id":"c3dbdbdbdkirirl103043","name":"abcdtest1","online":false,"ready":false}}
info: [CLUSTER]: reconnect {"accessible":false,"disconnected":true,"id":"c3dbdbdbdkirirl103043","name":"abcdtest1","online":false,"ready":false}
info: Authentication proxy started {"meta":{"accessible":false,"disconnected":true,"id":"c3dbdbdbdkirirl103043","name":"abcdtest1","online":false,"ready":false}}
info: [KUBE-AUTH-PROXY]: found port=58834
debug: [CLUSTER-MANAGER]: updating catalog from cluster store
info: Refreshing connection status ... {"meta":{"accessible":false,"disconnected":false,"id":"c3dbdbdbdkirirl103043","name":"abcdtest1","online":false,"ready":false}}

```
