### ISSUE TITLE
App crash at /pods

### ISSUE THREAD

**Issue by lisenet** [kontena/lens#6220]
**Describe the bug**
App crashed.

**To Reproduce**
N/A

**Expected behavior**
App does not crash.

**Screenshots**
![lens-crash](https://user-images.githubusercontent.com/8998418/189376027-c0844c54-d2c9-404e-8b0a-df296d1c69cf.png)

**Environment (please complete the following information):**
- Lens Version: 5.3.3-latest.2021223.1
- OS: Ubuntu 18.04 LTS
- Installation method: apt

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Component stack:


    at wrappedComponent (http://635d3758954edd7afe4094d29e95caee.localhost:44881/build/Lens.js:10557:16)
    at div
    at Logs (http://635d3758954edd7afe4094d29e95caee.localhost:44881/build/chunks/5.js:7281:9)
    at div
    at div
    at Dock (http://635d3758954edd7afe4094d29e95caee.localhost:44881/build/chunks/5.js:7713:9)
    at div
    at div
    at MainLayout (http://635d3758954edd7afe4094d29e95caee.localhost:44881/build/Lens.js:286623:9)
    at ErrorBoundary (http://635d3758954edd7afe4094d29e95caee.localhost:44881/build/Lens.js:237976:9)
    at Router (http://635d3758954edd7afe4094d29e95caee.localhost:44881/build/Lens.js:79057:30)
    at ClusterFrame (http://635d3758954edd7afe4094d29e95caee.localhost:44881/build/chunks/5.js:7941:9)
    at ThemeProvider (http://635d3758954edd7afe4094d29e95caee.localhost:44881/build/Lens.js:609784:24)


Error stack:

TypeError: Cannot create a KubeObject from undefined
    at new KubeObject (http://635d3758954edd7afe4094d29e95caee.localhost:44881/build/Lens.js:32750:19)
    at new WorkloadKubeObject (http://635d3758954edd7afe4094d29e95caee.localhost:44881/build/Lens.js:124965:1)
    at new Pod (http://635d3758954edd7afe4094d29e95caee.localhost:44881/build/Lens.js:154535:9)
    at http://635d3758954edd7afe4094d29e95caee.localhost:44881/build/chunks/5.js:7213:17
    at http://635d3758954edd7afe4094d29e95caee.localhost:44881/build/Lens.js:10557:49
    at http://635d3758954edd7afe4094d29e95caee.localhost:44881/build/Lens.js:10521:25
    at trackDerivedFunction (http://635d3758954edd7afe4094d29e95caee.localhost:44881/build/Lens.js:3120:18)
    at Reaction.track (http://635d3758954edd7afe4094d29e95caee.localhost:44881/build/Lens.js:3649:18)
    at useObserver (http://635d3758954edd7afe4094d29e95caee.localhost:44881/build/Lens.js:10519:14)
    at wrappedComponent (http://635d3758954edd7afe4094d29e95caee.localhost:44881/build/Lens.js:10557:16)
    at Ch (http://635d3758954edd7afe4094d29e95caee.localhost:44881/build/Lens.js:556372:137)
    at li (http://635d3758954edd7afe4094d29e95caee.localhost:44881/build/Lens.js:556395:154)
    at ki (http://635d3758954edd7afe4094d29e95caee.localhost:44881/build/Lens.js:556393:169)
    at ck (http://635d3758954edd7afe4094d29e95caee.localhost:44881/build/Lens.js:556489:157)
    at bk (http://635d3758954edd7afe4094d29e95caee.localhost:44881/build/Lens.js:556465:347)
    at ak (http://635d3758954edd7afe4094d29e95caee.localhost:44881/build/Lens.js:556465:278)
```

**Kubeconfig:**
The problem was not caused by malformed kubeconfig.

**Additional context**
N/A

**Comment by Nokel81** [comment]
This has been fixed in a newer version of Lens. Please upgrade.

**Comment by lisenet** [comment]
Does the latest version of Lens still require one to sign up to your service and have an account?
