### ISSUE TITLE
Disable or reduce log level

### ISSUE THREAD

**Issue by silveraignacio** [kontena/lens#6254]
Hi! I have installed Lens App 6.0.1 and running it on a Fedora 35 with gnome desktop. 
I have noticed that it is generating a lot of logs entries on messages files. It is all the time writing logs with information that I think is not necessary. For example, is logging all the time that I access to a cluster, or open a pod to check information, etc.

Below you can find some examples of logs:
```
Sep 15 11:18:03 computer01 lens.desktop[4061571]: info:    ┏ [CLUSTER]: refresh +26s
Sep 15 11:18:03 computer01 lens.desktop[4061571]: info:    ┃ [1] {
Sep 15 11:18:03 computer01 lens.desktop[4061571]: info:    ┃ [2]   id: '1fd3838f862addc1eeb5ce615849c708',
Sep 15 11:18:03 computer01 lens.desktop[4061571]: info:    ┃ [3]   name: 'mycluster',
Sep 15 11:18:03 computer01 lens.desktop[4061571]: info:    ┃ [4]   ready: true,
Sep 15 11:18:03 computer01 lens.desktop[4061571]: info:    ┃ [5]   online: true,
Sep 15 11:18:03 computer01 lens.desktop[4061571]: info:    ┃ [6]   accessible: true,
Sep 15 11:18:03 computer01 lens.desktop[4061571]: info:    ┃ [7]   disconnected: false
Sep 15 11:18:03 computer01 lens.desktop[4061571]: info:    ┗ [8] }
Sep 15 11:18:33 computer01 lens.desktop[4061571]: info:    ┏ [CLUSTER]: refresh +30s
Sep 15 11:18:33 computer01 lens.desktop[4061571]: info:    ┃ [1] {
Sep 15 11:18:33 computer01 lens.desktop[4061571]: info:    ┃ [2]   id: '1fd3838f862addc1eeb5ce615849c708',
Sep 15 11:18:33 computer01 lens.desktop[4061571]: info:    ┃ [3]   name: 'mycluster',
Sep 15 11:18:33 computer01 lens.desktop[4061571]: info:    ┃ [4]   ready: true,
Sep 15 11:18:33 computer01 lens.desktop[4061571]: info:    ┃ [5]   online: true,
Sep 15 11:18:33 computer01 lens.desktop[4061571]: info:    ┃ [6]   accessible: true,
Sep 15 11:18:33 computer01 lens.desktop[4061571]: info:    ┃ [7]   disconnected: false
Sep 15 11:18:33 computer01 lens.desktop[4061571]: info:    ┗ [8] }
Sep 15 11:18:37 computer01 lens.desktop[4061571]: warn:    ┏ [METRICS-ROUTE]: failed to get metrics for clusterId=1fd3838f862addc1eeb5ce615849c708: Metrics not available +4s
Sep 15 11:18:37 computer01 lens.desktop[4061571]: warn:    ┃ [1] Error: Metrics not available
Sep 15 11:18:37 computer01 lens.desktop[4061571]: warn:    ┃ [2]     at /opt/Lens/resources/app.asar/static/build/main.js:1:404041
Sep 15 11:18:37 computer01 lens.desktop[4061571]: warn:    ┃ [3]     at runMicrotasks (<anonymous>)
Sep 15 11:18:37 computer01 lens.desktop[4061571]: warn:    ┃ [4]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Sep 15 11:18:37 computer01 lens.desktop[4061571]: warn:    ┃ [5]     at async Promise.all (index 0)
Sep 15 11:18:37 computer01 lens.desktop[4061571]: warn:    ┃ [6]     at async /opt/Lens/resources/app.asar/static/build/main.js:1:404789
Sep 15 11:18:37 computer01 lens.desktop[4061571]: warn:    ┃ [7]     at async Object.route (/opt/Lens/resources/app.asar/static/build/main.js:1:396830)
Sep 15 11:18:37 computer01 lens.desktop[4061571]: warn:    ┗ [8]     at async c.route (/opt/Lens/resources/app.asar/static/build/main.js:1:396518)
Sep 15 11:19:03 computer01 lens.desktop[4061571]: info:    ┏ [CLUSTER]: refresh +26s
Sep 15 11:19:03 computer01 lens.desktop[4061571]: info:    ┃ [1] {
Sep 15 11:19:03 computer01 lens.desktop[4061571]: info:    ┃ [2]   id: '1fd3838f862addc1eeb5ce615849c708',
Sep 15 11:19:03 computer01 lens.desktop[4061571]: info:    ┃ [3]   name: 'mycluster',
Sep 15 11:19:03 computer01 lens.desktop[4061571]: info:    ┃ [4]   ready: true,
Sep 15 11:19:03 computer01 lens.desktop[4061571]: info:    ┃ [5]   online: true,
Sep 15 11:19:03 computer01 lens.desktop[4061571]: info:    ┃ [6]   accessible: true,
Sep 15 11:19:03 computer01 lens.desktop[4061571]: info:    ┃ [7]   disconnected: false
Sep 15 11:19:03 computer01 lens.desktop[4061571]: info:    ┗ [8] }
```

Most of the messages are info level, so it's not necessary. Its flooding the messages files with lens logs and is impossible to debug other issues due to this.

is it possible to disable log or at least change log level?
Thanks!

**Comment by Nokel81** [comment]
You can set the `LOG_LEVEL` env var to `warn` or even `error` if you would like.
