### ISSUE TITLE
Lens metrics not showing with custom kube-prometheus-stack

### ISSUE THREAD

**Issue by imageschool** [kontena/lens#6541]
**Describe the bug**
- Lens metrics not showing with custom kube-prometheus-stack

**To Reproduce**
1. Server settings - Extension (Lens Metrics) - Disable all three
2. helm Install kube-prometheus-stack (latest)
3. Apply following in helm chart config https://github.com/lensapp/lens/blob/master/troubleshooting/custom-prometheus.md
4. Lens UI not showing any metrics...

**Expected behavior**
Metrics to show up

**Screenshots**
![image](https://user-images.githubusercontent.com/29969006/200796704-3764a2ed-1668-4123-9661-ae7b782f728b.png)
![image](https://user-images.githubusercontent.com/29969006/200796745-795c932f-b8fc-43dd-971a-0f2451612ca6.png)
![image](https://user-images.githubusercontent.com/29969006/200796813-f0d1c2cd-7b93-4d54-a2ad-4f2d373e9f38.png)

**Environment (please complete the following information):**
- Lens: 2022.11.81921-latest
Extension API: 6.1.17
Electron: 19.1.4
Chrome: 102.0.5005.167
Node: 16.14.2
© 2022 Mirantis, Inc.
- OS: OSX
- Installation method (e.g. snap or AppImage in Linux): dmg for M1

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**

**Comment by trallnag** [comment]
Did it work before?

**Comment by imageschool** [comment]
> Did it work before?

@trallnag 
It worked with default Lens metrics before but in the latest version, both default ones (lens metrics) and custom ones (kube-prometheus-stack) do not work...

Currently, we are only interested in the custom (kube-prometheus-stack) tho!

**Comment by Nokel81** [comment]
What metrics provider is configured for that cluster?

**Comment by imageschool** [comment]
> 
@Nokel81 
You mean like metric server & node exporter?

I am using `k8s.gcr.io/metrics-server/metrics-server:v0.6.1` and `quay.io/prometheus/node-exporter:v1.3.1` (prometheus-node-exporters from kube-prometheus-stack)

**Comment by Nokel81** [comment]
No I mean what is the setting within Lens under cluster preferences > Metrics for "Promtheus provider"

**Comment by imageschool** [comment]
> No I mean what is the setting within Lens under cluster preferences > Metrics for "Promtheus provider"

Oh, I chose Prometheus Operator and used headless service of prometheus as below.
(Also tried kube-prometheus-stack-prometheus)
![image](https://user-images.githubusercontent.com/29969006/202064040-8bffb0a4-e1c9-49f2-b9c4-ba9e29a2fc1c.png)

**Comment by Nokel81** [comment]
If you installed prometheus from Helm you should probably use the "Prometheus Helm" provider. But until #6576 is merged and released it will be hard for us to diagnose why it isn't showing up.

**Comment by imageschool** [comment]
> If you installed prometheus from Helm you should probably use the "Prometheus Helm" provider. But until #6576 is merged and released it will be hard for us to diagnose why it isn't showing up.

I will try that tomorrow and let you know!

Also Really looking forward to seeing the new merge!

**Comment by imageschool** [comment]
> If you installed prometheus from Helm you should probably use the "Prometheus Helm" provider. But until #6576 is merged and released it will be hard for us to diagnose why it isn't showing up.

Switched to Helm, but no changes.

**Comment by imageschool** [comment]
@Nokel81 I have the following error stack and the cause seems to be a socket hang up error 

```
[0] warn:    ┏ [METRICS-ROUTE]: failed to get metrics for clusterId=bf5a8d06fa892a342094edf8835c4b42: Metrics not available +6ms
[0] warn:    ┃ [ 1] Error: Metrics not available
[0] warn:    ┃ [ 2]     at loadMetricHelper (/Users/XXXX/Downloads/lens-6.2.0/static/build/main.js:45121:31)
[0] warn:    ┃ [ 3]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[0] warn:    ┃ [ 4]     at async Promise.all (index 0)
[0] warn:    ┃ [ 5]     at async /Users/XXXX/Downloads/lens-6.2.0/static/build/main.js:45162:32
[0] warn:    ┃ [ 6]     at async Object.route (/Users/XXXX/Downloads/lens-6.2.0/static/build/main.js:43974:32)
[0] warn:    ┃ [ 7]     at async Router.route (/Users/XXXX/Downloads/lens-6.2.0/static/build/main.js:44247:9)
[0] warn:    ┃ [ 8]     at async LensProxy.handleRequest (/Users/XXXX/Downloads/lens-6.2.0/static/build/main.js:41912:9)
[0] warn:    ┃ [ 9] Cause: RequestError: Error: socket hang up
[0] warn:    ┃ [10]     RequestError: Error: socket hang up
[0] warn:    ┃ [11]         at new RequestError (/Users/XXXX/Downloads/lens-6.2.0/node_modules/request-promise-core/lib/errors.js:14:15)
[0] warn:    ┃ [12]         at plumbing.callback (/Users/XXXX/Downloads/lens-6.2.0/node_modules/request-promise-core/lib/plumbing.js:87:29)
[0] warn:    ┃ [13]         at Request.RP$callback [as _callback] (/Users/XXXX/Downloads/lens-6.2.0/node_modules/request-promise-core/lib/plumbing.js:46:31)
[0] warn:    ┃ [14]         at self.callback (/Users/XXXX/Downloads/lens-6.2.0/node_modules/request/request.js:185:22)
[0] warn:    ┃ [15]         at Request.emit (node:events:526:28)
[0] warn:    ┃ [16]         at Request.emit (node:domain:475:12)
[0] warn:    ┃ [17]         at Request.onRequestError (/Users/XXXX/Downloads/lens-6.2.0/node_modules/request/request.js:877:8)
[0] warn:    ┃ [18]         at ClientRequest.emit (node:events:526:28)
[0] warn:    ┃ [19]         at ClientRequest.emit (node:domain:475:12)
[0] warn:    ┃ [20]         at Socket.socketOnEnd (node:_http_client:466:9) {
[0] warn:    ┃ [21]       cause: Error: socket hang up
[0] warn:    ┃ [22]           at connResetException (node:internal/errors:691:14)
[0] warn:    ┃ [23]           at Socket.socketOnEnd (node:_http_client:466:23)
[0] warn:    ┃ [24]           at Socket.emit (node:events:538:35)
[0] warn:    ┃ [25]           at Socket.emit (node:domain:475:12)
[0] warn:    ┃ [26]           at endReadableNT (node:internal/streams/readable:1345:12)
[0] warn:    ┃ [27]           at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
[0] warn:    ┃ [28]         code: 'ECONNRESET'
[0] warn:    ┃ [29]       },
[0] warn:    ┃ [30]       error: Error: socket hang up
[0] warn:    ┃ [31]           at connResetException (node:internal/errors:691:14)
[0] warn:    ┃ [32]           at Socket.socketOnEnd (node:_http_client:466:23)
[0] warn:    ┃ [33]           at Socket.emit (node:events:538:35)
[0] warn:    ┃ [34]           at Socket.emit (node:domain:475:12)
[0] warn:    ┃ [35]           at endReadableNT (node:internal/streams/readable:1345:12)
[0] warn:    ┃ [36]           at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
[0] warn:    ┃ [37]         code: 'ECONNRESET'
[0] warn:    ┃ [38]       },
[0] warn:    ┃ [39]       options: {
[0] warn:    ┃ [40]         timeout: 0,
[0] warn:    ┃ [41]         resolveWithFullResponse: false,
[0] warn:    ┃ [42]         json: true,
[0] warn:    ┃ [43]         method: 'POST',
[0] warn:    ┃ [44]         form: {
[0] warn:    ┃ [45]           query: 'sum(node_memory_MemTotal_bytes * on (pod,namespace) group_left(node) kube_pod_info{node=~"lambda-server|lambda-server-2|lambda-server-cpu-1"} - (node_memory_MemFree_bytes * on (pod,namespace) group_left(node) kube_pod_info{node=~"lambda-server|lambda-server-2|lambda-server-cpu-1"} + node_memory_Buffers_bytes * on (pod,namespace) group_left(node) kube_pod_info{node=~"lambda-server|lambda-server-2|lambda-server-cpu-1"} + node_memory_Cached_bytes * on (pod,namespace) group_left(node) kube_pod_info{node=~"lambda-server|lambda-server-2|lambda-server-cpu-1"}))',
[0] warn:    ┃ [46]           start: '1668735048',
[0] warn:    ┃ [47]           end: '1668738648',
[0] warn:    ┃ [48]           step: '60',
[0] warn:    ┃ [49]           kubernetes_namespace: ''
[0] warn:    ┃ [50]         },
[0] warn:    ┃ [51]         headers: { Host: 'bf5a8d06fa892a342094edf8835c4b42.localhost:53298' },
[0] warn:    ┃ [52]         uri: 'http://localhost:53298/api-kube/api/v1/namespaces/prometheus/services/prometheus-operated:9090/proxy/api/v1/query_range',
[0] warn:    ┃ [53]         callback: [Function: RP$callback],
[0] warn:    ┃ [54]         transform: undefined,
[0] warn:    ┃ [55]         simple: true,
[0] warn:    ┃ [56]         transform2xxOnly: false
[0] warn:    ┃ [57]       },
warn:    ┃ [58]       response: undefined
[0] warn:    ┃ [59]     }
[0] warn:    ┃ [60] Cause: Error: socket hang up
[0] warn:    ┃ [61]     Error: socket hang up
[0] warn:    ┃ [62]         at connResetException (node:internal/errors:691:14)
[0] warn:    ┃ [63]         at Socket.socketOnEnd (node:_http_client:466:23)
[0] warn:    ┃ [64]         at Socket.emit (node:events:538:35)
[0] warn:    ┃ [65]         at Socket.emit (node:domain:475:12)
[0] warn:    ┃ [66]         at endReadableNT (node:internal/streams/readable:1345:12)
[0] warn:    ┃ [67]         at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
[0] warn:    ┃ [68]       code: 'ECONNRESET'
[0] warn:    ┗ [69]     }
```

**Comment by imageschool** [comment]
@Nokel81 Would you have a look at the error stack when you are free!

**Comment by vsychov** [comment]
I'm having same error, but with only one cluster that deployed to GKE, same error message `Error: socket hang up`, prometheus installed via operator.

**Comment by anonimnor** [comment]
same here, - not working Lens metrics with Lens prometheus, neither with latest kube-prometheus-stack, - @imageschool @vsychov how do you people got these errors, where did you get'em from? where do I click.. )

after TONS of googling I assumes that Lens and Prometheus projects both updated so quickly Lens just cannot keep up parsing all those Prometheus logging format changes somehow. So downgrading to old Prometheuses often fixes that, (probably accompanied by downgrading Lens also, but not necessarily - they try their best to store/keep all the previos Prometheuses'es fixes I guess). 

By googling I sees sometimes it helps to mess with "Metrics" settings a lot: auto-detect, helm, lens, operator, set service address manually (auto-detection is seldom) etc. but greatly depending on the Prometheus and Lens versions used (and Cluster configuration also).

community would greatly benefit if someone please pleeease describe the exact step-by-step applying of this here https://github.com/lensapp/lens/blob/master/troubleshooting/custom-prometheus.md curious fixes.
they are way confusing as for me, where to click.. how to where wha?.. ))

**Comment by imageschool** [comment]
@anonimnor to get the same error stack, I built it (following [https://docs.k8slens.dev/contributing/development/](https://docs.k8slens.dev/contributing/development/)) and run it on my own.

Or you can also run your Lens with the following command (on Mac) `DEBUG_PROXY=true /Applications/Lens.app/Contents/MacOS/Lens`

**Comment by imageschool** [comment]
@anonimnor To apply the custom Prometheus, you have to include the following in the Helm Chart.

```
kubelet:
  serviceMonitor:
    metricRelabelings:
    - action: replace
      sourceLabels:
      - node
      targetLabel: instance

prometheus-node-exporter:
  prometheus:
    monitor:
      metricRelabelings:
      - action: replace
        regex: (.*)
        replacement: $1
        sourceLabels:
        - __meta_kubernetes_pod_node_name
        targetLabel: kubernetes_node
```
Lens - Cluster Setting - Metrics, include the following.
![image](https://user-images.githubusercontent.com/29969006/205213671-a1b02111-42b3-4536-b59b-9a7237f6042d.png)

@vsychov @anonimnor If it still doesn't work after applying the above, try the below. 

I use the latest Lens IDE & `kube-prometheus-stack v41.9.1`

The first thing you can try for the `kube-prometheus-stack` Helm Chart is enabling the host network and see if it works.

```
prometheus:
  prometheusSpec:
     hostNetwork: true # this

prometheus-node-exporter:
 hostNetwork: true # and this
```

After setting them to true I was able to see all the metrics in worker nodes (on-prem) but still could not see the master node metrics (master node on AWS EC2). 

Investigating further, we ended up finding a network plugin (flannel) not correctly inserting the VXLAN interface (flannel.1) into the master node.

After restarting the canal on our master node then I put the host network back to false and everything was working correctly!

![image](https://user-images.githubusercontent.com/29969006/205213869-cf03d222-0a08-4e97-81d0-d2fc4bffbab5.png)

**Comment by flixx** [comment]
For us the issue was that the Kubernetes API Server was not allowed to reach prometheus.

Since lens is relying on the proxy-functionality of the service API, the API server must be allowed to reach the prometheus pod on port 9090 (or whatever port prometheus is running on inside the pod)

To debug stuff I was using this (adjust namespace/service on copy):
```
kubectl get --raw /api/v1/namespaces/monitoring-system/services/prometheus-server:80/proxy/
```
This was giving me this error after 60s or so:

```
Error from server (ServiceUnavailable): error trying to reach service: dial tcp 172.35.2.218:9090: connect: connection timed out
```
I am using the EKS terraform module. So I added this inside the module block:

```
  node_security_group_additional_rules = {
    prometheus_service_from_api_server = {
      description                   = "With this rule, the API server would be allowed to reach prometheus port. With this metrics work in lens"
      protocol                      = "TCP"
      from_port                     = 9090
      to_port                       = 9090
      type                          = "ingress"
      source_cluster_security_group = true
    }
  }
```

But of curse how exactly this rule is added depends on the setup...

With this extra-rule most metrics work (I could not get the Metrics on the cluster Tab working yet through)


Felix

**Comment by azunna1** [comment]
It might also be a permissions issue with cloud provider clusters. For example with GKE you need `container.services.proxy` permissions for lens to display metrics

**Comment by sidpremkumar** [comment]
> For us the issue was that the Kubernetes API Server was not allowed to reach prometheus.
> 
> Since lens is relying on the proxy-functionality of the service API, the API server must be allowed to reach the prometheus pod on port 9090 (or whatever port prometheus is running on inside the pod)
> 
> To debug stuff I was using this (adjust namespace/service on copy):
> 
> ```
> kubectl get --raw /api/v1/namespaces/monitoring-system/services/prometheus-server:80/proxy/
> ```
> 
> This was giving me this error after 60s or so:
> 
> ```
> Error from server (ServiceUnavailable): error trying to reach service: dial tcp 172.35.2.218:9090: connect: connection timed out
> ```
> 
> I am using the EKS terraform module. So I added this inside the module block:
> 
> ```
>   node_security_group_additional_rules = {
>     prometheus_service_from_api_server = {
>       description                   = "With this rule, the API server would be allowed to reach prometheus port. With this metrics work in lens"
>       protocol                      = "TCP"
>       from_port                     = 9090
>       to_port                       = 9090
>       type                          = "ingress"
>       source_cluster_security_group = true
>     }
>   }
> ```
> 
> But of curse how exactly this rule is added depends on the setup...
> 
> With this extra-rule most metrics work (I could not get the Metrics on the cluster Tab working yet through)
> 
> Felix

For future devs, as of April 22nd 2024 this is finally was fixed it for me 🐐🙏

**Comment by shrikantbhadane** [comment]
My issue resolved after I selected prometheus operator and address operations/prometheus-operated:9090
