### ISSUE TITLE
Lens Error: could not load extensions: npm WARN config only Use `--omit=dev` to omit dev dependencies from the install

### ISSUE THREAD

**Issue by guettli** [kontena/lens#6554]
**Describe the bug**

I installed Lens via snap on Ubuntu 22.04.

If I run Lens, I get this error:

> Lens Error: could not load extensions: npm WARN config only Use `--omit=dev` to omit dev dependencies from the install

![image](https://user-images.githubusercontent.com/414336/201194295-3b1ff74d-8895-4a05-94ab-74ee1e513027.png)

After that Lens works, but some things are not available (for example logs of pods).

**Environment (please complete the following information):**
- Lens Version:  Lens-2022.11.92045-latest.amd64.snap 
- OS: Ubuntu 22.04
- Installation method: snap

**Logs:**

/home/guettli/.npm/_logs/2022-11-10T20_00_09_201Z-debug-0.log:

```
1313 verbose type range
1314 verbose stack regenerator-runtime: No matching version found for regenerator-runtime@^0.13.10.
1314 verbose stack     at module.exports (/opt/Lens/resources/app.asar/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:209:23)
1314 verbose stack     at RegistryFetcher.manifest (/opt/Lens/resources/app.asar/node_modules/npm/node_modules/pacote/lib/registry.js:125:22)
1314 verbose stack     at async Promise.all (index 0)
1314 verbose stack     at async [buildDepStep] (/opt/Lens/resources/app.asar/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1046:5)
1314 verbose stack     at async Arborist.buildIdealTree (/opt/Lens/resources/app.asar/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:211:7)
1314 verbose stack     at async Promise.all (index 1)
1314 verbose stack     at async Arborist.reify (/opt/Lens/resources/app.asar/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:153:5)
1314 verbose stack     at async Install.exec (/opt/Lens/resources/app.asar/node_modules/npm/lib/commands/install.js:145:5)
1314 verbose stack     at async module.exports (/opt/Lens/resources/app.asar/node_modules/npm/lib/cli.js:78:5)
1315 verbose cwd /home/guettli/.config/Lens
1316 verbose Linux 5.15.0-52-generic
1317 verbose node v16.14.2
1318 verbose npm  v8.19.2
1319 error code ETARGET
1320 error notarget No matching version found for regenerator-runtime@^0.13.10.
1321 error notarget In most cases you or one of your dependencies are requesting
1321 error notarget a package version that doesn't exist.
1322 verbose exit 1
1323 timing npm Completed in 1876ms
1324 verbose unfinished npm timer reify 1668110409287
1325 verbose unfinished npm timer reify:loadTrees 1668110409289
1326 verbose code 1
```

**Comment by guettli** [comment]
It works now. I hand Lens installed twice. An old version via dpkg, the new via snap. I removed both and installed the dpkg again, and now it works.
