### ISSUE TITLE
🐛 Cronjob trigger option is missing

### ISSUE THREAD

**Issue by jmartins-sh** [kontena/lens#6600]
**Describe the bug**
Previous versions of Lens had the option to trigger the cronjobs without waiting for the scheduled time. 

**To Reproduce**
1. Go to **Workloads** -> **Cronjobs**
2. Left Click on the three dots on the right on the cronjob list.

**Expected behavior**
An option to trigger the cronjob.

**Screenshots**
![New version Cronjob Screen (with bug)](https://user-images.githubusercontent.com/16046723/202473534-bbce7358-d49d-4c19-967b-677ccf775aff.png)| 
|:--:| 
| *New version Cronjob Screen (with bug)* |

![Previous version Cronjob Screen (without bug)](https://user-images.githubusercontent.com/16046723/202473752-c78ca182-0548-405e-9a4b-1637f80d8917.png)| 
|:--:| 
| *Previous version Cronjob Screen (without bug)* |

![Previsous version](https://user-images.githubusercontent.com/16046723/202474052-7d2a68b9-3e77-4fa0-91b4-e83bd8d6dbb7.png)| 
|:--:| 
| *Previsous version* |

**Environment (please complete the following information):**
- Lens Version: 2022.11.101953-latest
- OS: Windows 10
- Installation method (e.g. snap or AppImage in Linux): Windows x64 (.exe)

**Logs:**
```
(node:21292) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `Lens --trace-deprecation ...` to show where the warning was created)
info:    ▪ [CLUSTER-STORE]: LOADING from  ... +0ms
info:    ▪ [CLUSTER-STORE]: LOADED from C:\Users\proxys\AppData\Roaming\Lens\lens-cluster-store.json +787ms
info:    ▪ 🔌 Starting LensProxy +5ms
info:    ▪ [LENS-PROXY]: Proxy server has started at 127.0.0.1:59107 +93ms
info:    ▪ 🔎 Testing LensProxy connection ... +1ms
info:    ▪ [USER-STORE]: LOADING from  ... +12ms
info:    ▪ [USER-STORE]: LOADED from C:\Users\proxys\AppData\Roaming\Lens\lens-user-store.json +28ms
info:    ▪ ⚡ LensProxy connection OK +66ms
info:    ▪ [CREATE-ELECTRON-WINDOW]: Loading content for window "splash" from file: D:\Program Files\Lens\resources\static\splash.html... +39ms
info:    ▪ [CREATE-ELECTRON-WINDOW]: Window "splash" loaded +784ms
info:    ▪ [MENU]: autoUpdateEnabled=true +42ms
info:    ▪ [EXTENSIONS-STORE]: LOADING from  ... +5ms
info:    ▪ [EXTENSIONS-STORE]: LOADED from C:\Users\proxys\AppData\Roaming\Lens\lens-extensions.json +3ms
info:    ▪ [FILESYSTEM-PROVISIONER-STORE]: LOADING from  ... +4ms
info:    ▪ [FILESYSTEM-PROVISIONER-STORE]: LOADED from C:\Users\proxys\AppData\Roaming\Lens\lens-filesystem-provisioner-store.json +7ms
info:    ▪ [WEBLINK-STORE]: LOADING from  ... +12ms
info:    ▪ [WEBLINK-STORE]: LOADED from C:\Users\proxys\AppData\Roaming\Lens\lens-weblink-store.json +13ms
info:    ▪ 📟 Setting protocol client for lens:// +15ms
info:    ▪ 📟 Protocol client register succeeded ✅ +3ms
info:    ▪ 🧩 Initializing extensions +4ms
info:    ▪ 🐚 Syncing shell environment +4ms
info:    ▪ [HOTBAR-STORE]: LOADING from  ... +102ms
info:    ▪ [HOTBAR-STORE]: LOADED from C:\Users\proxys\AppData\Roaming\Lens\lens-hotbar-store.json +6ms
info:    ▪ [EXTENSION-DISCOVERY] loading extensions from C:\Users\proxys\AppData\Roaming\Lens +119ms
info:    ▪ [EXTENSION-INSTALLER] installing dependencies at C:\Users\proxys\AppData\Roaming\Lens +113ms
info:    ▪ [EXTENSION-INSTALLER] dependencies installed at C:\Users\proxys\AppData\Roaming\Lens +1s
info:    ▪ [EXTENSION-DISCOVERY] watching extension add/remove in C:\Users\proxys\.k8slens\extensions +2ms
info:    ▪ [CLOUD-PROVIDER-SYNC-EXTENSION] activated +28ms
info:    ▪ [LENS-DESKTOP-KUBE] onActivate +378ms
info:    ▪ [EXTENSION-STORE-T]: LOADING from  ... +1ms
info:    ▪ [EXTENSION-STORE-T]: LOADED from C:\Users\proxys\AppData\Roaming\Lens\extension-store\lens-desktop-kube-lens-extension\ldk-store.json +1ms
License main extension activated
Native extraction module not loaded, msgpackr will still run, but with decreased performance. Cannot find module 'msgpackr-extract'
[ELECTRON-SYNC-STORE]: 2022-11-17T14:37:46.274Z - select-space-store ~ ElectronSyncStore:initialize, path C:\Users\proxys\AppData\Roaming\Lens\extension-store\lenscloud-lens-extension\select-space-store.json
[ELECTRON-SYNC-STORE]: 2022-11-17T14:37:46.274Z - startup-store ~ ElectronSyncStore:initialize, path C:\Users\proxys\AppData\Roaming\Lens\extension-store\lenscloud-lens-extension\startup-store.json
info:    ▪ [EXTENSION-STORE-T]: LOADING from  ... +501ms
info:    ▪ [EXTENSION-STORE-T]: LOADED from C:\Users\proxys\AppData\Roaming\Lens\extension-store\oci-image-lens-extension\security-preferences-store.json +2ms
info:    ▪ [SUPPORT-EXTENSION] activated +3ms
info:    ▪ [EXTENSION-STORE-T]: LOADING from  ... +2ms
info:    ▪ [EXTENSION-STORE-T]: LOADED from C:\Users\proxys\AppData\Roaming\Lens\extension-store\survey-lens-extension\preferences-store.json +2ms
telemetry main extension activated
info:    ▪ [EXTENSION-STORE-T]: LOADING from  ... +130ms
info:    ▪ [EXTENSION-STORE-T]: LOADED from C:\Users\proxys\AppData\Roaming\Lens\extension-store\telemetry-lens-extension\preferences-store.json +1ms
info:    ▪ [TOUR-EXTENSION] activated +2ms
info:    ▪ [EXTENSION-STORE-T]: LOADING from  ... +1ms
info:    ▪ [EXTENSION-STORE-T]: LOADED from C:\Users\proxys\AppData\Roaming\Lens\extension-store\tour-lens-extension\tip-store.json +2ms
info:    ▪ [STORE]: SAVING C:\Users\proxys\AppData\Roaming\Lens\lens-extensions.json +14ms
info:    ▪ [CREATE-ELECTRON-WINDOW]: Loading content for window "first-application-window" from url: http://localhost:59107... +103ms
[ELECTRON-SYNC-STORE]: 2022-11-17T14:37:46.954Z - select-space-store ~ ElectronSyncStore:initialize, model {"3b0925b6-aab5-46f2-993c-2a5248493d93":{"spaceId":"offline","isPersonalSpace":true,"spaceName":"offline"}}
[ELECTRON-SYNC-STORE]: 2022-11-17T14:37:46.955Z - select-space-store ~ ipcListen
[ELECTRON-SYNC-STORE]: 2022-11-17T14:37:46.957Z - startup-store ~ ElectronSyncStore:initialize, model {"skipSignup":false}
[ELECTRON-SYNC-STORE]: 2022-11-17T14:37:46.958Z - startup-store ~ ipcListen
info:    ▪ [EXTENSION-STORE-T]: LOADING from  ... +121ms
info:    ▪ [EXTENSION-STORE-T]: LOADED from C:\Users\proxys\AppData\Roaming\Lens\extension-store\lenscloud-lens-extension\local-metadata-store.json +4ms
info:    ▪ [EXTENSION-STORE-T]: LOADING from  ... +2ms
info:    ▪ [EXTENSION-STORE-T]: LOADED from C:\Users\proxys\AppData\Roaming\Lens\extension-store\lenscloud-lens-extension\release-notes-store.json +3ms
info:    ▪ [EXTENSION-STORE-T]: LOADING from  ... +1ms
info:    ▪ [EXTENSION-STORE-T]: LOADED from C:\Users\proxys\AppData\Roaming\Lens\extension-store\lenscloud-lens-extension\grace-period-store.json +2ms
info:    ▪ [EXTENSION-STORE-T]: LOADING from  ... +1ms
info:    ▪ [EXTENSION-STORE-T]: LOADED from C:\Users\proxys\AppData\Roaming\Lens\extension-store\lenscloud-lens-extension\spaces-settings-store.json +2ms
info:    ▪ [LENS-SPACES-EXTENSION]: 11/17/2022, 11:37:47 AM Broadcasted spaces change to SpacesListener on renderer +136ms
warn:    ▪ [LENS-SPACES-EXTENSION]: 11/17/2022, 11:37:47 AM No spaces in SpaceSyncer disposeSpacesReaction, not changing selected space. +1ms
info:    ┏ [IPC-RENDERER]: adding extension listener +5ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'disconnectClusterEvent',
info:    ┃ [3]   extension: { name: 'lenscloud-lens-extension', version: '6.1.19-latest.1668110585058' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension listener +3ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'deleteOneSpace',
info:    ┃ [3]   extension: { name: 'lenscloud-lens-extension', version: '6.1.19-latest.1668110585058' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension handler +1ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'forceRefreshToken',
info:    ┃ [3]   extension: { name: 'lenscloud-lens-extension', version: '6.1.19-latest.1668110585058' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension handler +1ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'disconnectProxiedClustersEvent',
info:    ┃ [3]   extension: { name: 'lenscloud-lens-extension', version: '6.1.19-latest.1668110585058' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension handler +42ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'resetSpaceSyncerEvent',
info:    ┃ [3]   extension: { name: 'lenscloud-lens-extension', version: '6.1.19-latest.1668110585058' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension handler +0ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'stopTokenRefresherEvent',
info:    ┃ [3]   extension: { name: 'lenscloud-lens-extension', version: '6.1.19-latest.1668110585058' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension handler +1ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'getSpaceSyncerSpaces',
info:    ┃ [3]   extension: { name: 'lenscloud-lens-extension', version: '6.1.19-latest.1668110585058' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension listener +0ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'loadRemoteSpacesClusters',
info:    ┃ [3]   extension: { name: 'lenscloud-lens-extension', version: '6.1.19-latest.1668110585058' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension listener +1ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'createOneSpace',
info:    ┃ [3]   extension: { name: 'lenscloud-lens-extension', version: '6.1.19-latest.1668110585058' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension listener +0ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'leaveOneSpace',
info:    ┃ [3]   extension: { name: 'lenscloud-lens-extension', version: '6.1.19-latest.1668110585058' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension listener +1ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'selectSpace',
info:    ┃ [3]   extension: { name: 'lenscloud-lens-extension', version: '6.1.19-latest.1668110585058' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension handler +0ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'proxyInfo',
info:    ┃ [3]   extension: { name: 'lenscloud-lens-extension', version: '6.1.19-latest.1668110585058' }
info:    ┗ [4] }
info:    ▪ [LENS-SPACES-EXTENSION]: 11/17/2022, 11:37:47 AM Lens Spaces Extension activated +1ms
info:    ┏ [IPC-RENDERER]: adding extension handler +0ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'vulnerabilities:db:import',
info:    ┃ [3]   extension: { name: 'oci-image-lens-extension', version: '6.1.19-latest.1668110585058' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension handler +0ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'vulnerabilities:settings:open',
info:    ┃ [3]   extension: { name: 'oci-image-lens-extension', version: '6.1.19-latest.1668110585058' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension handler +1ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'vulnerabilities:db:export',
info:    ┃ [3]   extension: { name: 'oci-image-lens-extension', version: '6.1.19-latest.1668110585058' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension handler +0ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'vulnerabilities:db:info',
info:    ┃ [3]   extension: { name: 'oci-image-lens-extension', version: '6.1.19-latest.1668110585058' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension handler +1ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'vulnerabilities:clear',
info:    ┃ [3]   extension: { name: 'oci-image-lens-extension', version: '6.1.19-latest.1668110585058' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension handler +1ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'vulnerabilities:scan:image',
info:    ┃ [3]   extension: { name: 'oci-image-lens-extension', version: '6.1.19-latest.1668110585058' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension handler +0ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'vulnerabilities:scan:storage',
info:    ┃ [3]   extension: { name: 'oci-image-lens-extension', version: '6.1.19-latest.1668110585058' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension handler +1ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'vulnerabilities:scan:enabled',
info:    ┃ [3]   extension: { name: 'oci-image-lens-extension', version: '6.1.19-latest.1668110585058' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension handler +1ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'image:manifest',
info:    ┃ [3]   extension: { name: 'oci-image-lens-extension', version: '6.1.19-latest.1668110585058' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension handler +1ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'image:tag',
info:    ┃ [3]   extension: { name: 'oci-image-lens-extension', version: '6.1.19-latest.1668110585058' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension handler +1ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'image:manifest-list',
info:    ┃ [3]   extension: { name: 'oci-image-lens-extension', version: '6.1.19-latest.1668110585058' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension handler +2ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'image:history',
info:    ┃ [3]   extension: { name: 'oci-image-lens-extension', version: '6.1.19-latest.1668110585058' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension handler +1ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'image:vulnerabilities',
info:    ┃ [3]   extension: { name: 'oci-image-lens-extension', version: '6.1.19-latest.1668110585058' }
info:    ┗ [4] }
info:    ▪ [OCI-IMAGE] activated +1ms
info:    ▪ [LENS-SPACES-EXTENSION]: (from:TokenRefresher) 11/17/2022, 11:37:47 AM Detect token expires in 28800s (28800105.000019073ms), set refresh interval. +696ms
info:    ▪ [LENS-SPACES-EXTENSION]: (from:TokenRefresher) 11/17/2022, 11:37:47 AM Start token refresh iterator... scheduled next refresh 11/17/2022, 7:28:12 PM +4ms
info:    ▪ [LENS-SPACES-EXTENSION]: 11/17/2022, 11:37:48 AM isLensCloudStatusOk on initialization returns true +156ms
info:    ┏ [IPC-RENDERER]: adding extension handler +2s
info:    ┃ [1] {
info:    ┃ [2]   channel: 'vm:enabled',
info:    ┃ [3]   extension: { name: 'lens-desktop-kube-lens-extension', version: '6.1.19-latest.1668110585058' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension handler +1ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'vm:start',
info:    ┃ [3]   extension: { name: 'lens-desktop-kube-lens-extension', version: '6.1.19-latest.1668110585058' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension handler +1ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'vm:stop',
info:    ┃ [3]   extension: { name: 'lens-desktop-kube-lens-extension', version: '6.1.19-latest.1668110585058' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension handler +1ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'vm:reset',
info:    ┃ [3]   extension: { name: 'lens-desktop-kube-lens-extension', version: '6.1.19-latest.1668110585058' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension handler +1ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'vm:delete',
info:    ┃ [3]   extension: { name: 'lens-desktop-kube-lens-extension', version: '6.1.19-latest.1668110585058' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension handler +0ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'vm:download:pause',
info:    ┃ [3]   extension: { name: 'lens-desktop-kube-lens-extension', version: '6.1.19-latest.1668110585058' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension handler +2ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'vm:connectAndNavigateLdkCluster',
info:    ┃ [3]   extension: { name: 'lens-desktop-kube-lens-extension', version: '6.1.19-latest.1668110585058' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension handler +1ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'vm:download:resume',
info:    ┃ [3]   extension: { name: 'lens-desktop-kube-lens-extension', version: '6.1.19-latest.1668110585058' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension handler +1ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'vm:download:cancel',
info:    ┃ [3]   extension: { name: 'lens-desktop-kube-lens-extension', version: '6.1.19-latest.1668110585058' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension handler +1ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'vm:create',
info:    ┃ [3]   extension: { name: 'lens-desktop-kube-lens-extension', version: '6.1.19-latest.1668110585058' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension handler +1ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'vm:state:created',
info:    ┃ [3]   extension: { name: 'lens-desktop-kube-lens-extension', version: '6.1.19-latest.1668110585058' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension handler +0ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'vm:profiles:get',
info:    ┃ [3]   extension: { name: 'lens-desktop-kube-lens-extension', version: '6.1.19-latest.1668110585058' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension handler +1ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'k0s:versions:get',
info:    ┃ [3]   extension: { name: 'lens-desktop-kube-lens-extension', version: '6.1.19-latest.1668110585058' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension handler +0ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'extension:enable',
info:    ┃ [3]   extension: { name: 'lens-desktop-kube-lens-extension', version: '6.1.19-latest.1668110585058' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension handler +1ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'vm:cluster:active',
info:    ┃ [3]   extension: { name: 'lens-desktop-kube-lens-extension', version: '6.1.19-latest.1668110585058' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension handler +0ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'vm:cluster:isLdkClusterPath',
info:    ┃ [3]   extension: { name: 'lens-desktop-kube-lens-extension', version: '6.1.19-latest.1668110585058' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension handler +1ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'vm:cluster:open',
info:    ┃ [3]   extension: { name: 'lens-desktop-kube-lens-extension', version: '6.1.19-latest.1668110585058' }
info:    ┗ [4] }
info:    ┏ [IPC-RENDERER]: adding extension handler +0ms
info:    ┃ [1] {
info:    ┃ [2]   channel: 'vm:os:compatibility',
info:    ┃ [3]   extension: { name: 'lens-desktop-kube-lens-extension', version: '6.1.19-latest.1668110585058' }
info:    ┗ [4] }
warn:    ▪ [LENS-DESKTOP-KUBE] failed to register cli commands: Error: Cannot find module '../../cli-lens-extension/dist/main.js'
Require stack:
- C:\Users\proxys\AppData\Roaming\Lens\node_modules\lens-desktop-kube-lens-extension\dist\main.js
- D:\Program Files\Lens\resources\app.asar\static\build\main.js
-
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at n._resolveFilename (node:electron/js2c/browser_init:245:1105)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at 73287 (C:\Users\proxys\AppData\Roaming\Lens\node_modules\lens-desktop-kube-lens-extension\dist\main.js:2:1321121)
    at n (C:\Users\proxys\AppData\Roaming\Lens\node_modules\lens-desktop-kube-lens-extension\dist\main.js:2:1502746)
    at C:\Users\proxys\AppData\Roaming\Lens\node_modules\lens-desktop-kube-lens-extension\dist\main.js:2:938693
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [Array]
} +91ms
info:    ▪ [EXTENSION]: enabled cloud-provider-sync-extension@6.1.19-latest.1668110585058 +10ms
info:    ▪ [EXTENSION]: enabled lens-desktop-kube-lens-extension@6.1.19-latest.1668110585058 +0ms
info:    ▪ [EXTENSION]: enabled lens-license-extension@6.1.19-latest.1668110585058 +1ms
info:    ▪ [EXTENSION]: enabled lenscloud-lens-extension@6.1.19-latest.1668110585058 +0ms
info:    ▪ [EXTENSION]: enabled oci-image-lens-extension@6.1.19-latest.1668110585058 +0ms
info:    ▪ [EXTENSION]: enabled support-lens-extension@6.1.19-latest.1668110585058 +1ms
info:    ▪ [EXTENSION]: enabled survey-lens-extension@6.1.19-latest.1668110585058 +0ms
info:    ▪ [EXTENSION]: enabled telemetry-lens-extension@6.1.19-latest.1668110585058 +0ms
info:    ▪ [EXTENSION]: enabled tour-lens-extension@6.1.19-latest.1668110585058 +0ms
info:    ▪ [CREATE-ELECTRON-WINDOW]: Window "first-application-window" loaded +513ms
[ELECTRON-SYNC-STORE]: 2022-11-17T14:37:52.141Z - select-space-store ~ ipc electron-sync-store:renderer:initialize:select-space-store received
[ELECTRON-SYNC-STORE]: 2022-11-17T14:37:52.142Z - select-space-store ~ ipc electron-sync-store:renderer:initialize:select-space-store received
[ELECTRON-SYNC-STORE]: 2022-11-17T14:37:52.142Z - startup-store ~ ipc electron-sync-store:renderer:initialize:startup-store received
[ELECTRON-SYNC-STORE]: 2022-11-17T14:37:52.204Z - select-space-store ~ ipc electron-sync-store:renderer:initialize:select-space-store received
[ELECTRON-SYNC-STORE]: 2022-11-17T14:37:52.204Z - startup-store ~ ipc electron-sync-store:renderer:initialize:startup-store received
Checking for update
info:    ▪ [KUBECONFIG-SYNC]: starting requested syncs +2s
info:    ┏ [KUBECONFIG-SYNC]: starting sync of file/folder +3ms
info:    ┗ [1] { filePath: 'C:\\Users\\proxys\\AppData\\Roaming\\Lens\\kubeconfigs' }
info:    ┏ [KUBECONFIG-SYNC]: starting sync of file/folder +1ms
info:    ┗ [1] { filePath: 'C:\\Users\\proxys\\.kube' }
Update for version 2022.11.101953-latest is not available (latest version: 2022.11.101953-latest, downgrade is disallowed).
info:    ┏ [CLUSTER]: activate +14s
info:    ┃ [1] {
info:    ┃ [2]   id: '8f6d1a90a1197a29a120d1ec7d9c5a52',
info:    ┃ [3]   name: 'gcp-prod',
info:    ┃ [4]   ready: false,
info:    ┃ [5]   online: false,
info:    ┃ [6]   accessible: false,
info:    ┃ [7]   disconnected: true
info:    ┗ [8] }
info:    ┏ [CLUSTER]: bind events +1ms
info:    ┃ [1] {
info:    ┃ [2]   id: '8f6d1a90a1197a29a120d1ec7d9c5a52',
info:    ┃ [3]   name: 'gcp-prod',
info:    ┃ [4]   ready: false,
info:    ┃ [5]   online: false,
info:    ┃ [6]   accessible: false,
info:    ┃ [7]   disconnected: true
info:    ┗ [8] }
info:    ┏ [CLUSTER]: reconnect +2ms
info:    ┃ [1] {
info:    ┃ [2]   id: '8f6d1a90a1197a29a120d1ec7d9c5a52',
info:    ┃ [3]   name: 'gcp-prod',
info:    ┃ [4]   ready: false,
info:    ┃ [5]   online: false,
info:    ┃ [6]   accessible: false,
info:    ┃ [7]   disconnected: true
info:    ┗ [8] }
info:    ▪ [KUBE-AUTH-PROXY]: found port=59169 +2s
[ELECTRON-SYNC-STORE]: 2022-11-17T14:38:12.533Z - select-space-store ~ ipc electron-sync-store:renderer:initialize:select-space-store received
[ELECTRON-SYNC-STORE]: 2022-11-17T14:38:12.543Z - select-space-store ~ ipc electron-sync-store:renderer:initialize:select-space-store received
[ELECTRON-SYNC-STORE]: 2022-11-17T14:38:12.543Z - startup-store ~ ipc electron-sync-store:renderer:initialize:startup-store received
[ELECTRON-SYNC-STORE]: 2022-11-17T14:38:12.794Z - select-space-store ~ ipc electron-sync-store:renderer:initialize:select-space-store received
[ELECTRON-SYNC-STORE]: 2022-11-17T14:38:12.796Z - startup-store ~ ipc electron-sync-store:renderer:initialize:startup-store received
info:    ▪ [CONTEXT-HANDLER]: using lens as prometheus provider for clusterId=8f6d1a90a1197a29a120d1ec7d9c5a52 +5s
```

**Comment by Nokel81** [comment]
Duplicate of #6572
