### ISSUE TITLE
Lens not starting after installed with snap: ERR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by blafasel42** [kontena/lens#6720]
**Describe the bug**
lens does not start after install with snap.
message: 
(node:109547) electron: Failed to load URL: file:///snap/kontena-lens/185/resources/static/splash.html with error: ERR_FILE_NOT_FOUND

**To Reproduce**
- installed lens on UBUNTU with snap install kontena-lens --classic
- started on command line with kontena-lens
- no window opens, log appears on screen containing ERR_FILE_NOT_FOUND

**Expected behavior**
lens starting, window coming up

**Screenshots**

**Environment (please complete the following information):**
- current snap version 185
- Ubuntu 22.04
- snap --classic

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
$ kontena-lens
(node:109547) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `kontena-lens --trace-deprecation ...` to show where the warning was created)
info:    ▪ [CLUSTER-STORE]: LOADING from  ... +0ms
info:    ▪ [CLUSTER-STORE]: LOADED from /home/gaylord/snap/kontena-lens/185/.config/Lens/lens-cluster-store.json +4ms
info:    ▪ 🔌 Starting LensProxy +2ms
info:    ▪ [LENS-PROXY]: Proxy server has started at 127.0.0.1:39557 +3ms
info:    ▪ 🔎 Testing LensProxy connection ... +0ms
info:    ▪ [USER-STORE]: LOADING from  ... +3ms
info:    ▪ [USER-STORE]: LOADED from /home/gaylord/snap/kontena-lens/185/.config/Lens/lens-user-store.json +9ms
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
info:    ▪ ⚡ LensProxy connection OK +16ms
warn:    ▪ No suitable icon found for task bar. +7ms
info:    ▪ [CREATE-ELECTRON-WINDOW]: Loading content for window "splash" from file: /snap/kontena-lens/185/resources/static/splash.html... +0ms
error:   ┏ [CREATE-ELECTRON-WINDOW]: Failed to load window "splash" +45ms
error:   ┗ [1] { code: -6, desc: 'ERR_FILE_NOT_FOUND' }
(node:109547) electron: Failed to load URL: file:///snap/kontena-lens/185/resources/static/splash.html with error: ERR_FILE_NOT_FOUND
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: ERR_FILE_NOT_FOUND (-6) loading 'file:///snap/kontena-lens/185/resources/static/splash.html'
    at rejectAndCleanup (node:electron/js2c/browser_init:161:7647)
    at EventEmitter.failListener (node:electron/js2c/browser_init:161:7860)
    at EventEmitter.emit (node:events:538:35)
    at EventEmitter.emit (node:domain:475:12)
    at emitter.emit (/snap/kontena-lens/185/resources/app.asar/node_modules/@sentry/electron/main/integrations/electron-breadcrumbs.js:119:20)
(node:109547) UnhandledPromiseRejectionWarning: Error: ERR_FILE_NOT_FOUND (-6) loading 'file:///snap/kontena-lens/185/resources/static/splash.html'
    at rejectAndCleanup (node:electron/js2c/browser_init:161:7647)
    at EventEmitter.failListener (node:electron/js2c/browser_init:161:7860)
    at EventEmitter.emit (node:events:538:35)
    at EventEmitter.emit (node:domain:475:12)
    at emitter.emit (/snap/kontena-lens/185/resources/app.asar/node_modules/@sentry/electron/main/integrations/electron-breadcrumbs.js:119:20)
(node:109547) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
info:    ▪ [CREATE-ELECTRON-WINDOW]: Window "splash" loaded +96ms
^Cinfo:    ▪ [EXTENSIONS-STORE]: LOADING from  ... +4m
info:    ▪ [EXTENSIONS-STORE]: LOADED from /home/gaylord/snap/kontena-lens/185/.config/Lens/lens-extensions.json +1ms
info:    ▪ [FILESYSTEM-PROVISIONER-STORE]: LOADING from  ... +0ms
info:    ▪ [FILESYSTEM-PROVISIONER-STORE]: LOADED from /home/gaylord/snap/kontena-lens/185/.config/Lens/lens-filesystem-provisioner-store.json +1ms
^C
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
kubeconfig worked with older version of lens, also i do not think it is related since the problem is quite obvious.
```

**Additional context**
```
$ ls -l /snap/kontena-lens/185/resources/static/splash.html
ls: cannot access '/snap/kontena-lens/185/resources/static/splash.html': No such file or directory
gaylord@gaylord-XPS-13-9310:~$ ls -l /snap/kontena-lens/185/resources/static/
ls: cannot access '/snap/kontena-lens/185/resources/static/': No such file or directory
gaylord@gaylord-XPS-13-9310:~$ ls -l /snap/kontena-lens/185/resources/
total 983838
-rw-r--r-- 1 root root 1007449759 Dez  1 15:35 app.asar
```

**Comment by iozho** [comment]
I have the same issue - apparently many directories are missing in resource folder.

**Comment by Nokel81** [comment]
Thanks for reporting this. This is a duplicate of https://github.com/lensapp/lens/issues/6697. We have found a fix for this and a new update will be released within a day or so.
