### ISSUE TITLE
Node shell is broken

### ISSUE THREAD

**Issue by jweak** [kontena/lens#7138]
**Describe the bug**
Node shell does not work. It will say "Connecting..." for ever.

**To Reproduce**
1. Connect to a cluster
2. Click on **Nodes**
3. Open Node details
4. Click "Node shell"

**Expected behavior**
A terminal session to the node is opened

**Screenshots**
<img width="467" alt="image" src="https://user-images.githubusercontent.com/774344/218093831-9df2dee8-b4f1-471a-90bb-4e23c11fc1e3.png">

**Environment (please complete the following information):**
- Lens Version: Lens: 2023.2.81050-alpha
- OS: Macos 13.1 (22C65) M1 Silicon
- Installation method (e.g. snap or AppImage in Linux): Alpha channel update

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
debug:   ▪ Set kubectl version 1.23.3 for cluster version v1.23.12+k0s using version map +5s
debug:   ▪ Acquired a lock for 1.23.3 +4ms
error:   ┏ [KUBECTL]: Failed to get a lock for 1.23.3 Lock file is already being held +316ms
error:   ┃ [1] Error: Lock file is already being held
error:   ┃ [2]     at /Applications/Lens.app/Contents/Resources/app.asar/node_modules/proper-lockfile/lib/lockfile.js:68:47
error:   ┃ [3]     at callback (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/graceful-fs/polyfills.js:306:20)
error:   ┃ [4]     at FSReqCallback.oncomplete (node:fs:199:5)
error:   ┗ [5] { code: 'ELOCKED', file: '/Users/jheikka/Library/Application Support/Lens/binaries/kubectl/1.23.3' }
error:   ▪ Failed to ensure kubectl, fallback to the bundled version +0ms
debug:   ▪ [KUBECTL]: Releasing lock for 1.23.3 +13ms
debug:   ▪ [NODE-SHELL]: waiting for node-shell-d300fb1d-040a-4f01-8fc8-49bf4ef19553 to be running +122ms
[CLUSTER-CONNECT] 18 active sockets
info:    ┏ [UNIX-SHELL-ENV]: running against /bin/zsh +1s
info:    ┃ [1] {
info:    ┃ [2]   command: ` '/Applications/Lens.app/Contents/MacOS/Lens' -p '"175c65bc54a145be9aa936e9e5e807d4" + JSON.stringify(process.env) + "175c65bc54a145be9aa936e9e5e807d4"'`,
info:    ┃ [3]   shellArgs: [ '-l', '-i' ]
info:    ┗ [4] }
error:   ┏ [SHELL-SESSION]: failed to open a node shell request to https://127.0.0.1:55342/api-kube/api/v1/nodes/lens-desktop-kube failed, reason: Hostname/IP does not match certificate's altnames: Host: 70d4025be74fd345d774947ee7c205f9.localhost. is not in the cert's altnames: DNS:*.lens.app, DNS:lens.app, DNS:localhost, IP Address:127.0.0.1 +5ms
error:   ┃ [ 1] d: request to https://127.0.0.1:55342/api-kube/api/v1/nodes/lens-desktop-kube failed, reason: Hostname/IP does not match certificate's altnames: Host: 70d4025be74fd345d774947ee7c205f9.localhost. is not in the cert's altnames: DNS:*.lens.app, DNS:lens.app, DNS:localhost, IP Address:127.0.0.1
error:   ┃ [ 2]     at ClientRequest.<anonymous> (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/@k8slens/node-fetch/dist/index.js:2:81899)
error:   ┃ [ 3]     at ClientRequest.emit (node:events:526:28)
error:   ┃ [ 4]     at ClientRequest.emit (node:domain:475:12)
error:   ┃ [ 5]     at TLSSocket.socketErrorListener (node:_http_client:442:9)
error:   ┃ [ 6]     at TLSSocket.emit (node:events:526:28)
error:   ┃ [ 7]     at TLSSocket.emit (node:domain:475:12)
error:   ┃ [ 8]     at emitErrorNT (node:internal/streams/destroy:157:8)
error:   ┃ [ 9]     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
error:   ┃ [10]     at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
error:   ┃ [11] {
error:   ┃ [12]   type: 'system',
error:   ┃ [13]   errno: 'ERR_TLS_CERT_ALTNAME_INVALID',
error:   ┃ [14]   code: 'ERR_TLS_CERT_ALTNAME_INVALID',
error:   ┃ [15]   erroredSysCall: undefined
error:   ┗ [16] }
debug:   ┏ [UNIX-SHELL-ENV]: got the following output +1s
debug:   ┃ [1] {
debug:   ┃ [2]   rawOutput: 'Restored session: Fri Feb 10 14:32:19 EET 2023\n' +
debug:   ┃ [3]     `\x1B]7;file://jheikka-mbp13/Users/jheikka/code/oci-image-lens-extension\x07\x1B]7;file://jheikka-mbp13/Users/jheikka/code/oci-image-lens-extension\x07\x1Bk..ens-extension\x1B\\\x1B]7;file://jheikka-mbp13/Users/jheikka/code/oci-image-lens-extension\x07\x1Bk'/Applications/Lens.app/Contents/MacOS/Lens'\x1B\\175c65bc54a145be9aa936e9e5e807d4{"TERM_PROGRAM":"Apple_Terminal","SHELL":"/bin/zsh","TERM":"screen-256color-bce","TMPDIR":"/var/folders/wl/_p1nw_915w15n_bdh90jz9bm0000gn/T/","TERM_PROGRAM_VERSION":"447","TERM_SESSION_ID":"2772559C-42FA-4E43-9152-E779D74A3F01","USER":"jheikka","SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.CjbhpeNbZ0/Listeners","PATH":"/opt/homebrew/opt/openjdk/bin:/Users/jheikka/.local/bin:/Users/jheikka/.nvm/versions/node/v16.13.2/bin:/var/folders/wl/_p1nw_915w15n_bdh90jz9bm0000gn/T/fnm_multishells/75626_1676032363735/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/opt/openjdk/bin:/Users/jheikka/.local/bin:/Users/jheikka/.nvm/versions/node/v16.13.2/bin:/var/folders/wl/_p1nw_915w15n_bdh90jz9bm0000gn/T/fnm_multishells/73420_1676032092171/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/var/folders/wl/_p1nw_915w15n_bdh90jz9bm0000gn/T/fnm_multishells/12021_1675681949083/bin","__CFBundleIdentifier":"com.apple.Terminal","PWD":"/Users/jheikka/code/oci-image-lens-extension","XPC_FLAGS":"0x0","XPC_SERVICE_NAME":"0","SHLVL":"2","HOME":"/Users/jheikka","LOGNAME":"jheikka","OLDPWD":"/Users/jheikka/code/oci-image-lens-extension","HOMEBREW_PREFIX":"/opt/homebrew","HOMEBREW_CELLAR":"/opt/homebrew/Cellar","HOMEBREW_REPOSITORY":"/opt/homebrew","MANPATH":"/Users/jheikka/.nvm/versions/node/v16.13.2/share/man:/opt/homebrew/share/man:/usr/share/man:/usr/local/share/man:/Users/jheikka/.nvm/versions/node/v16.13.2/share/man:/opt/homebrew/share/man::","INFOPATH":"/opt/homebrew/share/info:/opt/homebrew/share/info:","ZSH":"/Users/jheikka/.oh-my-zsh","PAGER":"less","LESS":"-R","LSCOLORS":"Gxfxcxdxbxegedabagacad","FNM_MULTISHELL_PATH":"/var/folders/wl/_p1nw_915w15n_bdh90jz9bm0000gn/T/fnm_multishells/75626_1676032363735","FNM_DIR":"/Users/jheikka/.fnm","FNM_LOGLEVEL":"info","FNM_NODE_DIST_MIRROR":"https://nodejs.org/dist","FNM_ARCH":"arm64","LENS_DEV_USE_ESBUILD_LOADER":"true","NVM_DIR":"/Users/jheikka/.nvm","NVM_CD_FLAGS":"-q","NVM_BIN":"/Users/jheikka/.nvm/versions/node/v16.13.2/bin","NVM_INC":"/Users/jheikka/.nvm/versions/node/v16.13.2/include/node","CPPFLAGS":"-I/opt/homebrew/opt/openjdk/include","DEBUG":"true","__CF_USER_TEXT_ENCODING":"0x1F5:0x0:0x0","ORIGINAL_XDG_CURRENT_DESKTOP":"undefined","ELECTRON_RUN_AS_NODE":"1","ELECTRON_NO_ATTACH_CONSOLE":"1","LC_CTYPE":"UTF-8","_":"/Applications/Lens.app/Contents/MacOS/Lens"}175c65bc54a145be9aa936e9e5e807d4\n` +
debug:   ┃ [4]     '\x1B]7;file://jheikka-mbp13/Users/jheikka/code/oci-image-lens-extension\x07\x1Bk..ens-extension\x1B\\\x1B]7;file://jheikka-mbp13/Users/jheikka/code/oci-image-lens-extension\x07'
debug:   ┗ [5] }
```

**Additional context**
Happens for at least Lens Desktop Kube and Spaces clusters.

**Comment by alebcay** [comment]
See also #7091, which describes a similar (the same?) issue.

**Comment by Nokel81** [comment]
@alebcay That is the same issue. Thanks for reporting the connection.
