### ISSUE TITLE
bug in 2023.4.60821-latest

### ISSUE THREAD

**Issue by ndidenko-unit** [kontena/lens#7523]
Today's update in snap (2023.4.60821-latest) brokes Lens in Ubuntu 18.04.6 LTS with the following error:

Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /snap/kontena-lens/214/resources/app.asar.unpacked/node_modules/node-pty/build/Release/pty.node)

older versions work well

**Comment by SorianoMarmol** [comment]
Same issue

**Comment by aiellomau** [comment]
Same issue with Ubuntu 18.04.6 LTS as well.  
More details:

`A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /opt/Lens/resources/app.asar.unpacked/node_modules/node-pty/build/Release/pty.node)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1812)
    at Module._extensions..node (node:internal/modules/cjs/loader:1203:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:2039)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/opt/Lens/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:26:11)
    at Module._compile (node:internal/modules/cjs/loader:1118:14)
`

**Comment by maikfr** [comment]
Hi, the snap beta channel contains a version which is a little old, but it works (only tested on Ubuntu 18.04.6 LTS).
Obviously, it's not a solution for the problem, but it enabled me to continue my working-day :-)

**Comment by SorianoMarmol** [comment]
Is it going to be fixed or do I have to downgrade?

**Comment by Nokel81** [comment]
Thanks for this report. We will be solving this in a future release soon

**Comment by igorbrigadir** [comment]
Ran into this earlier too, it seems the culprit is NodeJS https://github.com/nodesource/distributions/issues/1392#issuecomment-1136582618

**Comment by Nokel81** [comment]
@igorbrigadir Probably not since we are still using NodeJS 16 (due to the version of electron the most recent versions of Lens Desktop are using)

**Comment by igorbrigadir** [comment]
Ah ok! On Ubuntu 18.04.6 LTS, this is the full error when installing the latest `deb` via apt https://docs.k8slens.dev/getting-started/install-lens/#debian and running `lense-desktop`:

```
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /opt/Lens/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /opt/Lens/resources/app.asar/node_modules/node-pty/lib/index.js
- /opt/Lens/resources/app.asar/node_modules/@k8slens/core/static/build/library/main.js
- /opt/Lens/resources/app.asar/static/build/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at n._resolveFilename (node:electron/js2c/browser_init:245:1105)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/opt/Lens/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (node:internal/modules/cjs/loader:1118:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:988:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/Lens/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/opt/Lens/resources/app.asar/node_modules/node-pty/lib/index.js',
    '/opt/Lens/resources/app.asar/node_modules/@k8slens/core/static/build/library/main.js',
    '/opt/Lens/resources/app.asar/static/build/main.js',
    undefined
  ]
}
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /opt/Lens/resources/app.asar.unpacked/node_modules/node-pty/build/Release/pty.node)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1812)
    at Module._extensions..node (node:internal/modules/cjs/loader:1203:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:2039)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/opt/Lens/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:26:11)
    at Module._compile (node:internal/modules/cjs/loader:1118:14)
mesa: for the --simplifycfg-sink-common option: may only occur zero or one times!
mesa: for the --global-isel-abort option: may only occur zero or one times!
mesa: for the --amdgpu-atomic-optimizations option: may only occur zero or one times!
```

I tried the latest AppImage instead, https://api.k8slens.dev/binaries/Lens-2023.4.141316-latest.x86_64.AppImage and got a similar error:

```
./Lens-2023.4.141316-latest.x86_64.AppImage 
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /tmp/.mount_Lens-2uL608e/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /tmp/.mount_Lens-2uL608e/resources/app.asar/node_modules/node-pty/lib/index.js
- /tmp/.mount_Lens-2uL608e/resources/app.asar/node_modules/@k8slens/core/static/build/library/main.js
- /tmp/.mount_Lens-2uL608e/resources/app.asar/static/build/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at n._resolveFilename (node:electron/js2c/browser_init:245:1105)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/tmp/.mount_Lens-2uL608e/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (node:internal/modules/cjs/loader:1118:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:988:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/tmp/.mount_Lens-2uL608e/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/tmp/.mount_Lens-2uL608e/resources/app.asar/node_modules/node-pty/lib/index.js',
    '/tmp/.mount_Lens-2uL608e/resources/app.asar/node_modules/@k8slens/core/static/build/library/main.js',
    '/tmp/.mount_Lens-2uL608e/resources/app.asar/static/build/main.js',
    undefined
  ]
}
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.mount_Lens-2uL608e/resources/app.asar.unpacked/node_modules/node-pty/build/Release/pty.node)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1812)
    at Module._extensions..node (node:internal/modules/cjs/loader:1203:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:2039)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/tmp/.mount_Lens-2uL608e/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:26:11)
    at Module._compile (node:internal/modules/cjs/loader:1118:14)
mesa: for the --simplifycfg-sink-common option: may only occur zero or one times!
mesa: for the --global-isel-abort option: may only occur zero or one times!
mesa: for the --amdgpu-atomic-optimizations option: may only occur zero or one times!
```

however, an older AppImage, https://downloads.k8slens.dev/ide/Lens-2023.1.110749-latest.x86_64.AppImage worked for me, so downgrading seems to be a good workaround. But it was very awkward to find a link to an older version for some reason, it would be easier if there were at least 2 or 3 links on the site - not just latest but the previous stable one too

**Comment by dayuanyuan1989** [comment]
ubuntu-16.04 has same error.

## versions

```vim
$ dpkg -l | grep lens
ii  lens                                          2023.4.141316-latest                            amd64        
ii  unity-lens-applications                       7.1.0+16.04.20160701-0ubuntu1                   amd64        Application lens for unity
ii  unity-lens-files                              7.1.0+16.04.20151217-0ubuntu1                   amd64        File lens for unity
ii  unity-lens-music                              6.9.1+16.04-0ubuntu1                            amd64        Music lens for unity
ii  unity-lens-photos                             1.0+14.04.20140318-0ubuntu1                     all          Photos lens for Unity
ii  unity-lens-video                              0.3.15+16.04.20160212.1-0ubuntu1                amd64        Unity Video lens
```

**Comment by jim-docker** [comment]
There is now a bionic channel on the Lens Debian repo for Ubuntu 18.04 versions of Lens Desktop. Instructions here: https://docs.k8slens.dev/getting-started/install-lens/#debian
