### ISSUE TITLE
Cannot create deployments with Lens

### ISSUE THREAD

**Issue by bruno-lopes** [kontena/lens#7647]
**Describe the bug**
When I try to create a new deployment (the default one generated by Lens)  I get messages like this: 

```
error: error validating "/tmp/8eb77a9eae663a8f884cbf7e06ad4684/resource.yaml": error validating data: invalid character '<' looking for beginning of value; if you choose to ignore these errors, turn validation off with --validate=false
```

 But it I use kubectl, the deployment gets created.

**To Reproduce**
1. Go to Deployments tab
2. Click on '+' -> 'Create resource'
3. Select Deployment in 'Select Template ...'
4. Click on Create

**Expected behavior**
The deployment should be created with success, since the yaml is correct

**Screenshots**

![image](https://user-images.githubusercontent.com/2408316/235362038-7fb0c2aa-762f-4e2b-9fd9-8c2809412de2.png)

**Environment (please complete the following information):**
- Lens Version: 2023.4.141316-latest
- OS: Linux Mint  21.1
- Installation method (e.g. snap or AppImage in Linux): DEB package

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
info:    ▪ 🔌 Starting LensProxy +0ms
info:    ▪ [LENS-PROXY]: Proxy server has started at 127.0.0.1:44101 +5ms
info:    ▪ 🔎 Testing LensProxy connection ... +1ms
info:    ▪ [LENS-USER-STORE]: LOADING ... +9ms
info:    ▪ [LENS-USER-STORE]: LOADED from /home/bruno/.config/Lens/lens-user-store.json +11ms
info:    ▪ [LENS-CLUSTER-STORE]: LOADING ... +0ms
[32369:0430/124103.903793:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
info:    ▪ [LENS-CLUSTER-STORE]: LOADED from /home/bruno/.config/Lens/lens-cluster-store.json +727ms
info:    ▪ ⚡ LensProxy connection OK +30ms

(lens-desktop:32326): dbind-WARNING **: 12:41:04.699: Couldn't connect to accessibility bus: Failed to connect to socket /root/.cache/at-spi/bus_0: Permission denied
warn:    ▪ No suitable icon found for task bar. +73ms
info:    ▪ [CREATE-ELECTRON-WINDOW]: Loading content for window "splash" from file: /opt/Lens/resources/app.asar/static/splash.html... +1ms
[32398:0430/124104.750726:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[32436:0430/124104.877519:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
info:    ▪ [CREATE-ELECTRON-WINDOW]: Window "splash" loaded +365ms
info:    ▪ [LENS-EXTENSIONS]: LOADING ... +5ms
info:    ▪ [LENS-EXTENSIONS]: LOADED from /home/bruno/.config/Lens/lens-extensions.json +2ms
info:    ▪ [LENS-WEBLINK-STORE]: LOADING ... +19ms
info:    ▪ [LENS-WEBLINK-STORE]: LOADED from /home/bruno/.config/Lens/lens-weblink-store.json +8ms
info:    ▪ 📟 Setting protocol client for lens:// +12ms
info:    ▪ 📟 Protocol client register failed ❗ +21ms
info:    ▪ [LENS-FILESYSTEM-PROVISIONER-STORE]: LOADING ... +16ms
info:    ▪ [LENS-FILESYSTEM-PROVISIONER-STORE]: LOADED from /home/bruno/.config/Lens/lens-filesystem-provisioner-store.json +1ms
info:    ▪ 🐚 Syncing shell environment +1ms
info:    ┏ [UNIX-SHELL-ENV]: running against /bin/zsh +1ms
info:    ┃ [1] {
info:    ┃ [2]   command: ` '/opt/Lens/lens-desktop' -p '"61337575e588412a8a0e2cccc4847661" + JSON.stringify(process.env) + "61337575e588412a8a0e2cccc4847661"'`,
info:    ┃ [3]   shellArgs: [ '-l', '-i' ]
info:    ┗ [4] }
info:    ▪ [LENS-HOTBAR-STORE]: LOADING ... +28ms
info:    ▪ [LENS-HOTBAR-STORE]: LOADED from /home/bruno/.config/Lens/lens-hotbar-store.json +3ms
APPIMAGE env is not defined, current application is not an AppImage
APPIMAGE env is not defined, current application is not an AppImage
info:    ▪ [SHELL-SYNC]: Synced shell env +301ms
info:    ▪ 🧩 Initializing extensions +1ms
info:    ▪ [EXTENSIONS-LOADER]: auto initializing extensions +1ms
info:    ▪ [CLI] activated +181ms
info:    ▪ [CLOUD-PROVIDER-SYNC-EXTENSION] activated +22ms
info:    ▪ [LENS-DESKTOP-KUBE] onActivate +188ms
info:    ▪ [LDK-STORE]: LOADING ... +1ms
info:    ▪ [LDK-STORE]: LOADED from /home/bruno/.config/Lens/extension-store/lens-desktop-kube-lens-extension/ldk-store.json +1ms
License main extension activated
Native extraction module not loaded, msgpackr will still run, but with decreased performance. Cannot find module 'msgpackr-extract'
[ELECTRON-SYNC-STORE]: 2023-04-30T15:41:06.087Z - select-space-store ~ ElectronSyncStore:initialize, path /home/bruno/.config/Lens/extension-store/lenscloud-lens-extension/select-space-store.json
[ELECTRON-SYNC-STORE]: 2023-04-30T15:41:06.087Z - startup-store ~ ElectronSyncStore:initialize, path /home/bruno/.config/Lens/extension-store/lenscloud-lens-extension/startup-store.json
info:    ▪ [SECURITY-PREFERENCES-STORE]: LOADING ... +415ms
info:    ▪ [SECURITY-PREFERENCES-STORE]: LOADED from /home/bruno/.config/Lens/extension-store/oci-image-lens-extension/security-preferences-store.json +9ms
info:    ▪ [SUPPORT-EXTENSION] activated +66ms
info:    ▪ [PREFERENCES-STORE]: LOADING ... +2ms
info:    ▪ [PREFERENCES-STORE]: LOADED from /home/bruno/.config/Lens/extension-store/survey-lens-extension/preferences-store.json +0ms
info:    ▪ [TOUR-EXTENSION] activated +118ms
info:    ▪ [TIP-STORE]: LOADING ... +0ms
info:    ▪ [TIP-STORE]: LOADED from /home/bruno/.config/Lens/extension-store/tour-lens-extension/tip-store.json +1ms
info:    ▪ [LENS-DESKTOP-KUBE] extracting virtual machine runtime files ... +46ms
[ELECTRON-SYNC-STORE]: 2023-04-30T15:41:06.566Z - select-space-store ~ ElectronSyncStore:initialize, model {"65d20766-d859-4b55-8d20-2777373002bf":{"spaceId":"offline","isPersonalSpace":true,"spaceName":"offline"}}
[ELECTRON-SYNC-STORE]: 2023-04-30T15:41:06.567Z - select-space-store ~ ipcListen
[ELECTRON-SYNC-STORE]: 2023-04-30T15:41:06.568Z - startup-store ~ ElectronSyncStore:initialize, model {"skipSignup":false}
[ELECTRON-SYNC-STORE]: 2023-04-30T15:41:06.568Z - startup-store ~ ipcListen
telemetry main extension activated
info:    ▪ [PREFERENCES-STORE]: LOADING ... +20ms
info:    ▪ [PREFERENCES-STORE]: LOADED from /home/bruno/.config/Lens/extension-store/telemetry-lens-extension/preferences-store.json +9ms
info:    ▪ [LOCAL-METADATA-STORE]: LOADING ... +49ms
info:    ▪ [LOCAL-METADATA-STORE]: LOADED from /home/bruno/.config/Lens/extension-store/lenscloud-lens-extension/local-metadata-store.json +1ms
info:    ▪ [RELEASE-NOTES-STORE]: LOADING ... +0ms
info:    ▪ [RELEASE-NOTES-STORE]: LOADED from /home/bruno/.config/Lens/extension-store/lenscloud-lens-extension/release-notes-store.json +2ms
info:    ▪ [END-OF-TRIAL-STORE]: LOADING ... +1ms
info:    ▪ [END-OF-TRIAL-STORE]: LOADED from /home/bruno/.config/Lens/extension-store/lenscloud-lens-extension/end-of-trial-store.json +1ms
info:    ▪ [GRACE-PERIOD-STORE]: LOADING ... +1ms
info:    ▪ [GRACE-PERIOD-STORE]: LOADED from /home/bruno/.config/Lens/extension-store/lenscloud-lens-extension/grace-period-store.json +1ms
info:    ▪ [SPACES-SETTINGS-STORE]: LOADING ... +1ms
info:    ▪ [SPACES-SETTINGS-STORE]: LOADED from /home/bruno/.config/Lens/extension-store/lenscloud-lens-extension/spaces-settings-store.json +7ms
info:    ▪ [LENS-SPACES-EXTENSION]: 4/30/2023, 12:41:06 PM Broadcasted spaces change to SpacesListener on renderer +92ms
warn:    ▪ [LENS-SPACES-EXTENSION]: 4/30/2023, 12:41:06 PM No spaces in SpaceSyncer disposeSpacesReaction, not changing selected space. +0ms
info:    ▪ [LENS-SPACES-EXTENSION]: 4/30/2023, 12:41:06 PM Lens Spaces Extension activated +6ms
info:    ▪ [LENS-SECURITY] activated +104ms
warn:    ▪ [LENS-DESKTOP-KUBE] not a valid lens subscription, stopping ... +111ms
info:    ▪ [EXTENSION]: enabled @lensapp/cli-lens-extension@0.16.1 +54ms
info:    ▪ [EXTENSION]: enabled @lensapp/cloud-provider-sync-extension@0.2.0 +0ms
info:    ▪ [EXTENSION]: enabled @lensapp/lens-desktop-kube-lens-extension@0.26.2 +0ms
info:    ▪ [EXTENSION]: enabled @lensapp/lens-license-extension@0.14.0 +0ms
info:    ▪ [EXTENSION]: enabled @lensapp/lenscloud-lens-extension@1.30.0 +1ms
info:    ▪ [EXTENSION]: enabled @lensapp/oci-image-lens-extension@0.28.0 +0ms
info:    ▪ [EXTENSION]: enabled @lensapp/support-lens-extension@0.11.0 +0ms
info:    ▪ [EXTENSION]: enabled @lensapp/survey-lens-extension@0.6.0 +0ms
info:    ▪ [EXTENSION]: enabled @lensapp/telemetry-lens-extension@0.8.0 +0ms
info:    ▪ [EXTENSION]: enabled @lensapp/tour-lens-extension@1.7.0 +0ms
info:    ▪ [EXTENSION-DISCOVERY] loading extensions from /home/bruno/.config/Lens +2ms
info:    ▪ [EXTENSION-DISCOVERY] watching extension add/remove in /home/bruno/.k8slens/extensions +16ms
info:    ▪ [BASE-STORE]: saving /home/bruno/.config/Lens/lens-extensions.json... +9ms
warn:    ▪ No suitable icon found for task bar. +12ms
info:    ▪ [CREATE-ELECTRON-WINDOW]: Loading content for window "first-application-window" from url: https://lens.app:44101... +1ms
[32326:0430/124107.093345:ERROR:cert_verify_proc_builtin.cc(681)] CertVerifyProcBuiltin for 127.0.0.1 failed:
----- Certificate i=0 (O=Lens,CN=Lens Certificate Authority) -----
ERROR: No matching issuer found


warn:    ┏ [LENS-SPACES-EXTENSION]: (from:onRefreshTokenError) 4/30/2023, 12:41:07 PM InvalidGrantError error, reset Lens state and set connected=false... Offline user session not found +392ms
warn:    ┃ [1] Error: Offline user session not found
warn:    ┃ [2]     at t.refreshTokens (/opt/Lens/resources/app.asar/node_modules/@lensapp/lenscloud-lens-extension/dist/main.js:2:31016)
warn:    ┃ [3]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
warn:    ┗ [4]     at async AuthTokenStore.refresh (/opt/Lens/resources/app.asar/node_modules/@lensapp/lenscloud-lens-extension/dist/main.js:2:45593)
info:    ▪ [LENS-SPACES-EXTENSION]: (from:resetSpaceSyncer) Clearing spaces/k8sClusters... +2ms
error:   ▪ [LENS-SPACES-EXTENSION]: 4/30/2023, 12:41:07 PM Error: Offline user session not found +5ms
warn:    ▪ [LENS-SPACES-EXTENSION]: 4/30/2023, 12:41:07 PM Couldn't refresh tokens, starting token refresher later. +0ms
info:    ▪ [LENS-SPACES-EXTENSION]: 4/30/2023, 12:41:07 PM isLensCloudStatusOk on initialization returns true +324ms
info:    ▪ [CREATE-ELECTRON-WINDOW]: Window "first-application-window" loaded +2s
[ELECTRON-SYNC-STORE]: 2023-04-30T15:41:10.751Z - select-space-store ~ ipc electron-sync-store:renderer:initialize:select-space-store received
[ELECTRON-SYNC-STORE]: 2023-04-30T15:41:10.752Z - select-space-store ~ ipc electron-sync-store:renderer:initialize:select-space-store received
[ELECTRON-SYNC-STORE]: 2023-04-30T15:41:10.752Z - startup-store ~ ipc electron-sync-store:renderer:initialize:startup-store received
[ELECTRON-SYNC-STORE]: 2023-04-30T15:41:10.839Z - select-space-store ~ ipc electron-sync-store:renderer:initialize:select-space-store received
[ELECTRON-SYNC-STORE]: 2023-04-30T15:41:10.839Z - startup-store ~ ipc electron-sync-store:renderer:initialize:startup-store received
APPIMAGE env is not defined, current application is not an AppImage
info:    ▪ [KUBECONFIG-SYNC]: starting requested syncs +2s
info:    ┏ [KUBECONFIG-SYNC]: starting sync of file/folder +1ms
info:    ┗ [1] { filePath: '/home/bruno/.config/Lens/kubeconfigs' }
info:    ┏ [KUBECONFIG-SYNC]: starting sync of file/folder +0ms
info:    ┗ [1] { filePath: '/home/bruno/.kube' }
info:    ┏ [KUBECONFIG-SYNC]: starting sync of file/folder +1ms
info:    ┗ [1] { filePath: '/home/bruno/git/canalBL2/site/infraestrutura/terraform/artifacts' }
info:    ┏ [KUBECONFIG-SYNC]: starting sync of file/folder +0ms
info:    ┗ [1] { filePath: '/home/bruno/.kube/config-oci' }
info:    ┏ [CLUSTER]: activate +3s
info:    ┃ [1] {
info:    ┃ [2]   id: '17befacc65fd4acfb0ad748706b02fc9',
info:    ┃ [3]   name: 'Canal BL2',
info:    ┃ [4]   ready: false,
info:    ┃ [5]   online: false,
info:    ┃ [6]   accessible: false,
info:    ┃ [7]   disconnected: true
info:    ┗ [8] }
info:    ┏ [CLUSTER]: bind events +0ms
info:    ┃ [1] {
info:    ┃ [2]   id: '17befacc65fd4acfb0ad748706b02fc9',
info:    ┃ [3]   name: 'Canal BL2',
info:    ┃ [4]   ready: false,
info:    ┃ [5]   online: false,
info:    ┃ [6]   accessible: false,
info:    ┃ [7]   disconnected: true
info:    ┗ [8] }
info:    ┏ [CLUSTER]: reconnect +1ms
info:    ┃ [1] {
info:    ┃ [2]   id: '17befacc65fd4acfb0ad748706b02fc9',
info:    ┃ [3]   name: 'Canal BL2',
info:    ┃ [4]   ready: false,
info:    ┃ [5]   online: false,
info:    ┃ [6]   accessible: false,
info:    ┃ [7]   disconnected: true
info:    ┗ [8] }
info:    ▪ [KUBE-AUTH-PROXY]: found port=41641 +37ms
info:    ┏ [CLUSTER]: refreshAccessibility +99ms
info:    ┃ [1] {
info:    ┃ [2]   id: '17befacc65fd4acfb0ad748706b02fc9',
info:    ┃ [3]   name: 'Canal BL2',
info:    ┃ [4]   ready: false,
info:    ┃ [5]   online: true,
info:    ┃ [6]   accessible: true,
info:    ┃ [7]   disconnected: false
info:    ┗ [8] }
[ELECTRON-SYNC-STORE]: 2023-04-30T15:41:17.711Z - select-space-store ~ ipc electron-sync-store:renderer:initialize:select-space-store received
[ELECTRON-SYNC-STORE]: 2023-04-30T15:41:17.712Z - select-space-store ~ ipc electron-sync-store:renderer:initialize:select-space-store received
[ELECTRON-SYNC-STORE]: 2023-04-30T15:41:17.712Z - startup-store ~ ipc electron-sync-store:renderer:initialize:startup-store received
[ELECTRON-SYNC-STORE]: 2023-04-30T15:41:18.068Z - select-space-store ~ ipc electron-sync-store:renderer:initialize:select-space-store received
[ELECTRON-SYNC-STORE]: 2023-04-30T15:41:18.068Z - startup-store ~ ipc electron-sync-store:renderer:initialize:startup-store received
warn:    ┏ [METRICS-ROUTE]: failed to get metrics for clusterId=17befacc65fd4acfb0ad748706b02fc9: No Prometheus service found +3s
warn:    ┃ [ 1] Error: No Prometheus service found
warn:    ┃ [ 2]     at ContextHandler.getPrometheusService (/opt/Lens/resources/app.asar/node_modules/@k8slens/core/static/build/library/main.js:36167:15)
warn:    ┃ [ 3]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
warn:    ┃ [ 4]     at async ContextHandler.getPrometheusDetails (/opt/Lens/resources/app.asar/node_modules/@k8slens/core/static/build/library/main.js:36119:25)
warn:    ┃ [ 5]     at async /opt/Lens/resources/app.asar/node_modules/@k8slens/core/static/build/library/main.js:45285:54
warn:    ┃ [ 6]     at async Object.route (/opt/Lens/resources/app.asar/node_modules/@k8slens/core/static/build/library/main.js:44150:32)
warn:    ┃ [ 7]     at async Router.route (/opt/Lens/resources/app.asar/node_modules/@k8slens/core/static/build/library/main.js:44381:9)
warn:    ┃ [ 8]     at async LensProxy.handleRequest (/opt/Lens/resources/app.asar/node_modules/@k8slens/core/static/build/library/main.js:41894:9)
warn:    ┃ [ 9] Cause:
warn:    ┃ [10]     {
warn:    ┃ [11]       '0': Error: Failed to find Prometheus provider for "Lens"
warn:    ┃ [12]           at Object.getPrometheusService (/opt/Lens/resources/app.asar/node_modules/@k8slens/core/static/build/library/main.js:43134:19)
warn:    ┃ [13]           at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
warn:    ┃ [14]           at async Promise.allSettled (index 0)
warn:    ┃ [15]           ... 5 lines matching cause stack trace ...
warn:    ┃ [16]           at async LensProxy.handleRequest (/opt/Lens/resources/app.asar/node_modules/@k8slens/core/static/build/library/main.js:41894:9) {
warn:    ┃ [17]         [cause]: Error: Failed to list services in namespace="lens-metrics": services "prometheus" not found
warn:    ┃ [18]             at findNamespacedService (/opt/Lens/resources/app.asar/node_modules/@k8slens/core/static/build/library/main.js:43171:15)
warn:    ┃ [19]             at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
warn:    ┃ [20]             at async Object.getPrometheusService (/opt/Lens/resources/app.asar/node_modules/@k8slens/core/static/build/library/main.js:43130:20)
warn:    ┃ [21]             at async Promise.allSettled (index 0)
warn:    ┃ [22]             at async ContextHandler.getPrometheusService (/opt/Lens/resources/app.asar/node_modules/@k8slens/core/static/build/library/main.js:36154:35)
warn:    ┃ [23]             at async ContextHandler.getPrometheusDetails (/opt/Lens/resources/app.asar/node_modules/@k8slens/core/static/build/library/main.js:36119:25)
warn:    ┃ [24]             at async /opt/Lens/resources/app.asar/node_modules/@k8slens/core/static/build/library/main.js:45285:54
warn:    ┃ [25]             at async Object.route (/opt/Lens/resources/app.asar/node_modules/@k8slens/core/static/build/library/main.js:44150:32)
warn:    ┃ [26]             at async Router.route (/opt/Lens/resources/app.asar/node_modules/@k8slens/core/static/build/library/main.js:44381:9)
warn:    ┃ [27]             at async LensProxy.handleRequest (/opt/Lens/resources/app.asar/node_modules/@k8slens/core/static/build/library/main.js:41894:9)
warn:    ┃ [28]       }
warn:    ┗ [29]     }
info:    ┏ [UNIX-SHELL-ENV]: running against /bin/zsh +7s
info:    ┃ [1] {
info:    ┃ [2]   command: ` '/opt/Lens/lens-desktop' -p '"fa27001956b54c7e80fe3ccf4612b877" + JSON.stringify(process.env) + "fa27001956b54c7e80fe3ccf4612b877"'`,
info:    ┃ [3]   shellArgs: [ '-l', '-i' ]
info:    ┗ [4] }
info:    ▪ [SHELL-SESSION]: PTY for 17befacc65fd4acfb0ad748706b02fc9:dbfe4229-f066-4ac6-8f9e-d1aafdfeb2e3 is started with PID=32833 +323ms
info:    ┏ [SHELL-SESSION]: websocket for 17befacc65fd4acfb0ad748706b02fc9:dbfe4229-f066-4ac6-8f9e-d1aafdfeb2e3 closed with code=NoStatusReceived(1005) +5s
info:    ┃ [ 1] {
info:    ┃ [ 2]   cluster: {
info:    ┃ [ 3]     id: '17befacc65fd4acfb0ad748706b02fc9',
info:    ┃ [ 4]     name: 'Canal BL2',
info:    ┃ [ 5]     ready: true,
info:    ┃ [ 6]     online: true,
info:    ┃ [ 7]     accessible: true,
info:    ┃ [ 8]     disconnected: false
info:    ┃ [ 9]   }
info:    ┗ [10] }
info:    ▪ [SHELL-SESSION]: Killing shell process (pid=32833) for 17befacc65fd4acfb0ad748706b02fc9:dbfe4229-f066-4ac6-8f9e-d1aafdfeb2e3 +1ms
info:    ▪ [SHELL-SESSION]: shell has exited for 17befacc65fd4acfb0ad748706b02fc9:dbfe4229-f066-4ac6-8f9e-d1aafdfeb2e3 closed with exitcode=1 +3ms
info:    ┏ [CLUSTER]: refresh +15s
info:    ┃ [1] {
info:    ┃ [2]   id: '17befacc65fd4acfb0ad748706b02fc9',
info:    ┃ [3]   name: 'Canal BL2',
info:    ┃ [4]   ready: true,
info:    ┃ [5]   online: true,
info:    ┃ [6]   accessible: true,
info:    ┃ [7]   disconnected: false
info:    ┗ [8] }
info:    ┏ [CLUSTER]: refresh +30s
info:    ┃ [1] {
info:    ┃ [2]   id: '17befacc65fd4acfb0ad748706b02fc9',
info:    ┃ [3]   name: 'Canal BL2',
info:    ┃ [4]   ready: true,
info:    ┃ [5]   online: true,
info:    ┃ [6]   accessible: true,
info:    ┃ [7]   disconnected: false
info:    ┗ [8] }

```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <CERTIFICATE_AUTHORITY_DATA>
    server: https://<MY_DOMAIN>:8443
  name: local
contexts:
- context:
    cluster: local
    user: user
  name: CBL2
current-context: CBL2
kind: Config
preferences: {}
users:
- name: user
  user:
    client-certificate-data: <CLIENT_CERTIFICATE_DATA>
    client-key-data: <CLIENT_KEY_DATA>

```

**Additional context**
The same yaml can be applied to the cluster using kubectl

**Comment by bruno-lopes** [comment]
In preferences, I set PATH TO KUBECTL BINARY to use my own kubectl version, and now everything is working. When KUBECTL BINARY DOWNLOAD was set to true, I got the error that I have described.

**Comment by bruno-lopes** [comment]
Kubectl and Kubernetes versions:

```
kubectl version --short                                                                                                                                                                                          
Client Version: v1.25.4
Kustomize Version: v4.5.7
Server Version: v1.27.1+k0s
WARNING: version difference between client (1.25) and server (1.27) exceeds the supported minor version skew of +/-1
```

**Comment by panuhorsmalahti** [comment]
This is a known issue with Kubernetes 1.27.1. It should be fixed in Kubernetes 1.27.2, target day May 17th.

k8s issue: https://github.com/kubernetes/kubernetes/issues/117463

**Comment by rimelek** [comment]
This error wouldn't happen if Lens didn't use a proxy server. Is that proxy necessary for some reason? Lens also uses a different kube config where that proxy url is defined to change the original endpoint and the KUBECONFIG variable points to that config when I use the embedded terminal in Lens. To be honest I am not comfortable sending traffic through a proxy that I don't know what it does exactly. It is possible that it is well-documented somehwre, but I still haven't found it. At least I think I found the sourcecode so I can check that to understand it.

https://github.com/lensapp/lens/blob/0c7a0b37873f34d81545419ed4fb56fc9158593c/packages/core/src/main/lens-proxy/lens-proxy.ts#L6

Couldn't that proxy be optional in case someone prefers not to have an additional layer between the cluster and Lens?

**Comment by Nokel81** [comment]
@rimelek That is one of the proxies that we use currently and not it is not possible for it to be optional as it is currently fundamental to the architecture of Lens. We might take spend some time simplifying this architecture, but we plan to always use the proxy code from the kubernetes client-go library, as it handles the authentication and simplifies working with the kubernetes API directly.

**Comment by JOSERMI** [comment]
> In preferences, I set PATH TO KUBECTL BINARY to use my own kubectl version, and now everything is working. When KUBECTL BINARY DOWNLOAD was set to true, I got the error that I have described.

Thanks, that worked for me
