### ISSUE TITLE
App crash at /deployments

### ISSUE THREAD

**Issue by danielecazzari** [kontena/lens#7841]
**Describe the bug**
I'm trying to enter deployment details of one of my cluster, this always result in a crash. No changes if I restart the app or force refresh.  This is a AKS cluster v1.26.3. 

This is the component stack:
Component stack:

    at d (C:\Users\dazari\.k8slens\extensions\kubescape--lens-extension\dist\renderer.js:1:33486)
    at Details
    at div
    at div
    at div
    at NonInjectedAnimate (https://68a6e585acb0b82d10bfcd1a2dce6784.lens.app:55120/build/lens.js?3009659a76e484a218f8:46115:13)
    at NonInjectedDrawer (https://68a6e585acb0b82d10bfcd1a2dce6784.lens.app:55120/build/lens.js?3009659a76e484a218f8:62741:9)
    at observerComponent (https://68a6e585acb0b82d10bfcd1a2dce6784.lens.app:55120/build/lens.js?3009659a76e484a218f8:376039:16)
    at ObserverComponent (https://68a6e585acb0b82d10bfcd1a2dce6784.lens.app:55120/build/lens.js?3009659a76e484a218f8:376087:23)
    at c (https://68a6e585acb0b82d10bfcd1a2dce6784.lens.app:55120/build/lens.js?3009659a76e484a218f8:663703:673)
    at observerComponent (https://68a6e585acb0b82d10bfcd1a2dce6784.lens.app:55120/build/lens.js?3009659a76e484a218f8:376039:16)
    at ObserverComponent (https://68a6e585acb0b82d10bfcd1a2dce6784.lens.app:55120/build/lens.js?3009659a76e484a218f8:376087:23)
    at observerComponent (https://68a6e585acb0b82d10bfcd1a2dce6784.lens.app:55120/build/lens.js?3009659a76e484a218f8:376039:16)
    at https://68a6e585acb0b82d10bfcd1a2dce6784.lens.app:55120/build/lens.js?3009659a76e484a218f8:663724:1641
    at ThemeProvider (https://68a6e585acb0b82d10bfcd1a2dce6784.lens.app:55120/build/lens.js?3009659a76e484a218f8:241171:24)
    at https://68a6e585acb0b82d10bfcd1a2dce6784.lens.app:55120/build/lens.js?3009659a76e484a218f8:41213:28
    at Router (https://68a6e585acb0b82d10bfcd1a2dce6784.lens.app:55120/build/lens.js?3009659a76e484a218f8:605421:30)
    at https://68a6e585acb0b82d10bfcd1a2dce6784.lens.app:55120/build/lens.js?3009659a76e484a218f8:41213:28
    at observerComponent (https://68a6e585acb0b82d10bfcd1a2dce6784.lens.app:55120/build/lens.js?3009659a76e484a218f8:376039:16)

This is the Error Stack
Error stack:

TypeError: Cannot read properties of undefined (reading 'controls')
    at d.render (C:\Users\dazari\.k8slens\extensions\kubescape--lens-extension\dist\renderer.js:1:33585)
    at qi (https://68a6e585acb0b82d10bfcd1a2dce6784.lens.app:55120/build/lens.js?3009659a76e484a218f8:603970:188)
    at pi (https://68a6e585acb0b82d10bfcd1a2dce6784.lens.app:55120/build/lens.js?3009659a76e484a218f8:603969:173)
    at ck (https://68a6e585acb0b82d10bfcd1a2dce6784.lens.app:55120/build/lens.js?3009659a76e484a218f8:604052:427)
    at bk (https://68a6e585acb0b82d10bfcd1a2dce6784.lens.app:55120/build/lens.js?3009659a76e484a218f8:604033:347)
    at ak (https://68a6e585acb0b82d10bfcd1a2dce6784.lens.app:55120/build/lens.js?3009659a76e484a218f8:604033:278)
    at Tj (https://68a6e585acb0b82d10bfcd1a2dce6784.lens.app:55120/build/lens.js?3009659a76e484a218f8:604033:138)
    at Lj (https://68a6e585acb0b82d10bfcd1a2dce6784.lens.app:55120/build/lens.js?3009659a76e484a218f8:604026:163)
    at https://68a6e585acb0b82d10bfcd1a2dce6784.lens.app:55120/build/lens.js?3009659a76e484a218f8:603906:115
    at exports.unstable_runWithPriority (https://68a6e585acb0b82d10bfcd1a2dce6784.lens.app:55120/build/lens.js?3009659a76e484a218f8:624924:343)

**Comment by MartyB-007** [comment]
+1, also experiencing this issue and exact stack trace on the /pods & /deployments endpoints on AKS 1.25.6.

Seems to only happen on my 1.25 cluster. My old 1.21 and 1.24 clusters both allow me to grab info without error.

**Comment by stanezil** [comment]
+1, also experiencing this on GKE 1.26.2

**Comment by fpetr** [comment]
What helped me was to temporary disable kubescape extensions as this seems to be root cause of the problem.

**Comment by stanezil** [comment]
@fpetr  Great catch mate! This solved the issue for me

**Comment by josue-skyhop** [comment]
@fpetr Thanks, this solved my issue too when i selected a pod then it crashed trying to render the GUI. The culprit was Kubecscape extension. 🏆
