### ISSUE TITLE
Unable to display metrics using Lens-installed builtin Prometheus

### ISSUE THREAD

**Issue by Rezrazi** [kontena/lens#7888]
**Describe the bug**
Having a freshly created EKS cluster, I've added the config to Lens, and enabled the builtin metrics provider (Settings > Builtin Metric Provider > Enable all)
<img width="737" alt="CleanShot 2023-08-05 at 09 02 33@2x" src="https://github.com/lensapp/lens/assets/2086576/affa08e3-7fb6-4a2f-bc61-4cbf23cc4dd3">

I do see the resource created under the lens-metrics namespace
<img width="1134" alt="CleanShot 2023-08-05 at 09 03 00@2x" src="https://github.com/lensapp/lens/assets/2086576/81df2f9a-457e-484c-8097-71995881ad85">

However the metrics are loading forever
<img width="1150" alt="CleanShot 2023-08-05 at 09 03 25@2x" src="https://github.com/lensapp/lens/assets/2086576/26a6937d-1490-404d-9ac3-3a9428eda385">

**To Reproduce**

**Expected behavior**
I expect the charts to display correctly

**Environment (please complete the following information):**
Lens: 2023.5.310801-latest
Extension API: 6.5.2
Electron: 22.3.10
Chrome: 108.0.5359.215
Node: 16.17.1
MacOS 13.4

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
info:    ▪ [CONTEXT-HANDLER]: using lens as prometheus provider for clusterId=0d38661990a5de1dae829143ca9bd3c9 +23s
info:    ┏ [CLUSTER]: refresh +7s
info:    ┃ [1] {
info:    ┃ [2]   id: '0d38661990a5de1dae829143ca9bd3c9',
info:    ┃ [3]   name: 'arn:aws:eks:eu-west-3:<id>:cluster/monitoring',
info:    ┃ [4]   ready: true,
info:    ┃ [5]   online: true,
info:    ┃ [6]   accessible: true,
info:    ┃ [7]   disconnected: false
info:    ┗ [8] }
warn:    ┏ [METRICS-ROUTE]: failed to get metrics for clusterId=0d38661990a5de1dae829143ca9bd3c9: Metrics not available +12s
warn:    ┃ [ 1] Error: Metrics not available
warn:    ┃ [ 2]     at loadMetricHelper (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/@k8slens/core/static/build/library/main.js:49771:31)
warn:    ┃ [ 3]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
warn:    ┃ [ 4]     at async Promise.all (index 0)
warn:    ┃ [ 5]     at async /Applications/Lens.app/Contents/Resources/app.asar/node_modules/@k8slens/core/static/build/library/main.js:49816:36
warn:    ┃ [ 6]     at async Object.route (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/@k8slens/core/static/build/library/main.js:48738:32)
warn:    ┃ [ 7]     at async Router.route (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/@k8slens/core/static/build/library/main.js:48969:9)
warn:    ┃ [ 8]     at async LensProxy.handleRequest (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/@k8slens/core/static/build/library/main.js:46327:9)
warn:    ┃ [ 9] Cause:
warn:    ┗ [10]     { type: 'system', errno: 'ECONNRESET', code: 'ECONNRESET', erroredSysCall: undefined }

```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**
EKS Kubernetes 1.27

I have another cluster running 1.23, in which I ran the helm install kube-prometheus-stack command, and the metrics are showing correctly on that one
<img width="1070" alt="CleanShot 2023-08-05 at 09 07 41@2x" src="https://github.com/lensapp/lens/assets/2086576/0622b1c6-94ba-4386-a276-f749917fcf19">

**Comment by robervexcel** [comment]
Interested, I update from 1.24 until 1.27 and in 1.27 version the metrics disappear in the same cluster (I tested in 3 EKS clusters)

I'm pending to test this solution -> https://github.com/lensapp/lens/issues/7667#issuecomment-1547979332

**Comment by trjo1016** [comment]
Hello everybody, I am also working on displaying metrics on Lens UI, these are my settings:

![image](https://github.com/lensapp/lens/assets/81167386/1f1a5b69-b99c-4cb2-90ed-e9271d6a5d16)
![image](https://github.com/lensapp/lens/assets/81167386/5133f906-33f2-4516-89f4-2741f35251f0)

I can expose the port and forward the new prometheus pod. Then I can use prometheus in the browser, but it doesn't load the metrics in the UI what so ever.

I am clueless to how to implement the solution @robervexcel offered. Is there an easier way?

**Comment by sfrolich** [comment]
Same here. Every EKS cluster we have upgraded from 1.24 to 1.25 have all lost metrics through Lens.
